### ISSUE TITLE
[21.12] Errors during make uninstall

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#1014]
## Description

Make uninstall shows the following errors (even after fresh installation)
```
Uninstalling Open-CAS modules
depmod: ERROR: fstatat(4, cas_cache.ko): No such file or directory
depmod: ERROR: fstatat(4, cas_disk.ko): No such file or directory
```

## Steps to Reproduce

1. Install Open-CAS using `make`
2. Enter sources folder and call `make uninstall`

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master (some previous builds as well)
* Operating System: RHEL 8.3

**Comment by rafalste** [comment]
During CAS RPM installation additional symlinks are created by weak-modules script to handle compatible kernel usage, but manual CAS installation using `make && make install` doesn't do that.
The reason for this depmod error is that CAS was previously installed from RPM and then before removed, it was overwritten by manual `make install`, resulting in leftover broken symlinks used by depmod.
To resolve this issue, simply uninstall CAS RPMs.
