### ISSUE TITLE
[21.12] Standby cache activated with different ID than that of an active cache

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#1018]
## Description

Standby cache was configured with cache id 2. Active cache was started with cache id 1.
Exported object on main node: /dev/cas1-1; exported object on secondary node (after activation): /dev/cas2-1

## Expected Behavior

Activation of the standby cache should be blocked.

## Actual Behavior

Activation was successful with activated cache using cache id 2.

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master
* Operating System: RHEL 8.3

**Comment by karolinavelkaja** [comment]
Need to validate on newest CAS version

**Comment by mmichal10** [comment]
I've been able to reporoduce it on the current master master (OCL: https://github.com/Open-CAS/open-cas-linux/commit/1742841ee35060781d74d70b5a87c839b227edda ocf [6af8d20ceef7](https://github.com/Open-CAS/ocf/commit/6af8d20ceef70898364b5742feba5d6b2743fb29))
