### ISSUE TITLE
[21.12] Calling `casadm --list` after detach doesn't produce a proper output

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#1020]
## Description

After a standby cache is detached, `casadm --list` produces an error output.

## Expected Behavior

```
# casadm -L
type    id   disk             status    write policy   device
cache   1    /dev/nvme2n1p1   Standby   -              -      # <-- maybe status Detached?
```

## Actual Behavior

```
# casadm -L
Failed to retrieve cache information
```

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master

**Comment by kmajzero** [comment]
Closing as the relater PR has been merged
