### ISSUE TITLE
[21.12] Add device for standby cache in `casadm --list`

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#1021]
## Description

Cache exported object is not displayed in `casadm --list` output

## Reason

Core exported objects are displayed, I think it would be consistent to display cache exported objects as well.

## Proposed behavior
```
# casadm -L
type    id   disk             status    write policy   device
cache   1    /dev/nvme2n1p1   Standby   -              /dev/cas-cache-1
```

**Comment by Deixx** [comment]
After detach set state `Standby detached`

**Comment by pdebski21** [comment]
fix presented in https://github.com/Open-CAS/open-cas-linux/pull/1059 patch
