### ISSUE TITLE
[21.12] Activation succeeds when a file with core exported object name exists

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#1022]
## Description

When a regular file /dev/cas1-1 exists, standby cache activation succeeds.

## Expected Behavior

Same as on load in similar situation
```
# casadm --failover-activate --cache-id 1 --cache-device /dev/drbd0
Error inserting cache 1
Could not create exported object because file in /dev directory exists
Error occurred, please see syslog (/var/log/messages) for details.
```

## Actual Behavior

```
# casadm --failover-activate --cache-id 1 --cache-device /dev/drbd0
Could not create exported object because file in /dev directory exists
# casadm -L
type    id   disk             status    write policy   device
cache   1    /dev/drbd0       Running   wb             -
└core   1    /dev/nvme0n1p1   Active    -              /dev/cas1-1
```

## Steps to Reproduce

1. Standard DRBD setup
2. Fail primary node
3. `touch /dev/cas1-1` before activation
4. Activate standby cache

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master

**Comment by karolinavelkaja** [comment]
Need to investigate possible fixes and when to implement this - which release.

**Comment by karolinavelkaja** [comment]
CAS need to fail in such case (cache stop in rollback) - current solution for issue.
