### ISSUE TITLE
[21.12] Error message when activating wrong caching device - "Invalid input parameter" could be better

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#1024]
## Description

Activation of passing cache with wrong cache device results with information "Invalid input parameter" which is not really meaningful. 
It would be awesome to get precise information what happened (activation aborted and why) :)
In dmesg logs there is "cache1: Superblock mismatch!" which may be some example of information.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master

**Comment by pdebski21** [comment]
added addtional error code and more descriptive message.
fix in those pull requests:
[(https://github.com/Open-CAS/ocf/pull/640)]
[https://github.com/Open-CAS/open-cas-linux/pull/1045]
