### ISSUE TITLE
opencas configuration error

### ISSUE THREAD

**Issue by elham9449** [Open-CAS/open-cas-linux#1031]
Hi!
I have a question about configuring cas.
Can the case be configured with a type scsi disk?
I'm trying to configure cache with type scsi disk, which returns the following error message:
Error inserting cache 1
Invalid input parameter

How can I fix it?
Many tnx!

**Comment by mmichal10** [comment]
Hello @elham9449,

perhaps you are trying to create cache instance with a device path in `/dev/sd*` format? As mentioned in [the documentation](https://open-cas.github.io/guide_tool_details.html#-s----start-cache) you have to provide path in `/dev/disk/by-id/*` format. Could you provide the command you are using? 

Best regards

**Comment by elham9449** [comment]
> Hello @elham9449,
> 
> perhaps you are trying to create cache instance with a device path in `/dev/sd*` format? As mentioned in [the documentation](https://open-cas.github.io/guide_tool_details.html#-s----start-cache) you have to provide path in `/dev/disk/by-id/*` format. Could you provide the command you are using?
> 
> Best regards

This is the command which I used:
casadm -S -d /dev/disk/by-id/scsi-1ATA_Micron_5100_MTFDDAK3T8TBY_* -i 1 -x 8 -c wb -f

**Comment by robertbaldyga** [comment]
@elham9449 What version of Open CAS you are using (`casadm -V`)? Can you provide output of `dmesg` command?

**Comment by elham9449** [comment]
> `dmesg`

opencas version: 21.03.0.0496.release
output of dmesg command:
[219804.741938]  sde: sde1
[278370.336542]  sde: sde1 sde2
[278370.342245]  sde: sde1 sde2
 and kernel version:  3.10.0-1160.el7.x86_64

**Comment by elham9449** [comment]
> @elham9449 What version of Open CAS are you using (`casadm -V`)? Can you provide output of `dmesg` command?



> @elham9449 What version of Open CAS are you using (`casadm -V`)? Can you provide output of `dmesg` command?

 opencas version: 21.03.0.0496.release
output of dmesg command:
[219804.741938] sde: sde1
[278370.336542] sde: sde1 sde2
[278370.342245] sde: sde1 sde2
and kernel version: 3.10.0-1160.el7.x86_64

**Comment by mmichal10** [comment]
This error may occur if you are trying to start cache instance with an id which is already in use. To check if that is the case you can use `casadm -L` to see the list of all the running cache instances.

**Comment by mmichal10** [comment]
@elham9449 have you solved the problem? If so, I would like to close this issue.

**Comment by elham9449** [comment]
Yes. The problem was solved by another version of opencas and GCC.
Thanks!
