### ISSUE TITLE
High latency on  the Intel cas device 

### ISSUE THREAD

**Issue by wuyan6293** [Open-CAS/open-cas-linux#1039]
## Description

![image](https://user-images.githubusercontent.com/5463273/148383835-69832ece-b894-4ddd-84bb-23b04a16d56d.png)

As shown in the figure above, the await of the cas device is very high, but the await of the cache and core devices are not high.

* intelcas9-1 await:14974.17    r_await:21437.33     w_await:11552.50
* nvme1n1 await:1.44         r_await:0.89    w_await:2.09
* sdj await: 5.57    r_await:5.17    w_await:5.58

The wait of the cas device is so exaggerated. 

This is ps and top output in the same time:

![image](https://user-images.githubusercontent.com/5463273/148384876-9b1d4a44-30c6-4162-afc5-78920191eb20.png)

![image](https://user-images.githubusercontent.com/5463273/148384996-5be83006-f474-4c7b-bec1-c39b71afa60a.png)

## Your Environment

* OpenCAS version (commit hash or tag): Intel CAS： 03.08.00.01601108
* Operating System: Redhat 7.5 
* Kernel version: 3.10.0-862.11.6.el7.x86_64
* Cache device type (NAND/Optane/other):  NVMe SSD
* Core device type (HDD/SSD/other): HDD
* Cache configuration:
* * Cache mode: (default: wt) wb
* * Cache line size: (default: 4) 8
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru) acp
* * Sequential cutoff policy: (default: full) off
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)
![image](https://user-images.githubusercontent.com/5463273/148383394-c973f9ae-7e82-45bd-8fb3-5d1fe5337c11.png)

**Comment by gaowayne** [comment]
@wuyan6293 intel cas is already out of support cycle. could you please start try opencas latest release? better use Optane SSD P5800 as cache device, we tuned very well for it.

**Comment by wuyan6293** [comment]
> 

Yes, this version was installed and deployed on a historical customer. The latest version of opencas has been used in our latest products. We want to confirm whether this phenomenon is similar to a known bug, or it is not a problem with the cas software itself.

**Comment by jfckm** [comment]
@wuyan6293 I'm having trouble understanding - you now use latest version, but this results are from IntelCAS 3.8? If so, please retest this scenario with newest OpenCAS release

**Comment by arutk** [comment]
Hi @wuyan6293. Any update on this?

**Comment by karolinavelkaja** [comment]
Hello,
The Intel CAS Enterprise for Linux product is not supported through GitHub (only OpenCAS is). We do not show any current/valid support contracts for Intel CAS Enterprise. If the end user has a current/valid support contract, please have them contact Intel Technical Support by phone at 800-404-2284 or at the following URL: http://www.intel.com/support/go/cas for help with their issue.
