### ISSUE TITLE
Can I set activity-threshold params in the opencas.conf

### ISSUE THREAD

**Issue by mslovy** [Open-CAS/open-cas-linux#1054]
## Question
Can I set activity-threshold params in the opencas.conf when using alru cleaning policy?

## Motivation
I want to persistent the **activity-threshold** params during the system reboot and opencas upgrading. I find that the Extra flags in the configuration file can only persistent the **cleaning_policy** in the docs --> https://open-cas.github.io/guide_configuring.html.

## Your Environment

* OpenCAS version (commit hash or tag): 21.06.3.0551.release
* Operating System: CentOS 7.8
* Kernel version: 3.10.0-1127.el7.x86_64
* Cache device type (NAND/Optane/other): NVME
* Core device type (HDD/SSD/other): HDD
* Cache configuration:
* * Cache mode: (default: wb)
* * Cache line size: (default: 4)
* * Promotion policy: (default: nhit)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by robertbaldyga** [comment]
Cleaning policy parameters are stored in cache metadata on the drive and Open CAS restores them on cache load, so they can persist without need to add them in the config. Also the cleaning policy is stored in persistent metadata, so this option in config is somehow redundant.

**Comment by mslovy** [comment]
this is helpful, thanks for your reply.
