### ISSUE TITLE
Still some of pass-through writes when setting seq-cutoff policy to never

### ISSUE THREAD

**Issue by mslovy** [Open-CAS/open-cas-linux#1055]
## Question
When I set the seq-cutoff policy to never, why the sequencial IO still skip to core device?

## Motivation
Currentlly, PCIE 4.0 has both high bandwidth and IOPS. The NVME ssd performance rarely be saturated so that all write IO can write to NVME ssd first and then flush to the core devices.

I find that although my cache occupancy is high, almost all cache blocks are clean.  So I expect that all write IO can evict the least recenlty used cache blocks and cache into the nvme ssd device.

However, actually still some writes skip the cache device and write to the core device directly, why?

## Your Environment
OpenCAS version (commit hash or tag): 21.06.3.0551.release
Operating System: CentOS 7.8
Kernel version: 3.10.0-1127.el7.x86_64
Cache device type (NAND/Optane/other): NVME
Core device type (HDD/SSD/other): HDD
Cache configuration:
Cache mode: (default: wb)
Cache line size: (default: 4)
Promotion policy: (default: nhit)
Cleaning policy: (default: alru)
Sequential cutoff policy: (default: never)
Others:

# casadm -P -i 1
Cache Id                  1
Cache Size                483296886 [4KiB Blocks] / 1843.63 [GiB]
Cache Device              /dev/nvme0n1
Core Devices              12
Inactive Core Devices     0
Write Policy              wb
Cleaning Policy           alru
Promotion Policy          nhit
Cache line size           4 [KiB]
Metadata Memory Footprint 21.2 [GiB]
Dirty for                 123413 [s] / 1 [d] 10 [h] 16 [m] 53 [s]
Metadata Mode             normal
Status                    Running

╔══════════════════╤═══════════╤══════╤═════════════╗
║ Usage statistics │   Count   │  %   │   Units     ║
╠══════════════════╪═══════════╪══════╪═════════════╣
║ Occupancy        │ 396558832 │ 82.1 │ 4KiB Blocks ║
║ Free             │  86738054 │ 17.9 │ 4KiB Blocks ║
║ Clean            │ 396442573 │ 82.0 │ 4KiB Blocks ║
║ Dirty            │    116259 │  0.0 │ 4KiB Blocks ║
╚══════════════════╧═══════════╧══════╧═════════════╝

╔══════════════════════╤══════════╤═══════╤══════════╗
║ Request statistics   │  Count   │   %   │ Units    ║
╠══════════════════════╪══════════╪═══════╪══════════╣
║ Read hits            │ 10030305 │  12.0 │ Requests ║
║ Read partial misses  │   269665 │   0.3 │ Requests ║
║ Read full misses     │  8829384 │  10.6 │ Requests ║
║ Read total           │ 19129354 │  22.9 │ Requests ║
╟──────────────────────┼──────────┼───────┼──────────╢
║ Write hits           │ 37415887 │  44.8 │ Requests ║
║ Write partial misses │   546507 │   0.7 │ Requests ║
║ Write full misses    │  5569372 │   6.7 │ Requests ║
║ Write total          │ 43531766 │  52.1 │ Requests ║
╟──────────────────────┼──────────┼───────┼──────────╢
║ Pass-Through reads   │ 16789591 │  20.1 │ Requests ║
║ Pass-Through writes  │  4099548 │   4.9 │ Requests ║
║ Serviced requests    │ 62661120 │  75.0 │ Requests ║
╟──────────────────────┼──────────┼───────┼──────────╢
║ Total requests       │ 83550259 │ 100.0 │ Requests ║
╚══════════════════════╧══════════╧═══════╧══════════╝

╔══════════════════════════════════╤════════════╤═══════╤═════════════╗
║ Block statistics                 │   Count    │   %   │   Units     ║
╠══════════════════════════════════╪════════════╪═══════╪═════════════╣
║ Reads from core(s)               │  702940731 │  66.0 │ 4KiB Blocks ║
║ Writes to core(s)                │  362149233 │  34.0 │ 4KiB Blocks ║
║ Total to/from core(s)            │ 1065089964 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼────────────┼───────┼─────────────╢
║ Reads from cache                 │  328949221 │  35.4 │ 4KiB Blocks ║
║ Writes to cache                  │  599712517 │  64.6 │ 4KiB Blocks ║
║ Total to/from cache              │  928661738 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼────────────┼───────┼─────────────╢
║ Reads from exported object(s)    │  776600296 │  62.6 │ 4KiB Blocks ║
║ Writes to exported object(s)     │  463617358 │  37.4 │ 4KiB Blocks ║
║ Total to/from exported object(s) │ 1240217654 │ 100.0 │ 4KiB Blocks ║
╚══════════════════════════════════╧════════════╧═══════╧═════════════╝

# casadm -P -i 1  -j 1
Core Id              1
Core Device          /dev/sdd
Exported Object      /dev/cas1-1
Core Size            976754646 [4KiB Blocks] / 3726.02 [GiB]
Dirty for            123484 [s] / 1 [d] 10 [h] 18 [m] 4 [s]
Status               Active
Seq cutoff threshold 1024 [KiB]
Seq cutoff policy    never

╔══════════════════╤══════════╤═══════╤═════════════╗
║ Usage statistics │  Count   │   %   │   Units     ║
╠══════════════════╪══════════╪═══════╪═════════════╣
║ Occupancy        │ 21828660 │   4.5 │ 4KiB Blocks ║
║ Free             │ 86723359 │  17.9 │ 4KiB Blocks ║
║ Clean            │ 21820132 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │     8528 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧══════════╧═══════╧═════════════╝

╔══════════════════════╤═════════╤═══════╤══════════╗
║ Request statistics   │  Count  │   %   │ Units    ║
╠══════════════════════╪═════════╪═══════╪══════════╣
║ Read hits            │  682378 │  10.8 │ Requests ║
║ Read partial misses  │   38823 │   0.6 │ Requests ║
║ Read full misses     │  378200 │   6.0 │ Requests ║
║ Read total           │ 1099401 │  17.4 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Write hits           │ 3122264 │  49.4 │ Requests ║
║ Write partial misses │   36749 │   0.6 │ Requests ║
║ Write full misses    │  419416 │   6.6 │ Requests ║
║ Write total          │ 3578429 │  56.6 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Pass-Through reads   │ 1349215 │  21.3 │ Requests ║
║ Pass-Through writes  │  295454 │   4.7 │ Requests ║
║ Serviced requests    │ 4677830 │  74.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Total requests       │ 6322499 │ 100.0 │ Requests ║
╚══════════════════════╧═════════╧═══════╧══════════╝

╔═══════════════════════════════╤══════════╤═══════╤═════════════╗
║ Block statistics              │  Count   │   %   │   Units     ║
╠═══════════════════════════════╪══════════╪═══════╪═════════════╣
║ Reads from core               │ 46057001 │  62.4 │ 4KiB Blocks ║
║ Writes to core                │ 27786345 │  37.6 │ 4KiB Blocks ║
║ Total to/from core            │ 73843346 │ 100.0 │ 4KiB Blocks ║
╟───────────────────────────────┼──────────┼───────┼─────────────╢
║ Reads from cache              │ 25469735 │  39.6 │ 4KiB Blocks ║
║ Writes to cache               │ 38860656 │  60.4 │ 4KiB Blocks ║
║ Total to/from cache           │ 64330391 │ 100.0 │ 4KiB Blocks ║
╟───────────────────────────────┼──────────┼───────┼─────────────╢
║ Reads from exported object    │ 51494253 │  58.5 │ 4KiB Blocks ║
║ Writes to exported object     │ 36517058 │  41.5 │ 4KiB Blocks ║
║ Total to/from exported object │ 88011311 │ 100.0 │ 4KiB Blocks ║
╚═══════════════════════════════╧══════════╧═══════╧═════════════╝

**Comment by jfckm** [comment]
hi @mslovy, thanks for your report!

I don't know your workload exactly, but what may be causing pass-through IOs in your configuration is nhit promotion policy. It specifically engages pass-through for requests that weren't marked for promotion (containing core LBAs that weren't touched required number of times). Small caveat: we have limited memory dedicated to nhit, so it can only track `size_of_cache_in_cachelines * NHIT_MAPPING_RATIO`, where NHIT_MAPPING_RATIO is currently 2.

**Comment by mslovy** [comment]
@jfckm  so you mean nhit not only works on reads,  also on writes? I share another observer that when the cache occupancy is quite low, this is no pass-through writes at all.

Is that possible to let nhit just works on reads? I think if I setting cache mode to write-only, then there is no reads will be cached and this is also not I want. But if I setting promotion policy to always, then the cache polute quite rapidlly by such as period scrub IO and performance drops dramatically. thx

**Comment by jfckm** [comment]
yes, promotion works on any I/O that would put data in cache - in writeback that means both on reads and writes. That is also a feature of nhit promotion policy - policy trigger threshold, which tells the nhit policy on what cache occupancy level it should engage (default - 80%).

It's not possible without changing the code unfortunately. Maybe there are some other characteristics of those period scrub IOs you're talking about that could be handled with IO-classification? If you could pin down the right classification rules you could prevent those IOs from caching.

**Comment by mslovy** [comment]
thanks, @jfckm. After I change the promotion policy to always, it seems no other pass-through io now.

Since I use opencas in ceph-osd which uses the raw device like /dev/cas-1 directly, filesystem based characteristics cannot be used on this. Although scrub or data recovery IO read/write data with certain chunk size (such as 512KB), there is also other client IO may be just 512KB. Therefore, certain io-size classification is also not a reasonable solution. Beside, for the pid pin io-classification, it is also not possible since the scrub io threads' pid is hard to identified and it will be changed after the daemon  restart.

**Comment by mslovy** [comment]
@jfckm  not exactly sequential. It is object based sequential, which means one object (such as 4MB data should be sequential), but  consecutive objects do not mean consecutive LBA on raw disk. There is a metadata describing the mapping for the object to LBA on disk.
And it is much more complicated  to explain the detail in the allocator to allocate blobs for each object, sometimes small piece of data overwrite may make the object data itself fragment like a filesystem. If you want to know more detail about the allocator ,you can refer to slide 22~25 in https://www.snia.org/sites/default/files/SDC/2017/presentations/General_Session/Weil_Sage%20_Red_Hat_Goodbye_XFS_Building_a_new_faster_storage_backend_for_Ceph.pdf  

I think what we need is don't let nhit policy works on writeops. I know the flashcache do that and auto evict the cleaning cacheset during writing if use writeback mode. That is what we always do when use a ssd as a cache to deal with suddenly heavy writeops.

**Comment by jfckm** [comment]
I see, that would indeed be helpful in this scenario. It should be relatively easy to implement.

Quick and dirty hack, if you want to try it, would be just to put a check for request direction (`req->rw`) and return true if it's a write.
Here:
https://github.com/Open-CAS/ocf/blob/021e7e87ad87e53db7fc6acb33f1ea83fb377f8f/src/promotion/nhit/nhit.c#L228

If we were to implement that that would probably need some more comprehensive and configurable solution. Right now we're swamped with 21.12, but I'll keep you posted on any developments and if we decide to put it on roadmap somewhere.

**Comment by mslovy** [comment]
Oh, that would be great.  thanks for your guide to help me quick find the logic, and I would try it with a quick hack.

**Comment by jfckm** [comment]
Tracked here: https://github.com/Open-CAS/ocf/issues/658
