### ISSUE TITLE
Can't activate standby cache when undelaying device contains partitions

### ISSUE THREAD

**Issue by mmichal10** [Open-CAS/open-cas-linux#1065]
If it is allowed to start cache on a device with partitions, it should be also possible to activate standby instance on a such device. 

[dut~]# lsblk /dev/nvme0n1
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 349.3G  0 disk 
`-nvme0n1p1 259:1    0   200G  0 part 
```

[dut~]# casadm --standby --activate -i 2 -d <path_by_id>
```
Device contains partitions.
If you want to continue, please use --force option.
Warning: all data will be lost!
```

[dut~]# casadm --standby --activate -i 2 -d <path_by_id> -f
```
Option '--force (-f)' is not allowed
```

**Comment by jfckm** [comment]
Investigate how those partitions are in there after standby.

**Comment by kmajzero** [comment]
It is possible to crash the kernel with the following:

1. sudo casadm --standby --init -i 1 -x 4 -d /dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_666-cache --force

sudo fdisk -l /dev/sda:

Disk /dev/sda: 16 GiB, 17179869184 bytes, 33554432 sectors
Disk model: QEMU HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

2. sudo cfdisk /dev/sda #created 3 partitions 8G, 4G, 4G

dmesg:
[ 1244.977134] [CAS Disk] Partition 1 on sda hidden
[ 1244.977238] [CAS Disk] Partition 2 on sda hidden
[ 1244.977336] [CAS Disk] Partition 3 on sda hidden
[ 1244.977415] [CAS Disk] Partition 4 on sda hidden

sudo fdisk -l /dev/sda:
Disk /dev/sda: 16 GiB, 17179869184 bytes, 33554432 sectors
Disk model: QEMU HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 30109B4F-5943-4E43-BAB2-6318B576807B

Device        Start      End  Sectors Size Type
/dev/sda1      2048 16779263 16777216   8G Linux filesystem
/dev/sda2  16779264 25167871  8388608   4G Linux filesystem
/dev/sda3  25167872 33554398  8386527   4G Linux filesystem

sudo fdisk -l /dev/cas-cache-1:
Disk /dev/cas-cache-1: 16 GiB, 17179869184 bytes, 33554432 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 30109B4F-5943-4E43-BAB2-6318B576807B

Device                Start      End  Sectors Size Type
/dev/cas-cache-1p1     2048 16779263 16777216   8G Linux filesystem
/dev/cas-cache-1p2 16779264 25167871  8388608   4G Linux filesystem
/dev/cas-cache-1p3 25167872 33554398  8386527   4G Linux filesystem


3. sudo cfdisk /dev/cas-cache-1 # last 3 partitions visible, the last one was deleted and two 2G partitions were created
# notice the partition table discrepancy between /dev/sda and /dev/cas-cache-1 

dmesg:
[ 1552.321772]  cas-cache-1: p1 p2 p3
[ 1562.805697]  cas-cache-1: p1 p2 p3 p4
[ 1564.457237]  cas-cache-1: p1 p2 p3 p4

sudo fdisk -l /dev/sda:
Disk /dev/sda: 16 GiB, 17179869184 bytes, 33554432 sectors
Disk model: QEMU HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 30109B4F-5943-4E43-BAB2-6318B576807B

Device        Start      End  Sectors Size Type
/dev/sda1      2048 16779263 16777216   8G Linux filesystem
/dev/sda2  16779264 25167871  8388608   4G Linux filesystem
/dev/sda3  25167872 33554398  8386527   4G Linux filesystem


sudo fdisk -l /dev/cas-cache-1:
Disk /dev/cas-cache-1: 16 GiB, 17179869184 bytes, 33554432 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 30109B4F-5943-4E43-BAB2-6318B576807B

Device                Start      End  Sectors Size Type
/dev/cas-cache-1p1     2048 16779263 16777216   8G Linux filesystem
/dev/cas-cache-1p2 16779264 25167871  8388608   4G Linux filesystem
/dev/cas-cache-1p3 25167872 29362175  4194304   2G Linux filesystem
/dev/cas-cache-1p4 29362176 33554398  4192223   2G Linux filesystem


4. sudo casadm --standby --detach -i 1 # notice that now the partition tables are "synced"

dmesg:
[ 2363.884990]  sda: sda1 sda2 sda3 sda4

sudo fdisk -l /dev/sda:
Disk /dev/sda: 16 GiB, 17179869184 bytes, 33554432 sectors
Disk model: QEMU HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 30109B4F-5943-4E43-BAB2-6318B576807B

Device        Start      End  Sectors Size Type
/dev/sda1      2048 16779263 16777216   8G Linux filesystem
/dev/sda2  16779264 25167871  8388608   4G Linux filesystem
/dev/sda3  25167872 29362175  4194304   2G Linux filesystem
/dev/sda4  29362176 33554398  4192223   2G Linux filesystem


5. sudo casadm --standby --activate -i 1 -d /dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_666-cache
Device contains partitions.
If you want to continue, please use --force option.
Warning: all data will be lost!

6. sudo casadm --standby --activate -i 1 -d /dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_666-cache --force
Option '--force (-f)' is not allowed

and after some time (notice the timestamp of dmesg messages) 

$ sudo casadm --standby --activate -i 1 -d /dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_666-cache --force 
Option '--force (-f)' is not allowed

$ sudo casadm --standby --activate -i 1 -d /dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_666-cache
Device contains partitions.
If you want to continue, please use --force option
Warning: all data will be lost!

$ sudo casadm -T -i

[ 3486.085397] general protection fault: 0000 [#1] SMP PTI
[ 3486.085674] CPU: 3 PID: 80971 Comm: casadm Tainted: G           OE     5.4.0-100-generic #113-Ubuntu
[ 3486.085906] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.13.0-1ubuntu1.1 04/01/2014
[ 3486.086151] RIP: 0010:casdsk_exp_obj_lock+0x14/0x60 [cas_disk]
[ 3486.086372] Code: 10 00 00 00 00 31 c0 5b 5d c3 0f 0b 0f 0b 0f 0b 66 0f 1f 44 00 00 0f 1f 44 00 00 48 85 ff 74 46 55 48 89 e5 41 54 49 89 fc 53 <48> 8b
 9f e0 00 00 00 48 85 db 74 32 48 8b 3b 31 f6 e8 26 21 1c df
[ 3486.086794] RSP: 0018:ffffb6f000f3bcd0 EFLAGS: 00010206
[ 3486.086921] RAX: ffffffffc0920480 RBX: ffff92f099d0cb40 RCX: 0000000000000001
[ 3486.087052] RDX: ffffb6f000407080 RSI: ffffffffc099ff10 RDI: 7f60523f7ab00950
[ 3486.087184] RBP: ffffb6f000f3bce0 R08: 0000032baadda65b R09: 000000000002fe00
[ 3486.087315] R10: 0000000000000003 R11: 0000000000000010 R12: 7f60523f7ab00950
[ 3486.087447] R13: ffffb6f000f3be08 R14: ffff92f0991a6840 R15: ffff92f0963cfb00
[ 3486.087579] FS:  00007f5d7784c740(0000) GS:ffff92f0a7780000(0000) knlGS:0000000000000000
[ 3486.087758] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3486.087890] CR2: 00007f5d7784afb8 CR3: 0000000662104002 CR4: 0000000000160ee0
[ 3486.088026] Call Trace:
[ 3486.088204]  kcas_volume_destroy_exported_object+0x2c/0x80 [cas_cache]
[ 3486.088367]  kcas_cache_destroy_exported_object+0x16/0x20 [cas_cache]
[ 3486.088510]  cache_mngt_exit_instance+0xda/0x230 [cas_cache]
[ 3486.088649]  cas_service_ioctl_ctrl+0x13e1/0x2510 [cas_cache]
[ 3486.088807]  ? enqueue_task_fair+0xeb/0x560
[ 3486.088943]  ? x2apic_send_IPI+0x4d/0x60
[ 3486.089070]  ? native_smp_send_reschedule+0x2a/0x40
[ 3486.089116]  ? resched_curr+0x5e/0xc0
[ 3486.089116]  ? check_preempt_curr+0x4e/0x90
[ 3486.089116]  ? wake_up_new_task+0x1dd/0x290
[ 3486.089116]  do_vfs_ioctl+0x407/0x670
[ 3486.089116]  ? _do_fork+0xfa/0x360
[ 3486.089116]  ksys_ioctl+0x67/0x90
[ 3486.089116]  __x64_sys_ioctl+0x1a/0x20
[ 3486.089116]  do_syscall_64+0x57/0x190
[ 3486.089116]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 3486.089116] RIP: 0033:0x7f5d7796650b
[ 3486.089116] Code: 0f 1e fa 48 8b 05 85 39 0d 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa b8 10 00 00 00 0f 05 <48> 3d
 01 f0 ff ff 73 01 c3 48 8b 0d 55 39 0d 00 f7 d8 64 89 01 48
[ 3486.089116] RSP: 002b:00007ffda437a2d8 EFLAGS: 00000293 ORIG_RAX: 0000000000000010
[ 3486.089116] RAX: ffffffffffffffda RBX: 000055760d85d0e0 RCX: 00007f5d7796650b
[ 3486.089116] RDX: 00007ffda437a478 RSI: ffffffffc008ba02 RDI: 0000000000000005
[ 3486.089116] RBP: 00007ffda437a310 R08: 0000000000000000 R09: 00007f5d7784b700
[ 3486.089116] R10: 00007f5d7784b9d0 R11: 0000000000000293 R12: 000055760d844ae0
[ 3486.089116] R13: 00007ffda437c700 R14: 0000000000000000 R15: 0000000000000000
[ 3486.089116] Modules linked in: ufs qnx4 hfsplus hfs minix ntfs msdos jfs xfs cas_cache(OE) cas_disk(OE) dm_multipath scsi_dh_rdac scsi_dh_emc scsi_dh_a
lua intel_rapl_msr intel_rapl_common snd_hda_codec_generic kvm_intel ledtrig_audio kvm snd_hda_intel snd_intel_dspcfg snd_hda_codec snd_hda_core snd_hwdep
 joydev snd_pcm snd_timer input_leds serio_raw snd soundcore qemu_fw_cfg mac_hid sch_fq_codel msr virtio_rng ip_tables x_tables autofs4 btrfs zstd_compres
s raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear hid_generic usbhid hid crc
t10dif_pclmul crc32_pclmul ghash_clmulni_intel qxl ttm aesni_intel crypto_simd drm_kms_helper psmouse cryptd glue_helper syscopyarea sysfillrect sysimgblt
 fb_sys_fops virtio_scsi virtio_net ahci net_failover failover i2c_i801 libahci lpc_ich drm virtio_blk
[ 3486.096021] ---[ end trace 9d24109122e66ec9 ]---
[ 3486.096981] RIP: 0010:casdsk_exp_obj_lock+0x14/0x60 [cas_disk]
[ 3486.097888] Code: 10 00 00 00 00 31 c0 5b 5d c3 0f 0b 0f 0b 0f 0b 66 0f 1f 44 00 00 0f 1f 44 00 00 48 85 ff 74 46 55 48 89 e5 41 54 49 89 fc 53 <48> 8b
 9f e0 00 00 00 48 85 db 74 32 48 8b 3b 31 f6 e8 26 21 1c df
[ 3486.099745] RSP: 0018:ffffb6f000f3bcd0 EFLAGS: 00010206
[ 3486.100680] RAX: ffffffffc0920480 RBX: ffff92f099d0cb40 RCX: 0000000000000001
[ 3486.101720] RDX: ffffb6f000407080 RSI: ffffffffc099ff10 RDI: 7f60523f7ab00950
[ 3486.102980] RBP: ffffb6f000f3bce0 R08: 0000032baadda65b R09: 000000000002fe00
[ 3486.103908] R10: 0000000000000003 R11: 0000000000000010 R12: 7f60523f7ab00950
[ 3486.104818] R13: ffffb6f000f3be08 R14: ffff92f0991a6840 R15: ffff92f0963cfb00
[ 3486.105703] FS:  00007f5d7784c740(0000) GS:ffff92f0a7780000(0000) knlGS:0000000000000000
[ 3486.106600] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3486.107486] CR2: 00007f5d7784afb8 CR3: 0000000662104002 CR4: 0000000000160ee0
