### ISSUE TITLE
Invalid management operation does not provide error message (Purge cache)

### ISSUE THREAD

**Issue by pdebski21** [Open-CAS/open-cas-linux#1117]
## Description
Not allowed in standby state management operation does not provide error message

## Expected Behavior
[root@localhost open-cas-linux]# casadm --script --purge-cache --cache-id 1
Cannot purge cache while cache 1 is in standby mode

## Actual Behavior
[root@localhost open-cas-linux]# casadm --script --purge-cache --cache-id 1

**Comment by arutk** [comment]
https://github.com/Open-CAS/ocf/pull/678/files
