### ISSUE TITLE
1_vmalloc.conf failed on phytium arm64

### ISSUE THREAD

**Issue by jshen28** [Open-CAS/open-cas-linux#1121]
## Description

Configure failed on phytium arm64 machine

## Expected Behavior

Should succeed?

## Actual Behavior

```console
# ./configure
Preparing configuration
ERROR! Following steps failed while preparing config:
1_vmalloc.conf
```

## Steps to Reproduce

1. Download latest tarball
2. Then configure

## Your Environment

* OpenCAS version (commit hash or tag): 21.06.3.0551
* Operating System: kylin v10
* Kernel version: 4.19.90-25.9.v2101.ky10.aarch64
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by jshen28** [comment]
https://github.com/Open-CAS/open-cas-linux/commit/3d23b6d08f51c2d4f18a009dd73f8da163d7bf9b

**Comment by robertbaldyga** [comment]
You're right. Btw next OpenCAS release (v22.3) is expected within next two weeks.
