### ISSUE TITLE
Is it possible to bind a cache_device with multiple core devices?

### ISSUE THREAD

**Issue by GrayXu** [Open-CAS/open-cas-linux#1123]
## Question

Is it possible to bind a cache_device with multiple core devices?  

## Motivation  

It seems like Intel CAS in Windows can support caching different directories across different disks.

**Comment by robertbaldyga** [comment]
Yes, once you start a cache with `casadm --start-cache` you can run `casadm --add-core` many times to add multiple core devices to that cache. For example creating cache and adding three cores to it may look like this:
```
# casadm --start-cache --cache-id 1 --device /dev/disk/by-id/CACHE
# casadm  --add-core --cache-id 1 --core-id 1 --device /dev/disk/by-id/CORE1
# casadm  --add-core --cache-id 1 --core-id 2 --device /dev/disk/by-id/CORE2
# casadm  --add-core --cache-id 1 --core-id 3 --device /dev/disk/by-id/CORE3
```

**Comment by GrayXu** [comment]
thanks a lot!
