### ISSUE TITLE
Is it possible to recover data after `--force`

### ISSUE THREAD

**Issue by GrayXu** [Open-CAS/open-cas-linux#1160]
## Question

I set cache device in `wb` mode. After I reboot this machine without `casctl stop –flush`, `/dev/cas*-*` can't auto reload.   
And I wrongly start Open CAS with `casadm -S -d /dev/disk/by-id/nvme-INTEL_MEMPEK1J016GAL_PHBT8465005N016N --force -x 64 -c wb` instead of `casadm -S -d /dev/disk/by-id/nvme-INTEL_SSD -l`. So as a result I lost a part of newly written data.

Under this circumstance, is it possible to recover those dirty data in the cache device? since Optane is persistent storage...

## Your Environment

* OpenCAS version (commit hash or tag): 22.03.0.0629.master
* Operating System: Ubuntu 21
* Kernel version: 5.11.0-49-generic
* Cache device type (NAND/Optane/other): Optane M10 16G
* Core device type (HDD/SSD/other): HDD
* Cache configuration:
* * Cache mode: (default: wb)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by robertbaldyga** [comment]
I'm afraid it's not possible. Starting cache with `--force` overwrites all the metadata on the drive, so there is no way to recover the data.

**Comment by GrayXu** [comment]
Thank!
