### ISSUE TITLE
Can't add core to core pool without specifying core id

### ISSUE THREAD

**Issue by mmichal10** [Open-CAS/open-cas-linux#1189]
Adding core to core pool fails if no core id has been provided. Command:
`casadm --script --add-core --cache-id 1 --core-device <path_by_id> --try-add`
<information about non existing cache>

But it works when an user specifies core id in the command:
`casadm --script --add-core --cache-id 1 --core-id 1 --core-device <by_id_path> --try-add`

Probably the bug was introduced with https://github.com/Open-CAS/open-cas-linux/pull/1040

**Comment by jfckm** [comment]
I think it was by accident if it worked previously. Do you see any potential use for that? From my point of view it's only used by loader which gets core/cache-ids from config - no problem here. On the other hand I'd say it's difficult to get right (finding new core-ids when there's no cache which "stores" used core-ids).

**Comment by mmichal10** [comment]
I agree, but it means we need to change the error message, as currently casadm prints an information about non existing cache.

**Comment by mmichal10** [comment]
Team agree to change the error message to more meaningful

**Comment by pdebski21** [comment]
Issue was fixed with https://github.com/Open-CAS/open-cas-linux/pull/1274/files
