### ISSUE TITLE
CAS Cache and CAS Disk Kernel Modules not loaded after reboot.

### ISSUE THREAD

**Issue by KamilLepek** [Open-CAS/open-cas-linux#119]
Tested on clean CAS installation.
Kernel: 3.10.0-957.el7.x86_64
OS: CENTOS76

Outputs after reboot:

```casadm -L``` output:
```
Device /dev/cas_ctrl not found
Is the kernel module loaded?
Error getting caches list
```

```casadm -V``` output:

| Name        | Version           |
| ------------- |:-------------:|
| CAS Cache Kernel Module      | Not Loaded |
| CAS Disk Kernel Module      | Not Loaded      |
| CAS CLI Utility | 19.09.00.00000924      |

**Comment by robertbaldyga** [comment]
CENTOS7.6 by default has not installed `python3` package. Are you sure you have `python3` installed in your setup?

**Comment by KamilLepek** [comment]
Indeed, ```python3``` was the issue. That is why I suggest it should be required for installation. Closing this.
