### ISSUE TITLE
install fail 

### ISSUE THREAD

**Issue by vastchen** [Open-CAS/open-cas-linux#1217]
when ./configure
ERROR! Following steps failed while preparing config:
1_bd_part_count.conf
1_bdev_nr_sectors.conf
1_bdget_disk.conf
1_bdev_whole.conf
1_bd_first_part.conf
1_bio_dev.conf
1_bio_clone.conf
2_bio_barrier.conf

**Comment by mmichal10** [comment]
Hi @vastchen,

thank you for posting the issue. Could you provide some additional information? 
- OpenCAS version
- OS
- kernel version

**Comment by vastchen** [comment]
> Hi @vastchen,
> 
> thank you for posting the issue. Could you provide some additional information?
> 
>     * OpenCAS version
> 
>     * OS
> 
>     * kernel version

I use gentoo keernel 5.18 gentoo-sources OpenCAS version last and stable sam errors.   .I saw this for server like centos ubuntu. gentoo is many diffent .So i try bcache.

**Comment by mmichal10** [comment]
@vastchen @mikabytes 

We are currently working on the support for kernel 5.15. We are planning to finish it by the end of Q2
