### ISSUE TITLE
hung tasks after creating file system on cas1-1

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#1232]
## Description

test: SecIoEngines (MultiTester)
![image](https://user-images.githubusercontent.com/71020523/174278449-7655cbc9-7347-4526-a23f-853a3b426b6b.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* OpenCAS version (commit hash or tag): 22.6.0.0697
* Operating System: Centos7.9
* Kernel version: 5.15
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by mmichal10** [comment]
The issue didn't occur on kernel v4.18, however I reproduced it on kernel 4.19

**Comment by mmichal10** [comment]
Apparently, disabling wbt in `/sys/block/<disk_name>/queue` helps as well.
