### ISSUE TITLE
Metadata checksum is not correct. Metadata is damaged

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#1239]
## Description

test fail: SecLoadCorruptedMetadata

Loading cache
-
casadm --start-cache --cache-device /dev/disk/by-id/link-ram1 --load2022-06-22 12:44:01Passed

Error inserting cache 1
Metadata checksum is not correct. Metadata is damaged

## Steps to Reproduce
**ITERATION 11/31 - Tested configuration: WA | LINESIZE16KB | ALRU**

![image](https://user-images.githubusercontent.com/71020523/175100714-96a853f4-0ca3-414d-9592-135a26cf2587.png)
## Your Environment

* OpenCAS version (commit hash or tag): 22.06.0.0697
* Operating System: Centos 7.9
* Kernel version: 5.15.6
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by mmichal10** [comment]
I've tried to reproduce it by corrupting exactly the same addresses and each time CAS refused to load

**Comment by jfckm** [comment]
I've read into the logs and it seems that the test reports pass - CAS failed to load.
![obraz](https://user-images.githubusercontent.com/43981817/175301328-e4e301f3-4069-41a1-adc8-9e0a8e77afa3.png)
I think that this exception isn't from something happening on the DUT, but rather test controller ran out of space to store logs.

**Comment by soniapszczolinska** [comment]
It is test or environment issue
