### ISSUE TITLE
Reported metadata size is not quite accurate 

### ISSUE THREAD

**Issue by mmichal10** [Open-CAS/open-cas-linux#1241]
After starting a cache device on a ram disk of size 100MB CAS reported inconsistent metadata size and section offsets.

Consider `Hash` section offset from the attached log: `36352 kiB` whereas the whole `Metadata capacity` is equal to `18 MiB`

![image](https://user-images.githubusercontent.com/25607940/175245973-ad3de070-4732-4d5e-992b-a027584dc32b.png)

**Comment by kmajzero** [comment]
Fixed by Open-CAS/ocf#744
