### ISSUE TITLE
CAS/Cache read bandwidth is NOT within acceptable limits (for 4 number of jobs)

### ISSUE THREAD

**Issue by kajakoltan** [Open-CAS/open-cas-linux#1243]
## Description

test: Performance1 (MT)
problem:
**CAS/Cache read bandwidth for number of jobs = 4, queue depth = 8, block size = 4k is NOT within acceptable limits - 49.88%.**
This is problem only with **number of jobs =4**

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/71020523/175292919-ac9fa991-da04-4f73-9c59-abcaff57cf0c.png)
![image](https://user-images.githubusercontent.com/71020523/175293040-98827b5d-0e95-4b31-91c7-54496901acbe.png)

## Your Environment

* OpenCAS version (commit hash or tag): 22.06.0.0698
* Operating System: Centos 7.9
* Kernel version: 5.15.6
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by karolinavelkaja** [comment]
checking with newest CAS version: tests passed with 22.06.0.0701.master

**Comment by kmajzero** [comment]
This issue is due to the test's slightly non-dterministic behaviour. Rerun proved there is no performance problem.
