### ISSUE TITLE
RAM changes are higher than allowed RAM usage

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#1244]
## Description

test: CliMetadata2 (MT)
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/71020523/175311549-52c93d3b-6ac8-4c48-bc16-087ea88fcf89.png)

## Your Environment

* OpenCAS version (commit hash or tag): 22.6.0.0697
* Operating System: Centos 7.9
* Kernel version: 5.15.6
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by robertbaldyga** [comment]
This behavior has changed at least a year ago, as we observed similar fails in 21.6 and then 22.3 versions. We probably need to adjust our expected memory allocation size method.

**Comment by karolinavelkaja** [comment]
Test improved and during migration - under review: https://github.com/Open-CAS/open-cas-linux/pull/591
