### ISSUE TITLE
Missleading error message in script adding core to core pool

### ISSUE THREAD

**Issue by pdebski21** [Open-CAS/open-cas-linux#1261]
## Description
Executing script add-core with try-add flag without specyfied core-id error message point to not existing cache id

## Expected Behavior
Descriptive error message about missing parameter (core-id)

## Actual Behavior
```
# /sbin/casadm --script --add-core --core-device /dev/disk/by-id/nvme-nvme --cache-id 1 --try-add
Error while adding core device to cache instance 1
Cache ID does not exist
```

```
# /sbin/casadm --script --add-core --core-device /dev/disk/by-id/nvme-nvme --cache-id 1 --core-id 1 --try-add
Successfully added device in try add mode /dev/disk/by-id/nvme
```

**Comment by mmichal10** [comment]
Before closing this issue, make sure that there is a test which verifies whether this error message is correct (and if such test doesn't exist, please add one)

**Comment by pdebski21** [comment]
there are 2 tests which have to pass after fixing this issue `test_attach_core_pool `and `test_core_pool_exclusive_open`.
One more will be added `test_standby_activate_with_corepool`.
