### ISSUE TITLE
Cache Line Size has no effect on transfer unit size

### ISSUE THREAD

**Issue by patrickr92** [Open-CAS/open-cas-linux#1268]
## Description

The [cache configuration](https://open-cas.github.io/cache_configuration.html) documentation emphasizes that the _cache line size_ parameter controls the minimum unit of data on the backend device that can be mapped into the cache. 

## Expected Behavior

We understood this as the minimal amount of data to be transferred between cache and backend devices, e.g. with `--cache-line-size=64` we would expect that even for low-granularity reads (e.g. 4KiB) a whole cache line would be prefetched.

## Actual Behavior

We did not observe such a prefetching of larger blocks from the backend device, e.g. with 4KiB read I/Os and  `--cache-line-size=64` we could not identify any caching of neighboring blocks, but additional 4KiB I/Os on the backend device when targeting differeent blocks of already accessed cache lines.
 
## Steps to Reproduce

After each step, check the amount of backend/cache reads from the respective counters (`casadm -P -i 1`) and/or run blktrace or similar utility in parallel:

1. Create caching device (`-c=wt` or `-c=wa`, `-x=64`) and attach it to a backend device 
`casadm -S -i 1 -d /dev/<cache-dev> -c wt -x 64`
`casadm -A -i 1 -d /dev/<backend-dev>`

2. Read one 4KiB-block per cache line window in a strided fashion (theoretically, each cache line window should be cached afterwards):
`for i in {0..15}; do dd if=/dev/cas1-1 of=/dev/null bs=4K skip=$((256 + $i*16)) count=1 iflag=direct status=progress; done`
We observed 16 4KiB-blocks transferred from the backend here.

3. Read the complete range block-wise:
`dd if=/dev/cas1-1 of=/dev/null iflag=direct bs=4k count=256 skip=256 status=progress`
Although we expected all cache-lines being prefetched, we observed 240 backend reads and 16 cache reads (i.e., the blocks read in Step 2).

## Context

We were trying to use Open CAS for decreasing the number of individual I/O in a scenario where data is read in a small-granularity random-access fashion, but each individual block in the accessed range will be read exactly once and hence may be prefetched. 

## Possible Fix

We are not sure whether this is the intended behavior and we were just misled by documentation or this is an actual bug.

## Your Environment

* OpenCAS version (commit hash or tag): 22.06.0.0712.master
* Operating System: Centos 7.9.2009
* Kernel version: 5.4.172
* Cache device type (NAND/Optane/other): NAND
* Core device type (HDD/SSD/other): HDD
* Cache configuration:
* * Cache mode: wt, but also in wa
* * Cache line size: 64
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)

**Comment by mmichal10** [comment]
Hello @patrickr92 

Thank you for posting the issue. Cache line size is doesn't imply the size of an IO. The concept of cache line size was introduced to simplify management of cache blocks metadata as CAS needs to maintain some information per each disk block (vaild/invalid, clean/dirty, mapping). 

The lack of prefetch is, actually, part of our design and in some cases it would require an additional memory allocation but it possibe to implement. If you consider this feature useful, you can fill an[ Enhancement proposal](https://github.com/Open-CAS/ocf/issues/new/choose) in OCF github repo. That way the CAS team will investigate if it is worth implementing.

**Comment by patrickr92** [comment]
Hello @mmichal10,

thanks for the clarification. I already thought that prefetching is beyond the intended use. Misleading was for me the following statement in the [cache configuration](https://open-cas.github.io/cache_configuration.html) documentation: 
"It’s the minimum portion of data on the backend storage ([core line](https://open-cas.github.io/cache_line.html)) that can be mapped into the cache."

Concluding my experience and your explanation, cache line neither affects the minimum transfer unit, nor prevents smaller units from being cached (the individual 4K blocks read where still served from cache on further access); my final suggestion thus is  to either drop or enhance this specific sentence.  

Special thanks for openly sharing and maintaining CAS!
