### ISSUE TITLE
casadm hangs after kernel & opencas update

### ISSUE THREAD

**Issue by alxtrl** [Open-CAS/open-cas-linux#1278]
## Description
Hi,
I had four servers running Oracle8 4.18.0-348.2.1.el8_5.x86_64 and opencas 21.06.3.0551, I decided to try an upgrade of both the kernel and the opencas on one of them. After that I can't remove a core or stop the cache without casadm hanging:

[ 3810.542150] INFO: task casadm:301136 blocked for more than 120 seconds.
[ 3810.542782]       Tainted: G           OE    --------- -  - 4.18.0-372.13.1.0.1.el8_6.x86_64 #1
[ 3810.543429] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 3810.544076] task:casadm          state:D stack:    0 pid:301136 ppid:  2031 flags:0x00004080
[ 3810.544740] Call Trace:
[ 3810.545401]  __schedule+0x2d1/0x830
[ 3810.546073]  schedule+0x35/0xa0
[ 3810.546733]  blk_mq_freeze_queue_wait+0x46/0xb0
[ 3810.547423]  ? finish_wait+0x80/0x80
[ 3810.548097]  blk_cleanup_queue+0x38/0xd0
[ 3810.548772]  casdsk_exp_obj_destroy+0x3a/0xa0 [cas_disk]
[ 3810.549458]  block_dev_destroy_exported_object+0x44/0x80 [cas_cache]
[ 3810.550174]  cache_mngt_remove_core_from_cache+0x1bc/0x420 [cas_cache]
[ 3810.550894]  ? __vmalloc_node_range+0x1c0/0x230
[ 3810.551606]  cas_service_ioctl_ctrl+0x1823/0x29f0 [cas_cache]
[ 3810.552339]  ? update_load_avg+0x7e/0x700
[ 3810.553057]  ? enqueue_entity+0xf1/0x6e0
[ 3810.553778]  ? enqueue_task_fair+0x94/0x6d0
[ 3810.554500]  do_vfs_ioctl+0xa4/0x680
[ 3810.555224]  ? wake_up_new_task+0x1b9/0x270
[ 3810.555944]  ? syscall_trace_enter+0x1fb/0x2c0
[ 3810.556670]  ksys_ioctl+0x60/0x90
[ 3810.557412]  __x64_sys_ioctl+0x16/0x20
[ 3810.558137]  do_syscall_64+0x5b/0x1a0
[ 3810.558859]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[ 3810.559594] RIP: 0033:0x7ff57f8bb72b
[ 3810.560331] Code: Unable to access opcode bytes at RIP 0x7ff57f8bb701.
[ 3810.561073] RSP: 002b:00007ffe1a763bb8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[ 3810.561820] RAX: ffffffffffffffda RBX: 00007ffe1a763c10 RCX: 00007ff57f8bb72b
[ 3810.562580] RDX: 00007ffe1a763cf4 RSI: ffffffff800cba17 RDI: 0000000000000005
[ 3810.563329] RBP: 00007ffe1a763be0 R08: 0000000000000000 R09: 00007ff57f881700
[ 3810.564066] R10: 00007ff57f8819d0 R11: 0000000000000246 R12: 0000000000000000
[ 3810.564792] R13: 0000000000000005 R14: 00000000800cba17 R15: 00007ffe1a763cf4

I tried various version of opencas but the result is the same.
I even erased the nvme cache device using nvme format command but it didn't help.

Thanks for your support.
Alessandro

## Your Environment

* OpenCAS version (commit hash or tag): 
* Operating System: Oracle Linux 8.6
* Kernel version: 4.18.0-372.13.1.0.1.el8_6.x86_64 (just the last one I've tried)
* Cache device type (NAND/Optane/other): Optane DC P4800X SSDPED1K375GA E2010600
* Core device type (HDD/SSD/other): RAID array (/dev/sdx)
* Cache configuration: 
* * Cache mode: (default: wt) wa
* * Cache line size: (default: 4) 4
* * Promotion policy: (default: always) always
* * Cleaning policy: (default: alru) alru
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)
casadm -L
type    id   disk           status    write policy   device
cache   1    /dev/nvme0n1   Running   wa             -
├core   1    /dev/sdc1      Active    -              /dev/cas1-1
├core   2    /dev/sdd1      Active    -              /dev/cas1-2
├core   3    /dev/sde1      Active    -              /dev/cas1-3
└core   4    /dev/sdf1      Active    -              /dev/cas1-4

**Comment by robertbaldyga** [comment]
Hi @alxtrl. Thank you for reporting this problem. We did not test OpenCAS with Oracle Linux 8.6. We are on it.

**Comment by kmajzero** [comment]
Confirmed on RHEL 8.6, kernel 4.18.0-348.7.1.el8_5.x86_64 with same hung task error.
