### ISSUE TITLE
open-cas does not support Ubuntu 19.04 (kernel 5.0.0)

### ISSUE THREAD

**Issue by liangintel** [Open-CAS/open-cas-linux#128]
stack@ceph01liang: ~ / open-cas-linux$ sudo make install
cd modules && make install
make[1]: Entering directory '/opt/stack/open-cas-linux/modules'
Installing Open-CAS modules
modprobe: ERROR: could not insert 'cas_cache': Unknown symbol in module, or unknown parameter (see dmesg)
make[1]: *** [Makefile:58: install] Error 1
make[1]: Leaving directory '/opt/stack/open-cas-linux/modules'
make: *** [Makefile:15: modules] Error 2

stack@ceph01liang: ~ / open-cas-linux$ uname -r
5.0.0-29-generic

--------------------------------

stack@ceph01liang:~/open-cas-linux$ dmesg | grep cas_disk
[91506.368989] cas_disk: loading out-of-tree module taints kernel.
[91506.369108] cas_disk: module verification failed: signature and/or required key missing - tainting kernel

**Comment by micrakow** [comment]
What CAS version have You tried to install?
Open-CAS-Linux **19.6** does not support kernels 5+, but our next release (19.9) will. 
Alternatively You can try building & installing CAS from this commit: https://github.com/Open-CAS/open-cas-linux/commit/93ee2658275889e919995fae08d2e33752a6ef4c

Also this:
> module verification failed: signature and/or required key missing - tainting kernel

shows that Your running config may have disabled loading out-of-tree kernel modules which are not signed. Are there any more CAS-related logs in dmesg?

**Comment by liangintel** [comment]
I was following the page:
https://open-cas.github.io/getting_started_open_cas_linux.html

So I'm using latest code from master branch. I will try commit: 93ee265. 
BTW, when will 19.9 be released please?

some more logs:
----------
[Thu Sep 26 06:25:22 2019] cas_disk: loading out-of-tree module taints kernel.
[Thu Sep 26 06:25:22 2019] cas_disk: module verification failed: signature and/or required key missing - tainting kernel
[Thu Sep 26 06:25:22 2019] [CAS Disk] CAS Disk Version 19.09.00.00000926 (5.0.0-29-generic)::Module loaded successfully
[Thu Sep 26 06:25:22 2019] cas_cache: Unknown symbol blk_end_request_all (err -2)
[Thu Sep 26 06:29:26 2019] cas_cache: Unknown symbol blk_end_request_all (err -2)

**Comment by liangintel** [comment]
Just tested, commit: 93ee265 also does not work. Seems the same error.
