### ISSUE TITLE
open-cas does not support dedicated cache

### ISSUE THREAD

**Issue by liangintel** [Open-CAS/open-cas-linux#129]
In Openstack environment, dozens of VMs shares one single cache. Some VMs may occupy too much cache and other VMs does not. It is not fair for the tenant of the VMs.

It would be great if open-cas can allocate a fixed size cache for a specific VM, the cache belongs only to this VM, cannot be shared.

ps: A VM may contains one or more core device.

**Comment by mmichal10** [comment]
Hi @liangintel 

> It would be great if open-cas can allocate a fixed size cache for a specific VM

With OpenCAS v20.12 you can achieve it using io classification based on a process name or a process id combined with an occupancy per ioclass. The occupancy per ioclass allows you to specify a max cache size usage for a particular ioclass. 

With the following ioclass configuration you would limit maximum size of data cached for the process with pid 7890 to 20% of a caching device size. 

> IO class id,IO class name,Eviction priority,Allocation
> 0,unclassified,22,0.80
> 1,pid:eq:7890&done,9,0.20

You can read more about the io classification [here](https://open-cas.github.io/guide_io_classification.html)
