### ISSUE TITLE
Kernel warning during filesystem creation on exported device

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#133]
No reproduction so far

[  311.242921] ------------[ cut here ]------------
[  311.248403] WARNING: CPU: 17 PID: 43868 at mm/page_alloc.c:3189 __alloc_pages_slowpath+0x6f/0x724
[  311.258838] Modules linked in: cas_cache(OE) cas_disk(OE) brd xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack libcrc32c ipt_REJECT nf_reject_ipv4 tun bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter devlink loop rpcsec_gss_krb5 auth_rpcgss nfsv4 dns_resolver nfs lockd grace fscache sunrpc dm_mirror dm_region_hash dm_log dm_mod sb_edac intel_powerclamp coretemp intel_rapl iosf_mbi kvm_intel kvm irqbypass crc32_pclmul ghash_clmulni_intel aesni_intel lrw gf128mul iTCO_wdt glue_helper ablk_helper iTCO_vendor_support mei_me cryptd pcspkr sg joydev lpc_ich i2c_i801 mei ioatdma wmi ipmi_si ipmi_devintf ipmi_msghandler ip_tables ext4 mbcache jbd2 sd_mod crc_t10dif crct10dif_generic drm_kms_helper syscopyarea sysfillrect crct10dif_pclmul sysimgblt crct10dif_common fb_sys_fops ttm nvme crc32c_intel isci igb ahci drm libsas scsi_transport_sas libahci ptp nvme_core libata pps_core drm_panel_orientation_quirks dca i2c_algo_bit [last unloaded: cas_disk]
[  311.378189] CPU: 17 PID: 43868 Comm: mkfs.ext4 Kdump: loaded Tainted: G           OE  ------------   3.10.0-957.el7.x86_64 #1
[  311.391341] Hardware name: Intel Corporation S2600GZ ........../S2600GZ, BIOS SE5C600.86B.01.08.0003.022620131521 02/26/2013
[  311.404378] Call Trace:
[  311.407394]  [<ffffffffb5361dc1>] dump_stack+0x19/0x1b
[  311.413423]  [<ffffffffb4c97648>] __warn+0xd8/0x100
[  311.419164]  [<ffffffffb4c9778d>] warn_slowpath_null+0x1d/0x20
[  311.425977]  [<ffffffffb535cd87>] __alloc_pages_slowpath+0x6f/0x724
[  311.433289]  [<ffffffffb4dc0e95>] __alloc_pages_nodemask+0x405/0x420
[  311.440692]  [<ffffffffb4e0dcf8>] alloc_pages_current+0x98/0x110
[  311.447702]  [<ffffffffb4dbb5de>] __get_free_pages+0xe/0x40
[  311.454238]  [<ffffffffb4e1938e>] kmalloc_order_trace+0x2e/0xa0
[  311.461160]  [<ffffffffc0660e1e>] ? cas_rpool_try_get+0x5e/0x80 [cas_cache]
[  311.469242]  [<ffffffffb4e1d3d1>] __kmalloc+0x211/0x230
[  311.475374]  [<ffffffffc066837e>] ocf_req_alloc_map+0x3e/0x60 [cas_cache]
[  311.483251]  [<ffffffffc06683f7>] ocf_req_alloc_map_discard+0x57/0x60 [cas_cache]
[  311.492118]  [<ffffffffc067b6bd>] ocf_core_volume_submit_discard+0xdd/0x270 [cas_cache]
[  311.501563]  [<ffffffffc067b1bc>] ? ocf_core_io_allocator_new+0x1c/0x20 [cas_cache]
[  311.510619]  [<ffffffffc067aa78>] ? ocf_io_new+0x78/0xf0 [cas_cache]
[  311.518037]  [<ffffffffc068bb53>] ocf_volume_submit_discard+0x33/0x80 [cas_cache]
[  311.526925]  +0x1a/0x20 [cas_cache]
[  311.535186]  [<ffffffffc065cefc>] _blockdev_make_request_fast+0x23c/0x370 [cas_cache]
[  311.544445]  [<ffffffffb4f42eaf>] ? generic_make_request_checks+0x27f/0x390
[  311.552525]  [<ffffffffc04ffee3>] _casdsk_exp_obj_make_rq_fn+0xa3/0x1d0 [cas_disk]
[  311.561478]  [<ffffffffb4f44c87>] generic_make_request+0x147/0x380
[  311.568687]  [<ffffffffb4f44f30>] submit_bio+0x70/0x150
[  311.574828]  [<ffffffffb4e7e2e5>] ? bio_alloc_bioset+0x115/0x310
[  311.581849]  [<ffffffffb4f4d52a>] blkdev_issue_discard+0x1fa/0x2d0
[  311.589071]  [<ffffffffb4f56ac5>] blk_ioctl_discard+0xe5/0x130
[  311.595896]  [<ffffffffb4f57612>] blkdev_ioctl+0x632/0xa20
[  311.602313]  [<ffffffffb4e80761>] block_ioctl+0x41/0x50
[  311.608442]  [<ffffffffb4e56210>] do_vfs_ioctl+0x3a0/0x5a0
[  311.614860]  [<ffffffffb4e41148>] ? vfs_write+0x168/0x1f0
[  311.621179]  [<ffffffffb4e564b1>] SyS_ioctl+0xa1/0xc0
[  311.627121]  [<ffffffffb5374d15>] ? system_call_after_swapgs+0xa2/0x146
[  311.634802]  [<ffffffffb5374ddb>] system_call_fastpath+0x22/0x27
[  311.641809]  [<ffffffffb5374d21>] ? system_call_after_swapgs+0xae/0x146
[  311.649509] ---[ end trace 946d2bba3d539123 ]---

**Comment by arutk** [comment]
This warning is due to large kmalloc allocation in OCF discard handling. This will be fixed with future allocation optimizations in OCF and CAS Linux. For now it is not recommended to create file system on CAS exported object - this recommendation is documented in admin guide.

**Comment by arutk** [comment]
Fixed in https://github.com/Open-CAS/open-cas-linux/pull/329/commits/7153e8e8b6c25bf21663588e4ab1bd1153c5bae3.

@Deixx please verify
