### ISSUE TITLE
question: Opencas over mdadm raid

### ISSUE THREAD

**Issue by manwe** [Open-CAS/open-cas-linux#1378]
Hi

thank you for the great project. I've been checking caching solutions for my madadm raid6 that do not require formatting the existing filesystem. seems like opencas is the only one that can do that. Bcache, Bcachefs, dm-cache, zfs... all of them require to delete all the data  before. 

I've seen how one nvme can cache several hdds and also how to create a cached ceph system. But haven't seen if using a /dev/md* mdadm raid as core device is viable or if every single hdd should be cached first and create the mdadm over cas* devices.

Thank you.

**Comment by robertbaldyga** [comment]
Hi @manwe! Thank you for your kind words!
Using /dev/md* as core device will work fine. We have this configuration covered in our tests.
