### ISSUE TITLE
IO classes config load fail on kernel 5.18

### ISSUE THREAD

**Issue by Kgierszx** [Open-CAS/open-cas-linux#1403]
## Description

During load random IO class configuration for each cache, unexpected message appear "Unexpected classification rule condition".
Bug found on kernel 5.18.19-051819-generic.
Bug don`t appear on kernel 5.15.
## Expected Behavior

Config loaded successfully.
## Actual Behavior

During config load message "Unexpected classification rule condition" appear.
## Steps to Reproduce.

1.Prepare caches and cores.
2.Load IO class config.

## Your Environment

* OpenCAS version (commit hash or tag):
* Operating System: Ubuntu22.04
* Kernel version:5.18.19
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)
*

opencas_ioclass.conf:

IO class id,IO class name,Eviction priority,Allocation
0,unclassified,161,0.66
1,pid:le:916054&done,26,0.85
2,extension:f4Kg&done,208,0.82
3,directory:/1AZr,27,0.98
4,file_name_prefix:a6ldNY,35,0.63
5,process_name:C9xa0Seh,235,0.47
6,io_class:234,165,0.21
7,file_offset:ge:842948&done,248,0.50
8,file_offset:gt:480082,89,0.01
9,direct&done,141,0.27
10,pid:gt:395414&done,223,0.33
11,file_size:lt:962628,125,0.68
12,direct&done,152,0.60
13,wlth:eq:172446,26,0.75
14,file_size:le:542289,228,0.53
15,io_class:251,255,0.82
16,direct,230,0.27
17,file_size:gt:516456,2,0.81
18,io_class:188,162,0.50
19,metadata&done,50,0.74
20,extension:TCe3qbV&done,23,0.00
21,wlth:lt:173249,190,0.70
22,request_size:gt:876661,148,0.46
23,direct&done,6,0.05
24,directory:/fKq0d5PVaYAQ8Li,75,0.96
25,io_class:172,220,0.14
26,extension:iN7g,132,0.05
27,wlth:le:310732,121,0.35
28,file_name_prefix:d7RhhnE,37,0.12
29,file_offset:le:668241,255,0.03
30,file_size:eq:978313,72,0.44
31,file_name_prefix:3,147,0.04
32,directory:/TK1FzwOJj4G1oxvxmzMp4&done,119,0.53

**Comment by katlapinka** [comment]
When I removed all "wlth" rules - everything works fine. Otherwise it occurs on CentOS 9 with kernel 5.14.0-479.el9.x86_64

**Comment by robertbaldyga** [comment]
WLTH has been officially removed from kernel version 5.18, but some distribution kernels backported this change to earlier kernel version. Hence unavailability of `wlth` rule on recent distribution kernels is expected.

**Comment by katlapinka** [comment]
Expected behavior.
