### ISSUE TITLE
CAS fails to stop on kernel 5.18

### ISSUE THREAD

**Issue by Kgierszx** [Open-CAS/open-cas-linux#1409]
## Expected Behavior

CAS stop
## Actual Behavior

CAS fails to stop (Device busy warning occurs)
## Steps to Reproduce

1. Start cache and add core
2. Create and mount filesystem
3. Create test file and calculate md5 checksum
4. Add mountpoint fstab and create intelcas.conf
5. Reboot
6. Check if CAS started
7. CAS fails to stop

## Your Environment

* OpenCAS version (commit hash or tag):
* Operating System: Ubuntu 22.04
* Kernel version: 5.1819
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by kmajzero** [comment]
This can be observed on the test machines where Open CAS reports the device is still open. However, I cannot reproduce this on my local, clean Ubuntu 22.04LTS VM with 5.18.19 kernel (same config as the test machine).

**Comment by jfckm** [comment]
We need to check out refcount (with BPF maybe?)

**Comment by katlapinka** [comment]
No reproduction on current master branch (6c0829d5eae151f07f0b8a4825ae106980764c28)
