### ISSUE TITLE
Can't create deb packages

### ISSUE THREAD

**Issue by manwe** [Open-CAS/open-cas-linux#1412]
## Description
I'm running debian 11 with several packages from backports (such as kernel 5.19)
I cloned the git repository because the stable release doesn't support my kernel and seems like master does
git clone + git submodule update --init

When executing "make deb" I get 
dpkg-architecture: fallo: el tipo de sistema GNU unknown-linux-gnu es desconocido, también debe especificar la arquitectura de Debian
dpkg-buildpackage: fallo: dpkg-architecture subprocess returned exit status 25
debuild: fatal error at line 1182

If I try to execute the build script with amd64 as explicit architecture:
./tools/pckgen.sh . deb -a amd64
dwz: debian/open-cas-linux/sbin/casadm: .debug_info section not present
   debian/rules override_dh_strip
make[1]: se entra en el directorio '/tmp/opencas-pckgen.sh.HRGzoNedHw/debuild/open-cas-linux-22.06.0.0830.master'
dh_strip --no-ddebs
Can't exec "amd64-linux-gnu-strip": No existe el fichero o el directorio at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 524.
dh_strip: error: amd64-linux-gnu-strip --remove-section=.comment --remove-section=.note debian/open-cas-linux/sbin/casadm failed to execute: No child processes
dh_strip: error: amd64-linux-gnu-strip --remove-section=.comment --remove-section=.note debian/open-cas-linux/sbin/casadm returned exit code 2

## Your Environment

* OpenCAS version (commit hash or tag): f1161e04d7c60a00c307871f32c81da2e7425092
* Operating System: Debian 11 + backports
* Kernel version: 5.19.0-0.deb11.2-amd64
* debhelper                             13.9.1~bpo11+1         
* devscripts                            2.22.2~bpo11+1

**Comment by manwe** [comment]
Just for the record: this is the output of dpkg-architecture

root@NAS:/usr/src/open-cas-linux# dpkg-architecture 
DEB_BUILD_ARCH=amd64
DEB_BUILD_ARCH_ABI=base
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=amd64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=x86_64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=x86_64-linux-gnu
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
DEB_HOST_ARCH=amd64
DEB_HOST_ARCH_ABI=base
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=x86_64-linux-gnu
DEB_HOST_MULTIARCH=x86_64-linux-gnu
DEB_TARGET_ARCH=amd64
DEB_TARGET_ARCH_ABI=base
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=amd64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=x86_64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=x86_64-linux-gnu
DEB_TARGET_MULTIARCH=x86_64-linux-gnu

**Comment by manwe** [comment]
Bypassing the build tool works:

Link the debian folder to the upper dir
Manually modify changelog, control and rules files and change what the build tool "seds"
Build the debian way "dpkg-buildpackage -b"

So either there's a problem in my system with backported libs that the build tool doesn't understand or there's something wrong with the build tool.

**Comment by manwe** [comment]
Trying to build without generating debs, just with "make":

cd "/lib/modules/"5.19.0-0.deb11.2-amd64"/build" && make M=/usr/src/open-cas-linux/modules modules
make[2]: Entering directory '/usr/src/linux-headers-5.19.0-0.deb11.2-amd64'
  CC [M]  /usr/src/open-cas-linux/modules/cas_cache/service_ui_ioctl.o
In file included from /usr/src/open-cas-linux/modules/cas_cache/ocf_env.h:10,
                 from /usr/src/open-cas-linux/modules/include/ocf/ocf_logger.h:14,
                 from /usr/src/open-cas-linux/modules/include/ocf/ocf_ctx.h:15,
                 from /usr/src/open-cas-linux/modules/include/ocf/ocf_cache.h:16,
                 from /usr/src/open-cas-linux/modules/include/ocf/ocf.h:22,
                 from /usr/src/open-cas-linux/modules/cas_cache/cas_cache.h:9,
                 from /usr/src/open-cas-linux/modules/cas_cache/service_ui_ioctl.c:6:
/usr/src/open-cas-linux/modules/cas_cache/linux_kernel_version.h:44:10: fatal error: generated_defines.h: No such file or directory
   44 | #include "generated_defines.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by manwe** [comment]
It wanted x86_64 as arch and not amd64
So in the end it's only about the arch detection as "uname -i" is not portable and doesn't work in debian system AFAICS.

**Comment by rafalste** [comment]
Hi @manwe!
Thank you for filing this issue. We've probably never test this on pure Debian distribution, but rather on Ubuntu machines. It may be a matter of changing the architecture detection from `uname -i` to `uname -m`. Can you confirm that `uname -m` displays your architecture properly on your Debian distro?
If so, we will change that flag as it also works on all other systems that we test regularly.

Thanks in advance!
Rafal


P.S.: About the architecture naming confusion:
_pckgen.sh_ uses `--host-type` as an architecture specifier with the _debuild_ command (which later passes this value to _dpkg-buildpackage_). As taken from the dpkg-buildpackage manpage:
```
       -t, --host-type gnu-system-type
              Specify the GNU system type we build for (long option
              since dpkg 1.17.17).  It can be used in place of
              --host-arch or as a complement to override the default GNU
              system type of the host Debian architecture.
```
indicates that in the end the system type passed to the --host-type should be in your case `DEB_BUILD_GNU_TYPE=x86_64-linux-gnu`. And since the pckgen.sh simplifies this by taking only the arch specific part, you should use _x86_64_ as your architecture and not _amd64_:
`./tools/pckgen.sh . deb -a x86_64`

**Comment by manwe** [comment]
Hi.
I can confirm uname -m works in debian systems
