### ISSUE TITLE
Kernel exception with version greater than 4.18.0-405

### ISSUE THREAD

**Issue by nypca0** [Open-CAS/open-cas-linux#1419]
## Description
support kerne version greater than 4.18.0-348

## Reason
support New OS Version(RedHat/Centos)

## Your Environment
* OpenCAS version (commit hash or tag): v22.6.1
* Operating System: RedHat
* Kernel version: 4.18.0-425

**Comment by nypca0** [comment]
<img width="849" alt="企业微信截图_f2d6b002-6682-459b-ba0a-9199399f7a3b" src="https://user-images.githubusercontent.com/97942564/206829925-a300e106-7ebf-47b8-b4c9-78dd85e1d8ca.png">

**Comment by manwe** [comment]
AFAIK that's supported in master branch. I guess it will be supported in next release.

**Comment by mmichal10** [comment]
Hello @nypca0,

thank you for posting the issue. It will be fixed on master branch as soon as https://github.com/Open-CAS/open-cas-linux/pull/1425 gets merged
