### ISSUE TITLE
1_write_flag.conf configure failed with debian9 kernel 4.9.0-19-amd64

### ISSUE THREAD

**Issue by zyb521** [Open-CAS/open-cas-linux#1434]
## Description
opencas configure 1_write_flag.conf failed with debian9

os: Debian GNU/Linux 9.13 (stretch)
kernel: “Linux debian9 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64 GNU/Linux”

## Expected Behavior
configure ok

## Actual Behavior
configure error

## Steps to Reproduce
./configure
Preparing configuration
ERROR! Following steps failed while preparing config:
1_write_flag.conf

## Logs
build log: 
[1_write_flag.conf.log](https://github.com/Open-CAS/open-cas-linux/files/10341207/1_write_flag.conf.log)

WRITE or REQ_WRITE not compat with kernel 4.9?

**Comment by mmichal10** [comment]
Hello @zyb521, 

thank you for posting the issue. There is a pull request that fixes your problem; it should be merged soon
