### ISSUE TITLE
Which version can I install  with kernel: 5.10.0

### ISSUE THREAD

**Issue by alexfang609** [Open-CAS/open-cas-linux#1448]
hi, centos 7.6 7.6.1810  and  centos 7.4.1708 ，with kernel: 5.10.0，Which version do you recommend to install?

**Comment by mmichal10** [comment]
Hello @alexfang609,

We recommend using the latest version which currently is [v22.6.2](https://github.com/Open-CAS/open-cas-linux/releases/tag/v22.6.2)

**Comment by alexfang609** [comment]
thanks~
