### ISSUE TITLE
errors for ./configure

### ISSUE THREAD

**Issue by XueqiangDong** [Open-CAS/open-cas-linux#1449]
## Description

After upgrade to debian12,
When I try to run ./configure I get the errors:
Preparing configuration
ERROR! Following steps failed while preparing config:
1_bdev_nr_sectors.conf
1_bd_part_count.conf
1_bdev_whole.conf
1_bd_first_part.conf
1_bio_dev.conf
1_bio_clone.conf
2_bio_barrier.conf

I have no issue in using in debian11
## Steps to Reproduce

1. download and unzip, cd to ./open-cas-linux-22.06.2.0723.release
2. ./configure
3.
4.

## Your Environment

* OpenCAS version (commit hash or tag): 22.06.2.0723.release
* Operating System: debian12 bookworm
* Kernel version: 6.1.0-9-amd64
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by robertbaldyga** [comment]
This kernel version is not supported by v22.06. Kernels up to 6.8 will be supported in the next major release (v24.09) that is planned for September. It is actually already merged in the current master branch (unstable), so if you are welcome to try it.
