### ISSUE TITLE
Kernel modules don't load

### ISSUE THREAD

**Issue by alozzy** [Open-CAS/open-cas-linux#150]
After following the admin guide installation instructions exactly, I'm finding that the kernel modules are not loading on reboot.

**Comment by imjfckm** [comment]
Hi! Thanks for the report!

Could you provide some additional details? What's exactly the scenario, just installing CAS and then rebooting? Also, what's the OS?

**Comment by imjfckm** [comment]
What's the distro and version of your Linux? Do you have python3 installed?

**Comment by alozzy** [comment]
Hi Jan,

I'm running Mint Linux 19.2 with Cinnamon desktop, not sure if Python3 is installed - is that installed by default?

Thanks,

Alan

**Comment by robertbaldyga** [comment]
Hi Alan,

You can check this using command `apt -qq list python3`. It should return package version followed by `[installed]` mark. If it doesn't, then you need to install it using `sudo apt install python3`.

**Comment by alozzy** [comment]
Hi Robert,

Thanks for your suggestion; however, I've given up on Open CAS as it seems that nobody else is using it (Google searches to find info, reviews, etc are non existent), Intel no longer supports it, and LVM caching is "good enough" for my needs...

**Comment by robertbaldyga** [comment]
Hi Alan,

Intel supports Open CAS and it's currently actively developed. Latest version v19.9 has been released just few weeks ago. It's used primarily on server platforms in data centers and many big companies use it. It's established, enterprise quality software. However it's not (yet) popular on the internet as for many years it has been developed as closed source software, and it became open source only recently. I hope my response clears things up.
