### ISSUE TITLE
In OpenCAS's WA mode, the SSD read-only cache cannot automatically clear its cached data after it becomes full.

### ISSUE THREAD

**Issue by chang-rong-chen** [Open-CAS/open-cas-linux#1570]
In OpenCAS's WA mode, the SSD read-only cache cannot automatically clear its cached data after it becomes full.
"How can this be resolved? Who can help me? I can only use WA mode, but the SSD read-only cache does not automatically clear when it becomes full."

**Comment by chang-rong-chen** [comment]
"Attached is the cache information."
Cache Id                  1
Cache Size                483292630 [4KiB Blocks] / 1843.62 [GiB]
Cache Device              /dev/nvme0n1
Exported Object           -
Core Devices              3
Inactive Core Devices     0
Write Policy              wa
Cleaning Policy           alru
Promotion Policy          always
Cache line size           4 [KiB]
Metadata Memory Footprint 21.2 [GiB]
Dirty for                 0 [s] / Cache clean
Status                    Running

╔══════════════════╤═══════════╤═══════╤═════════════╗
║ Usage statistics │   Count   │   %   │   Units     ║
╠══════════════════╪═══════════╪═══════╪═════════════╣
║ Occupancy        │ 483292630 │ 100.0 │ 4KiB Blocks ║
║ Free             │         0 │   0.0 │ 4KiB Blocks ║
║ Clean            │ 483292630 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │         0 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧═══════════╧═══════╧═════════════╝

╔══════════════════════╤══════════╤═══════╤══════════╗
║ Request statistics   │  Count   │   %   │ Units    ║
╠══════════════════════╪══════════╪═══════╪══════════╣
║ Read hits            │ 10231480 │  48.9 │ Requests ║
║ Read partial misses  │   115138 │   0.5 │ Requests ║
║ Read full misses     │  2680890 │  12.8 │ Requests ║
║ Read total           │ 13027508 │  62.2 │ Requests ║
╟──────────────────────┼──────────┼───────┼──────────╢
║ Write hits           │  1592439 │   7.6 │ Requests ║
║ Write partial misses │        0 │   0.0 │ Requests ║
║ Write full misses    │     7008 │   0.0 │ Requests ║
║ Write total          │  1599447 │   7.6 │ Requests ║
╟──────────────────────┼──────────┼───────┼──────────╢
║ Pass-Through reads   │  2200223 │  10.5 │ Requests ║
║ Pass-Through writes  │  4108110 │  19.6 │ Requests ║
║ Serviced requests    │ 14626955 │  69.9 │ Requests ║
╟──────────────────────┼──────────┼───────┼──────────╢
║ Total requests       │ 20935288 │ 100.0 │ Requests ║
╚══════════════════════╧══════════╧═══════╧══════════╝

╔══════════════════════════════════╤════════════╤═══════╤═════════════╗
║ Block statistics                 │   Count    │   %   │   Units     ║
╠══════════════════════════════════╪════════════╪═══════╪═════════════╣
║ Reads from core(s)               │ 1471465520 │  85.0 │ 4KiB Blocks ║
║ Writes to core(s)                │  258871441 │  15.0 │ 4KiB Blocks ║
║ Total to/from core(s)            │ 1730336961 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼────────────┼───────┼─────────────╢
║ Reads from cache                 │  250147007 │  33.9 │ 4KiB Blocks ║
║ Writes to cache                  │  487800319 │  66.1 │ 4KiB Blocks ║
║ Total to/from cache              │  737947326 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼────────────┼───────┼─────────────╢
║ Reads from exported object(s)    │ 1721612527 │  86.9 │ 4KiB Blocks ║
║ Writes to exported object(s)     │  258871441 │  13.1 │ 4KiB Blocks ║
║ Total to/from exported object(s) │ 1980483968 │ 100.0 │ 4KiB Blocks ║
╚══════════════════════════════════╧════════════╧═══════╧═════════════╝

╔════════════════════╤═══════╤═════╤══════════╗
║ Error statistics   │ Count │  %  │ Units    ║
╠════════════════════╪═══════╪═════╪══════════╣
║ Cache read errors  │     0 │ 0.0 │ Requests ║
║ Cache write errors │     0 │ 0.0 │ Requests ║
║ Cache total errors │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Core read errors   │     0 │ 0.0 │ Requests ║
║ Core write errors  │     0 │ 0.0 │ Requests ║
║ Core total errors  │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Total errors       │     0 │ 0.0 │ Requests ║
╚════════════════════╧═══════╧═════╧══════════╝

**Comment by chang-rong-chen** [comment]
"Through several checks using casadm -P -i 1, it seems that when the SSD cache in WA mode is full, some data is automatically cleaned from the Free space, but it's very minimal. How can this be resolved? Is it possible to set parameters, such as cleaning data that hasn't been accessed for a certain number of days?"
1.
══════════════════╤═══════════╤═══════╤═════════════╗
║ Usage statistics │   Count   │   %   │   Units     ║
╠══════════════════╪═══════════╪═══════╪═════════════╣
║ Occupancy        │ 483292613 │ 100.0 │ 4KiB Blocks ║
║ Free             │        17 │   0.0 │ 4KiB Blocks ║
║ Clean            │ 483292613 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │         0 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧═══════════╧═══════╧═════════════╝
2.
╔══════════════════╤═══════════╤═══════╤═════════════╗
║ Usage statistics │   Count   │   %   │   Units     ║
╠══════════════════╪═══════════╪═══════╪═════════════╣
║ Occupancy        │ 483292630 │ 100.0 │ 4KiB Blocks ║
║ Free             │         0 │   0.0 │ 4KiB Blocks ║
║ Clean            │ 483292630 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │         0 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧═══════════╧═══════╧═════════════╝
3.
╔══════════════════╤═══════════╤═══════╤═════════════╗
║ Usage statistics │   Count   │   %   │   Units     ║
╠══════════════════╪═══════════╪═══════╪═════════════╣
║ Occupancy        │ 483292499 │ 100.0 │ 4KiB Blocks ║
║ Free             │       131 │   0.0 │ 4KiB Blocks ║
║ Clean            │ 483292499 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │         0 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧═══════════╧═══════╧═════════════╝

**Comment by robertbaldyga** [comment]
Hi @chang-rong-chen! The statistics look completely fine. Cache occupancy of 100% is expected (and desired) as this data residing on the cache generates cache hits, and more cache hits = better performance. So in most cases it doesn't make sense to decrease the occupancy.

There is also nothing to be cleaned, as statistics show the cache is already 100% clean. In fact, WA mode does not generate dirty data, so, you should never need cleaning.

I hope my answer makes it a bit clearer for you.

**Comment by chang-rong-chen** [comment]
@ robertbaldyga
"Sorry, you might have misunderstood me. It's true that it's not a problem when the cache is full. However, since I have a large amount of data on the hard drive (HD), when the cache is full, will the new data read from the HD no longer be written to the cache? But from what I see in the 'Free' section, there are still small amounts of space being freed up, although not much, as shown in the data I shared above. So I want to know if this is normal."

**Comment by chang-rong-chen** [comment]
"I ran a copy test using a 10GB file. From my test results, using iostat, when the cache is not full, the 10GB data read from the HD by the client is written to the cache, and next time it can be hit from the cache. When the cache is full, I created a new 10GB file on the HD, and when the user copies this file, it is not written to the cache. This is likely because the cache is full. I see that the cache periodically frees up some space, but it doesn’t seem to be much. So I’m curious about how this mechanism determines and handles cache cleaning."

**Comment by Deixx** [comment]
Hi @chang-rong-chen,

In general for Write-Around mode when the cache is full and non-cached data is read then the "coldest" cached data are evicted from cache to make space for the new data. However this is affected by several factors.

One of such factors is sequential cutoff. Caching data might not be desirable when sequential IOs are detected. Default policy triggers this behaviour when cache is full. Some data is still evicted as the sequential cutoff has a configurable threshold (default 1MiB) and new data is cached until the threshold is reached.
You can check your sequential cutoff settings by calling:
```casadm --get-param --name seq-cutoff --cache-id <CACHE_ID> --core-id <CORE_ID>```
If you want sequential data to be cached regardless of the occupancy then you can change the policy to `never` for all cores or for a specific core.
```casadm --set-param --name seq-cutoff --policy never --cache-id <CACHE_ID> [--core-id <CORE_ID>]```

Another factor could be the file system - different file systems handle copying files in different ways. What file system are you using?
