### ISSUE TITLE
Can open-cas be used with iscsi target backend

### ISSUE THREAD

**Issue by boxerab** [Open-CAS/open-cas-linux#1585]
Hello, 
I have been hunting for a good disk cache on linux for an iscsi initiator. I tried bcache, dm-cache.
Nothing is suitable so far.  Can an iscsi initiator use open-cas as a fast cache for read-only work flow ?
I want an aggressive cache policy - every cache miss is cached on disk.

Many Thanks,
Aaron

**Comment by robertbaldyga** [comment]
Hi @boxerab! Yes, Open CAS works with any block device. I don't see it very often as a cache on top of iscsi initiator so I don't have much experience with that specific scenario, but it should work just fine. If you can describe your use case I can help with selecting the right cache parameters.

**Comment by robertbaldyga** [comment]
Sounds like a very exotic configuration. I'm not sure if anyone tried to run Open CAS on WSL before. If you are doing only reads then WA or WT are equally good. You may want to turn off sequential cutoff if you want every single read to be cached.

Let me know if that worked.
