### ISSUE TITLE
OpenCAS  causes system crash and database bad block

### ISSUE THREAD

**Issue by ycs0220** [Open-CAS/open-cas-linux#161]
### Description
- The compute node Fio pressures the storage node to output the Crash through the NVMe over Fabrics protocol.
### Environment
- OS Version: RedHat-7.5（3.10.0-862.el7.x86_64）
- CAS Version: OpenCAS-19.6
- `CAS Configuration:` WB/acp/cache_line_size=8/seq-cutoff=never
### Fio Configuration
```shell
[global]
ioengine=libaio
iodepth=16
size=200G
direct=1
runtime=300
time_based
filename=/dev/cas2-1
filename=/dev/cas1-1
filename=/dev/cas3-1
filename=/dev/cas4-1

numjobs=4
group_reporting=1

#[seq-read]
#rw=read
#bs=1M

#[rand-read]
#rw=randread
#bs=8k

[seq-write]
rw=write
bs=1M

#[rand-write]
#rw=randwrite
#bs=8k
```
### Screenshot
![image](https://user-images.githubusercontent.com/34889631/67255138-29da3380-f4b3-11e9-9381-d4aa38b0263f.png)

---
Issue 2
### Description
- The storage node outputs the CAS disk to the compute node through the NVMe over Fabrics protocol. The CAS disk is used as the data disk of the Oracle database, and the database is restarted to cause bad blocks in the database.
### Configuration
- same as Issue 1
### Screenshot
![image](https://user-images.githubusercontent.com/34889631/67255522-06b08380-f4b5-11e9-8986-235eea3dca90.png)

**Comment by mmichal10** [comment]
Thanks for the report. Could you please provide us some additional information?
What is the size of disks used as caching devices? 
Does this crash occurred immediately after running fio? 
Could you share full log from system crash?
