### ISSUE TITLE
Kernel WARNING during IO

### ISSUE THREAD

**Issue by mariuszbarczak** [Open-CAS/open-cas-linux#244]
OS: Fedora 31
Commit: 9c7b485cef843f9bb8b640cb21586b817762650f
LOG:
Invalid sequential cutoff policy!
Dec 18 07:44:38 localhost.localdomain kernel: WARNING: CPU: 3 PID: 2699 at /root/open-cas-linux/modules/cas_cache/src/ocf/engine/cache_engine.c:194 ocf_seq_cutoff_check+0x35/0x70 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel: Modules linked in: cas_cache(OE) cas_disk(OE) xt_CHECKSUM xt_MASQUERADE tun bridge stp llc nf_conntrack_netbios_ns nf_conntrack_broadcast xt_CT ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ip6table_nat ip6table_mangle ip6table_raw ip6table_security iptable_nat nf_nat iptable_mangle iptable_raw iptable_security nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip_set nfnetlink ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter ip_tables sunrpc snd_intel8x0 snd_ac97_codec ac97_bus snd_seq snd_seq_device snd_pcm sb_edac snd_timer snd crct10dif_pclmul crc32_pclmul soundcore ghash_clmulni_intel joydev i2c_piix4 vboxguest intel_rapl_perf vmwgfx drm_kms_helper crc32c_intel ttm drm e1000 serio_raw ata_generic pata_acpi video [last unloaded: cas_disk]
Dec 18 07:44:38 localhost.localdomain kernel: CPU: 3 PID: 2699 Comm: systemd-udevd Tainted: G        W  OE     5.2.16-200.fc30.x86_64 #1
Dec 18 07:44:38 localhost.localdomain kernel: Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
Dec 18 07:44:38 localhost.localdomain kernel: RIP: 0010:ocf_seq_cutoff_check+0x35/0x70 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel: Code: 55 49 89 cd 41 54 49 89 d4 55 48 89 fd 53 89 f3 e8 b0 75 00 00 85 c0 74 1f 83 f8 02 74 0e 48 c7 c7 f8 cc 97 c0 e8 9a bb 78 db <0f> 0b 5b 44 89 f0 5d 41 5c 41 5d 41 5e c3 39 9d f0 00 00 00 75 ec
Dec 18 07:44:38 localhost.localdomain kernel: RSP: 0018:ffffb36549f4b868 EFLAGS: 00010286
Dec 18 07:44:38 localhost.localdomain kernel: RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
Dec 18 07:44:38 localhost.localdomain kernel: RDX: 0000000000000001 RSI: ffffffff9dbd9641 RDI: 0000000000000246
Dec 18 07:44:38 localhost.localdomain kernel: RBP: ffffb3654a1c9c50 R08: 000002620e5cf242 R09: 0000000000000021
Dec 18 07:44:38 localhost.localdomain kernel: R10: ffffb36549f4b6b8 R11: ffffb36549f4b6bd R12: 0000004fffff9000
Dec 18 07:44:38 localhost.localdomain kernel: R13: 0000000000005000 R14: 0000000000000000 R15: 0000000000000040
Dec 18 07:44:38 localhost.localdomain kernel: FS:  00007fe68beb8940(0000) GS:ffff8fc40f780000(0000) knlGS:0000000000000000
Dec 18 07:44:38 localhost.localdomain kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Dec 18 07:44:38 localhost.localdomain kernel: CR2: 00005576758ec000 CR3: 00000003fc024001 CR4: 00000000000606e0
Dec 18 07:44:38 localhost.localdomain kernel: Call Trace:
Dec 18 07:44:38 localhost.localdomain kernel:  ? ocf_get_effective_cache_mode+0x81/0xd0 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel:  ? ocf_core_submit_io_mode+0x453/0x490 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel:  ? cas_rpool_try_get+0x94/0xa0 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel:  ? env_allocator_new+0x49/0xa0 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel:  ? _block_dev_queue_request+0x836/0xad0 [cas_cache]
Dec 18 07:44:38 localhost.localdomain kernel:  ? wbt_track+0x21/0x30
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_add_rq_to_plug+0x27/0x70
Dec 18 07:44:38 localhost.localdomain kernel:  ? _casdsk_exp_obj_queue_rq+0x59/0x90 [cas_disk]
Dec 18 07:44:38 localhost.localdomain kernel:  ? __blk_mq_try_issue_directly+0x121/0x1c0
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_mq_request_issue_directly+0x48/0xe0
Dec 18 07:44:38 localhost.localdomain kernel:  ? generic_make_request+0xcf/0x320
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_mq_try_issue_list_directly+0x51/0xc0
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_mq_sched_insert_requests+0xa7/0xf0
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_mq_flush_plug_list+0x214/0x2b0
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_flush_plug_list+0xec/0x110
Dec 18 07:44:38 localhost.localdomain kernel:  ? blk_finish_plug+0x21/0x2e
Dec 18 07:44:38 localhost.localdomain kernel:  ? read_pages+0x80/0x1b0
Dec 18 07:44:38 localhost.localdomain kernel:  ? 0xffffffff9c000000
Dec 18 07:44:38 localhost.localdomain kernel:  ? __do_page_cache_readahead+0x168/0x1d0
Dec 18 07:44:38 localhost.localdomain kernel:  ? force_page_cache_readahead+0x93/0x100
Dec 18 07:44:38 localhost.localdomain kernel:  ? generic_file_read_iter+0x85d/0xe60
Dec 18 07:44:38 localhost.localdomain kernel:  ? file_fdatawait_range+0x20/0x20
Dec 18 07:44:38 localhost.localdomain kernel:  ? new_sync_read+0x12a/0x1c0
Dec 18 07:44:38 localhost.localdomain kernel:  ? vfs_read+0x9d/0x150
Dec 18 07:44:38 localhost.localdomain kernel:  ? ksys_read+0x5f/0xe0
Dec 18 07:44:38 localhost.localdomain kernel:  ? do_syscall_64+0x5f/0x1a0
Dec 18 07:44:38 localhost.localdomain kernel:  ? page_fault+0x8/0x30
Dec 18 07:44:38 localhost.localdomain kernel:  ? entry_SYSCALL_64_after_hwframe+0x44/0xa9
Dec 18 07:44:38 localhost.localdomain kernel: ---[ end trace 0fb21fbcffa4e526 ]---

**Comment by micrakow** [comment]
Please retest on current master. I believe that this: https://github.com/Open-CAS/ocf/commit/57e6b967912e8c1dbe2014d7247c5d881220d774 fixes this issue (current Open-CAS-linux master should contain this OCF with this commit).

**Comment by mariuszbarczak** [comment]
It does. Issue closed.
