### ISSUE TITLE
Kernel oops while unloading kernel module after unsuccessful cache start

### ISSUE THREAD

**Issue by katlapinka** [Open-CAS/open-cas-linux#338]
**Steps to reproduce:**
1. modprobe cas_cache metadata_layout=1 unaligned_io=0 use_io_scheduler=0
2. casadm --start-cache --cache-device <dev_id> --cache-mode wb --cache-line-size 64
(Starting cache failed due to existing previous cache's metadata on cache device)
Dmesg after unsuccessful cache start:
_[  248.269482] cache1: Attaching cache device failed
[  248.274921] Thread cas_io_cache1_25 stopped
[  248.274932] Thread cas_io_cache1_19 stopped
[  248.274938] Thread cas_io_cache1_16 stopped
[  248.274950] Thread cas_io_cache1_9 stopped
[  248.274956] Thread cas_io_cache1_14 stopped
[  248.274958] Thread cas_io_cache1_30 stopped
[  248.274961] Thread cas_io_cache1_15 stopped
[  248.274963] Thread cas_io_cache1_31 stopped
[  248.274965] Thread cas_io_cache1_0 stopped
[  248.274965] Thread cas_io_cache1_3 stopped
[  248.274979] Thread cas_io_cache1_24 stopped
[  248.274981] Thread cas_io_cache1_8 stopped
[  248.274995] Thread cas_io_cache1_26 stopped
[  248.274996] Thread cas_io_cache1_10 stopped
[  248.274997] Thread cas_io_cache1_11 stopped
[  248.274998] Thread cas_io_cache1_27 stopped
[  248.274999] Thread cas_io_cache1_12 stopped
[  248.275000] Thread cas_io_cache1_28 stopped
[  248.275001] Thread cas_io_cache1_29 stopped
[  248.275002] Thread cas_io_cache1_13 stopped
[  248.275003] cache1: Cache cache1 successfully stopped
[  248.275008] [Open-CAS] [Classifier] Deinitialized IO classifier
[  248.275010] Thread cas_io_cache1_1 stopped
[  248.275010] Thread cas_io_cache1_17 stopped
[  248.275012] Thread cas_io_cache1_18 stopped
[  248.275013] Thread cas_io_cache1_2 stopped
[  248.275014] Thread cas_io_cache1_4 stopped
[  248.275015] Thread cas_io_cache1_20 stopped
[  248.275016] Thread cas_io_cache1_21 stopped
[  248.275017] Thread cas_io_cache1_5 stopped
[  248.275018] Thread cas_io_cache1_22 stopped
[  248.275019] Thread cas_io_cache1_6 stopped
[  248.275020] Thread cas_io_cache1_23 stopped
[  248.275021] Thread cas_io_cache1_7 stopped
[  248.386529] ata2.00: Enabling discard_zeroes_data_

3. modprobe -r cas_cache

Kernel oops detested on serial console:
[  277.459743] BUG: unable to handle kernel paging request at ffffffffc05ba0c2
[  277.467699] PGD 64220c067 P4D 64220c067 PUD 64220e067 PMD 827fac067 PTE 0
[  277.475441] Oops: 0010 [#1] SMP PTI
[  277.479486] CPU: 3 PID: 23121 Comm: cas_io_cache1_- Tainted: G           O      4.19.56-t2.el7.twitter.x86_64 #1
[  277.491109] Hardware name: Intel Corporation S2600GZ ........../S2600GZ, BIOS SE5C600.86B.01.08.0003.022620131521 02/26/2013
[  277.503885] RIP: 0010:0xffffffffc05ba0c2
[  277.508415] Code: Bad RIP value.
[  277.512165] RSP: 0018:ffffbdc284c7fec0 EFLAGS: 00010202
[  277.518152] RAX: 0000000000000001 RBX: ffff9b19d2aa6120 RCX: 0000000000000000
[  277.526283] RDX: 0000000000000002 RSI: 0000000000000000 RDI: ffff9b19d2aa6120
[  277.534415] RBP: 0000000000000000 R08: ffff9b15ef8e2038 R09: 00000000000002a3
[  277.542546] R10: ffffbdc28397bda8 R11: fefefefefefefeff R12: ffff9b12c599f8c0
[  277.550688] R13: ffff9b12c599f910 R14: ffff9b12c599f8c8 R15: ffffffffc05ba000
[  277.558823] FS:  0000000000000000(0000) GS:ffff9b15ef8c0000(0000) knlGS:0000000000000000
[  277.568094] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  277.574665] CR2: ffffffffc05ba098 CR3: 000000064220a005 CR4: 00000000000606e0
[  277.582786] Call Trace:
[  277.585677]  ? finish_wait+0x80/0x80
[  277.589820]  ? kthread+0x113/0x130
[  277.593779]  ? kthread_create_worker_on_cpu+0x50/0x50
[  277.599577]  ? ret_from_fork+0x35/0x40
[  277.603912] Modules linked in: xfs nls_utf8 xt_CHECKSUM iptable_mangle ipt_MASQUERADE iptable_nat nf_nat_ipv4 nf_nat xt_conntrack nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c tun bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables devlink bpfilter rpcsec_gss_krb5 auth_rpcgss oid_registry nfsv4 nfs lockd grace fscache sunrpc intel_rapl iosf_mbi sb_edac x86_pkg_temp_thermal intel_powerclamp coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel kvm_intel iTCO_wdt iTCO_vendor_support mpt3sas ipmi_si ipmi_devintf ipmi_msghandler ioatdma raid_class i2c_i801 lpc_ich wmi pcc_cpufreq igb isci ptp crc32c_intel libsas pps_core scsi_transport_sas i2c_algo_bit nvme i2c_core nvme_core dca [last unloaded: cas_disk]
[  277.676855] CR2: ffffffffc05ba0c2
[  277.680705] ---[ end trace 843c9a3cb25b1d23 ]---
[  277.710148] RIP: 0010:0xffffffffc05ba0c2
[  277.714701] Code: Bad RIP value.
[  277.718472] RSP: 0018:ffffbdc284c7fec0 EFLAGS: 00010202
[  277.724466] RAX: 0000000000000001 RBX: ffff9b19d2aa6120 RCX: 0000000000000000
[  277.732602] RDX: 0000000000000002 RSI: 0000000000000000 RDI: ffff9b19d2aa6120
[  277.740732] RBP: 0000000000000000 R08: ffff9b15ef8e2038 R09: 00000000000002a3
[  277.748860] R10: ffffbdc28397bda8 R11: fefefefefefefeff R12: ffff9b12c599f8c0
[  277.756987] R13: ffff9b12c599f910 R14: ffff9b12c599f8c8 R15: ffffffffc05ba000
[  277.765113] FS:  0000000000000000(0000) GS:ffff9b15ef8c0000(0000) knlGS:0000000000000000
[  277.774387] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  277.780960] CR2: ffffffffc05ba098 CR3: 000000064220a005 CR4: 00000000000606e0
[  278.886770] [CAS Disk] CAS Disk Version 20.01.00.00000220 (4.19.56-t2.el7.twitter.x86_64)::Module loaded successfully
[  279.196346] 'OCF Core' volume operations registered
[  279.245800] 'Block_Device' volume operations registered
[  279.251820] [Open-CAS] Not found configuration for upgrade. Standard module initialization.
[  279.261495] Open Cache Acceleration Software Linux Version 20.01.00.00000220_

**Comment by arutk** [comment]
Logs indicate that after failed cache start (due to metadata mismatch) management queue was not shut down properly (as the crash occurs in management queue's thread). So the root cause is probably invalid error handling in cache attach.
