### ISSUE TITLE
seq-cutoff: 4K seq read performance is much worse than core device's when all the read requests are 100% cache hit and cache device is 80% dirty

### ISSUE THREAD

**Issue by eriksun421** [Open-CAS/open-cas-linux#345]
**Test Config:**
- OS: RHEL7.5
- CAS: v20.01 release
- Cache: NVMe/5GB
- Core:  HDD/50GB
- Write back 
- nop cleaning policy

**Reproduce Steps:**

1. 80% fill up cache device with 4K seq write.
fio --filename=/dev/cas1-1 --direct=1 --thread --rw=write --bs=4k --size=4G --iodepth=128 --ioengine=libaio --numjobs=1 --group_reporting --name=4k_seq_write

2. Enable seq-cutoff, threshold=4KB
casadm -X -n seq-cutoff -p always -i 1 -j 1 -t 4

3. Reset CAS statistic counters
casadm -Z -i 1

4. 4K seq read
fio --filename=/dev/cas1-1 --direct=1 --thread --rw=read --bs=4k --size=4G --iodepth=128 --ioengine=libaio --numjobs=1 --group_reporting --name=4k_seq_read

** Expected Result **
Similar 4K seq read performance as cache device's, because 4K seq read requests should be 100% cache hit. Even it is not 100% cache hit, it should equal to core device's performance.  

**Observed symptoms:** 
1. 4K seq read performance is bad.  cas1-1(BW) = 15MB/s, HDD(BW) = 217MB/s.
2. sequential 4K read requests are not cut off. According to iostat and below statistics, there are R/W requests on core device. 
3. According to CAS statistics, all the dirty cache lines are changed to clean, which means CAS flushes all those dirty cache lines when read hit and performing pass-thru requests (seq-cutoff). 

** CAS IO statistics **
 casadm -P -i 1
Cache Id                  1
Cache Size                1290176 [4KiB Blocks] / 4.92 [GiB]
Cache Device              /dev/nvme2n1p1
Core Devices              1
Inactive Core Devices     0
Write Policy              wb
Eviction Policy           lru
Cleaning Policy           nop
Promotion Policy          always
Cache line size           4 [KiB]
Metadata Memory Footprint 84.4 [MiB]
Dirty for                 13744 [s] / 3 [h] 49 [m] 4 [s]
Metadata Mode             normal
Status                    Running

╔══════════════════╤═════════╤══════╤═════════════╗
║ Usage statistics │  Count  │  %   │   Units     ║
╠══════════════════╪═════════╪══════╪═════════════╣
║ Occupancy        │ 1048705 │ 81.3 │ 4KiB Blocks ║
║ Free             │  241471 │ 18.7 │ 4KiB Blocks ║
║ Clean            │ 1048704 │ 81.3 │ 4KiB Blocks ║
║ Dirty            │       1 │  0.0 │ 4KiB Blocks ║
╚══════════════════╧═════════╧══════╧═════════════╝

╔══════════════════════╤═════════╤═══════╤══════════╗
║ Request statistics   │  Count  │   %   │ Units    ║
╠══════════════════════╪═════════╪═══════╪══════════╣
║ Read hits            │       1 │   0.0 │ Requests ║
║ Read partial misses  │       0 │   0.0 │ Requests ║
║ Read full misses     │       0 │   0.0 │ Requests ║
║ Read total           │       1 │   0.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Write hits           │       0 │   0.0 │ Requests ║
║ Write partial misses │       0 │   0.0 │ Requests ║
║ Write full misses    │       0 │   0.0 │ Requests ║
║ Write total          │       0 │   0.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Pass-Through reads   │ 1048575 │ 100.0 │ Requests ║
║ Pass-Through writes  │       0 │   0.0 │ Requests ║
║ Serviced requests    │       1 │   0.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Total requests       │ 1048576 │ 100.0 │ Requests ║
╚══════════════════════╧═════════╧═══════╧══════════╝

╔══════════════════════════════════╤═════════╤═══════╤═════════════╗
║ Block statistics                 │  Count  │   %   │   Units     ║
╠══════════════════════════════════╪═════════╪═══════╪═════════════╣
║ Reads from core(s)               │ 1048575 │  50.0 │ 4KiB Blocks ║
║ Writes to core(s)                │ 1048575 │  50.0 │ 4KiB Blocks ║
║ Total to/from core(s)            │ 2097150 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼─────────┼───────┼─────────────╢
║ Reads from cache                 │ 1048576 │ 100.0 │ 4KiB Blocks ║
║ Writes to cache                  │       0 │   0.0 │ 4KiB Blocks ║
║ Total to/from cache              │ 1048576 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼─────────┼───────┼─────────────╢
║ Reads from exported object(s)    │ 1048576 │ 100.0 │ 4KiB Blocks ║
║ Writes to exported object(s)     │       0 │   0.0 │ 4KiB Blocks ║
║ Total to/from exported object(s) │ 1048576 │ 100.0 │ 4KiB Blocks ║
╚══════════════════════════════════╧═════════╧═══════╧═════════════╝

╔════════════════════╤═══════╤═════╤══════════╗
║ Error statistics   │ Count │  %  │ Units    ║
╠════════════════════╪═══════╪═════╪══════════╣
║ Cache read errors  │     0 │ 0.0 │ Requests ║
║ Cache write errors │     0 │ 0.0 │ Requests ║
║ Cache total errors │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Core read errors   │     0 │ 0.0 │ Requests ║
║ Core write errors  │     0 │ 0.0 │ Requests ║
║ Core total errors  │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Total errors       │     0 │ 0.0 │ Requests ║
╚════════════════════╧═══════╧═════╧══════════╝

**Comment by michalwy** [comment]
I did a quick investigation of this issue few days ago. There's a special case in PT engine when seq cut-off is on and request references cache lines that are fully dirty: https://github.com/Open-CAS/ocf/blob/2a7a2bd6ca9e684deb2f3f2051165ad12732b0a6/src/engine/engine_pt.c#L123
In this case rq should be handled in WT, resulting in cache hit.
But the flag used in this condition (info.seq_cutoff) is never set and information about seq cut-off is not propagated to PT engine. It's always false.
