### ISSUE TITLE
atomic write format timeout/interrupted on 1.5TB P4800X

### ISSUE THREAD

**Issue by eriksun421** [Open-CAS/open-cas-linux#346]
**Test Config:**

- OS: RHEL7.5
- CAS: v20.01 release
- Cache: P4800X 1.5TB

**Reproduce steps:**
- casadm -N -F atomic -d /dev/nvme0n1

**Expected results:**
Format succeeds, and command return without any error message. 

**Actual results:**
Changing NVMe format failed!
Interrupted system call

**Comment by imjfckm** [comment]
This will be irrelevant after merging #446
