### ISSUE TITLE
Build error message not informative

### ISSUE THREAD

**Issue by esmondchang** [Open-CAS/open-cas-linux#347]
No rule to make target 'inc' stop

**Comment by mmichal10** [comment]
Hi @esmondchang! 

Could give us some more information? What is your OS, kernel version, compiler version?
Do you have ocf submodule in good version? Did you execute `git submodule update --init`?
Did the `confgiure` script return 0 status? 
Have you tried to clean open-cas-linux directory with `make distclean` (you can also try `make distclean && git clean -dxf`), and then configure and build it one more time?

**Comment by mmichal10** [comment]
Hi @esmondchang!

Do you have ocf submodule in good version? Please execute `git submodule update --init`, and then try to build OCL.

Did the confgiure script return 0 status?
Have you tried to clean open-cas-linux directory with make distclean (you can also try make distclean && git clean -dxf), and then configure and build it one more time?

**Comment by esmondchang** [comment]
Hi, 
you are right.  sorry for false alarm. i miss the step to git submodule update.  The configure didn't response any error till you get make error. If user forgot to have submodule update, shouldn't it be report during the configure?

Thanks...

**Comment by robertbaldyga** [comment]
Print message about missing submodule in Makefile.
