### ISSUE TITLE
Changing promotion policy to nhit comsumes a lot of memory and triggers OOM killer

### ISSUE THREAD

**Issue by robertbaldyga** [Open-CAS/open-cas-linux#351]
As nhit policy consumes huge amount of memory, available memory check should be performed before performing policy change. When available memory is too small, policy change should be aborted and appropriate error message should be printed.

**Comment by imjfckm** [comment]
As a first step [https://github.com/Open-CAS/ocf/pull/349]() (pulled by #349) PR should lower the memory consumption a bit. PR with memory checks before changing the policy coming soon.

**Comment by imjfckm** [comment]
#357 should prevent CAS from switching to `nhit` if there's too little memory to do that
