### ISSUE TITLE
Memory usage check is based on suboptimal value

### ISSUE THREAD

**Issue by imjfckm** [Open-CAS/open-cas-linux#358]
Currently `env_get_free_memory` in OCL checks for free, unmapped memory, when it should use available memory instead. On newer(> 4.4) kernels this value can be obtained using `si_mem_available`, for older kernels we should come up with something different.

**Comment by robertbaldyga** [comment]
Let's use `si_mem_available()` on newer kernels and leave is as it is on older kernel.
