### ISSUE TITLE
Manual pages missing info about expected block device naming

### ISSUE THREAD

**Issue by pbaldysi** [Open-CAS/open-cas-linux#359]
Recently I started to play with opencas. During the job I saw that there is no information in manual pages of casadm regarding the fact that the intention of the solution is to create block device in /dev/casX-Y form. 

Please consider adding such info to man pages, so it is clear that opencas will create new block device with particular naming that should be used as regular device.

**Comment by Ostrokrzew** [comment]
You mean something like this?

> The add-core command creates a new device in the /dev directory with the following name format:
> cas\<cache ID\>-<core #> for example: /dev/cas1-1.
> This new device can be treated as a regular block device.

from *https://open-cas.github.io/guide_configuring.html#manual-configuration-for-write-back-mode*?

**Comment by pbaldysi** [comment]
Yes, I might be sufficient. However I would suggest that it might be a little bit more exposed then description of add-core command - Maybe in general overview of openCAS?
