### ISSUE TITLE
Loading cache with --force flag prevents recovery

### ISSUE THREAD

**Issue by imjfckm** [Open-CAS/open-cas-linux#378]
### Description
If you try to run `casadm -S --load --force -d <device>` on a cache device that didn't shutdown cleanly under load the loadprocedure is going to fail and will report CRC error in dmesg. The recovery won't even be attempted as reported in dmesg.

### Reproduction steps
1. Create wb cache
2. Dirty the cache
3. Start flushing
4. Power failure
5. Try to load the cache with `--force` flag

### Expected results
Cache will load (or flags combination will be rejected) or attempt recovery

### Actual results
Cache fails to load, CRC error reported in dmesg, recovery not attempted

### Suggested solutions
First: integrate OCF fix for issue [361](https://github.com/Open-CAS/ocf/issues/361)
Second: Add nice handling of such case. I think that just rejecting `--load` and `--force` flags would be enough - this combination doesn't make sense anyways.

**Comment by mmichal10** [comment]
Expected result: `casadm` should fail gracefully, passing both `--load` and --force` should not be allowed.
