### ISSUE TITLE
Command is not supported by current kernel

### ISSUE THREAD

**Issue by mslovy** [Open-CAS/open-cas-linux#415]
Use cli: 
casadm -N -F atomic -f -d /dev/nvme0n1

and return:
Command is not supported by current kernel

kernel: 
[root@overcloud-novacompute-2 open-cas-linux]# uname -r
3.10.0-1127.el7.x86_64

can anyone know the reason for this?

**Comment by robertbaldyga** [comment]
Newer versions of Linux nvme driver do not provide kernel API for submitting admin request, which is required by CAS to enable atomic writes mode. We are looking for a way to work around this, but right now we don't support atomic mode for some fresher kernels. We will notify you when we solve this problem.

**Comment by mslovy** [comment]
> Newer versions of Linux nvme driver do not provide kernel API for submitting admin request, which is required by CAS to enable atomic writes mode. We are looking for a way to work around this, but right now we do not support atomic writes on some fresher kernels. We will notify you when we solve this problem.

thanks

**Comment by khristenkovladimir** [comment]
Dear All,

Could you tell if atomic writes will be supported in the near future?
Do you have any tests or documentation that can show how performance increases when using atomic writes?

Maybe we can format nvme using nvme-cli, isdct, intelmas etc..?

Thank you.
