### ISSUE TITLE
fio performance issue if I configure wb policy with ramdisk and QLC NVMe disk

### ISSUE THREAD

**Issue by gwnet** [Open-CAS/open-cas-linux#423]
Hello guys,

I create one cas device, cache device is one 80G ramdisk, core device is one QLC NVMe device. 

after configure the wb policy. runing fio, I watch the opencas counter there are a lot hits. but fio performance did not improve any more. 
if I use cache device as optane SSD, core device as the same QLC NVMe device. the fio on cas device will become bad than QLC NVMe standalone test.

**Comment by gwnet** [comment]
===ramdisk+QLCNVMe==
[root@localhost bin]# fio -filename=/dev/cas1-1 -direct=1 -iodepth 256 -thread -rw=write -ioengine=libaio -bs=2048k -size=7000G -numjobs=4 -runtime=60 -group_reporting -name=mytest
mytest: (g=0): rw=write, bs=(R) 2048KiB-2048KiB, (W) 2048KiB-2048KiB, (T) 2048KiB-2048KiB, ioengine=libaio, iodepth=256
...
fio-3.19
Starting 4 threads
Jobs: 4 (f=4): [W(4)][100.0%][w=1027MiB/s][w=513 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=4): err= 0: pid=173086: Tue May 26 11:18:04 2020
  write: IOPS=555, BW=1111MiB/s (1165MB/s)(65.2GiB/60153msec)
    slat (usec): min=346, max=56926, avg=7180.83, stdev=10381.32
    clat (usec): min=8, max=7268.2k, avg=1784970.22, stdev=2186711.91
     lat (msec): min=15, max=7293, avg=1792.15, stdev=2195.07
    clat percentiles (msec):
     |  1.00th=[  397],  5.00th=[  451], 10.00th=[  481], 20.00th=[  523],
     | 30.00th=[  558], 40.00th=[  592], 50.00th=[  634], 60.00th=[  693],
     | 70.00th=[  785], 80.00th=[ 4799], 90.00th=[ 5873], 95.00th=[ 6275],
     | 99.00th=[ 7013], 99.50th=[ 7148], 99.90th=[ 7215], 99.95th=[ 7215],
     | 99.99th=[ 7282]
   bw (  MiB/s): min=  192, max= 1632, per=99.10%, avg=1100.65, stdev=60.67, samples=452
   iops        : min=   93, max=  813, avg=547.41, stdev=30.35, samples=452
  lat (usec)   : 10=0.01%, 50=0.01%, 250=0.01%
  lat (msec)   : 20=0.01%, 50=0.01%, 100=0.03%, 250=0.20%, 500=14.51%
  lat (msec)   : 750=52.73%, 1000=8.68%, 2000=0.66%, >=2000=23.17%
  cpu          : usr=2.30%, sys=85.14%, ctx=138158, majf=0, minf=19993
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.2%, 32=0.4%, >=64=99.2%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=0,33403,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
  WRITE: bw=1111MiB/s (1165MB/s), 1111MiB/s-1111MiB/s (1165MB/s-1165MB/s), io=65.2GiB (70.1GB), run=60153-60153msec

Disk stats (read/write):
    cas1-1: ios=43/534277, merge=0/0, ticks=9/64538902, in_queue=64463275, util=99.82%, aggrios=0/0, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
  nvme3n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
[root@localhost bin]# fio -filename=/dev/cas1-1 -direct=1 -iodepth 256 -thread -rw=read -ioengine=libaio -bs=2048k -size=7000G -numjobs=4 -runtime=60 -group_reporting -name=mytest
mytest: (g=0): rw=read, bs=(R) 2048KiB-2048KiB, (W) 2048KiB-2048KiB, (T) 2048KiB-2048KiB, ioengine=libaio, iodepth=256
...
fio-3.19
Starting 4 threads
Jobs: 4 (f=4): [R(4)][100.0%][r=2619MiB/s][r=1309 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=4): err= 0: pid=173332: Tue May 26 11:19:53 2020
  read: IOPS=1675, BW=3352MiB/s (3515MB/s)(196GiB/60004msec)
    slat (usec): min=1659, max=5486, avg=2383.96, stdev=539.32
    clat (usec): min=9, max=883809, avg=605309.26, stdev=102228.00
     lat (msec): min=2, max=887, avg=607.69, stdev=102.57
    clat percentiles (msec):
     |  1.00th=[  498],  5.00th=[  514], 10.00th=[  518], 20.00th=[  531],
     | 30.00th=[  542], 40.00th=[  550], 50.00th=[  558], 60.00th=[  584],
     | 70.00th=[  642], 80.00th=[  709], 90.00th=[  785], 95.00th=[  802],
     | 99.00th=[  810], 99.50th=[  810], 99.90th=[  852], 99.95th=[  877],
     | 99.99th=[  885]
   bw (  MiB/s): min= 2443, max= 4023, per=100.00%, avg=3358.10, stdev=129.53, samples=472
   iops        : min= 1220, max= 2008, avg=1678.31, stdev=64.86, samples=472
  lat (usec)   : 10=0.01%, 1000=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.04%
  lat (msec)   : 100=0.06%, 250=0.19%, 500=0.99%, 750=80.99%, 1000=17.70%
  cpu          : usr=0.11%, sys=99.65%, ctx=81, majf=0, minf=14508
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=99.7%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=100558,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=3352MiB/s (3515MB/s), 3352MiB/s-3352MiB/s (3515MB/s-3515MB/s), io=196GiB (211GB), run=60004-60004msec

Disk stats (read/write):
    cas1-1: ios=1604533/0, merge=0/0, ticks=218672/0, in_queue=78617, util=67.55%, aggrios=0/0, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
  nvme3n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
[root@localhost bin]#

**Comment by gwnet** [comment]
===optane SSD+QLC NVMe test===
Device	            Fio seqwrite(2MB)	Fio seqread(2MB)
Optane SSD	        2454MB/s	        2693MB/s
QLC NVMe SSD	    1132MB/s	        3139MB/s
OpenCas+WB policy	1062MB/s	        2330MB/s

**Comment by gwnet** [comment]
hello guys, I adjust the test configuration. here is my latest finding that is very strange to me. could you please help me debug and instruct me how to move?

Very interesting. I create one partition also 80G on the nvme3n1 device. I use 80G ramdisk + 80G QLC nvme. I think fio result will be very high because I am write back mode. All the writes goes into ram disk. The throughput should be very high.
But it is still low.


[root@localhost ~]# fio -filename=/dev/cas1-1 -direct=1 -iodepth 256 -thread -rw=write -ioengine=libaio -bs=2048k -size=80G -numjobs=4 -runtime=60 -group_reporting -name=mytest
mytest: (g=0): rw=write, bs=(R) 2048KiB-2048KiB, (W) 2048KiB-2048KiB, (T) 2048KiB-2048KiB, ioengine=libaio, iodepth=256
...
fio-3.19
Starting 4 threads
Jobs: 4 (f=4): [W(4)][100.0%][w=1186MiB/s][w=593 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=4): err= 0: pid=231580: Wed May 27 02:02:57 2020
  write: IOPS=586, BW=1173MiB/s (1230MB/s)(68.8GiB/60100msec)
    slat (usec): min=344, max=75812, avg=6804.20, stdev=9693.14
    clat (usec): min=6, max=7413.6k, avg=1710576.27, stdev=2070936.94
     lat (msec): min=15, max=7436, avg=1717.38, stdev=2078.87

===from iostat, we can see during fio test, actually no IO happen on the nvme3n1, should all cache on the cache device the ramdisk. But why throughput cannot be RAM level?
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    2.50     0.00     0.00     3.60     0.00    0.20    0.00    0.20   0.20   0.05
sdb               0.00     0.00    0.00    2.50     0.00     0.00     3.60     0.00    0.60    0.00    0.60   0.60   0.15
md126             0.00     0.00    0.00    1.50     0.00     0.00     5.33     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    1.00     0.00     0.00     8.00     0.00    2.00    0.00    2.00   2.00   0.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme1n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme3n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme5n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme0n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme2n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme4n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
cas2-1            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
cas1-1            0.00     0.00    0.00 8338.50     0.00  1042.31   256.00  1229.94  137.99    0.00  137.99   0.12 100.25

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
md126             0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme1n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme3n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme5n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme0n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme2n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
nvme4n1           0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
cas2-1            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
cas1-1            0.00     0.00    0.00 8589.00     0.00  1073.62   256.00  1287.80  156.62    0.00  156.62   0.12 100.10

===opencas counter===
[root@localhost ~]#  casadm -P -i 1
Cache Id                  1
Cache Size                20713376 [4KiB Blocks] / 79.02 [GiB]
Cache Device              /dev/ram0
Core Devices              1
Inactive Core Devices     0
Write Policy              wb
Eviction Policy           lru
Cleaning Policy           alru
Promotion Policy          always
Cache line size           4 [KiB]
Metadata Memory Footprint 1.1 [GiB]
Dirty for                 446 [s] / 7 [m] 26 [s]
Metadata Mode             normal
Status                    Running

╔══════════════════╤══════════╤══════╤═════════════╗
║ Usage statistics │  Count   │  %   │   Units     ║
╠══════════════════╪══════════╪══════╪═════════════╣
║ Occupancy        │ 13177986 │ 63.6 │ 4KiB Blocks ║
║ Free             │  7535390 │ 36.4 │ 4KiB Blocks ║
║ Clean            │  3087562 │ 14.9 │ 4KiB Blocks ║
║ Dirty            │ 10090424 │ 48.7 │ 4KiB Blocks ║
╚══════════════════╧══════════╧══════╧═════════════╝

╔══════════════════════╤═════════╤═══════╤══════════╗
║ Request statistics   │  Count  │   %   │ Units    ║
╠══════════════════════╪═════════╪═══════╪══════════╣
║ Read hits            │     215 │   0.0 │ Requests ║
║ Read partial misses  │       0 │   0.0 │ Requests ║
║ Read full misses     │      43 │   0.0 │ Requests ║
║ Read total           │     258 │   0.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Write hits           │  774708 │  65.3 │ Requests ║
║ Write partial misses │       2 │   0.0 │ Requests ║
║ Write full misses    │  411802 │  34.7 │ Requests ║
║ Write total          │ 1186512 │ 100.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Pass-Through reads   │       0 │   0.0 │ Requests ║
║ Pass-Through writes  │       0 │   0.0 │ Requests ║
║ Serviced requests    │ 1186770 │ 100.0 │ Requests ║
╟──────────────────────┼─────────┼───────┼──────────╢
║ Total requests       │ 1186770 │ 100.0 │ Requests ║
╚══════════════════════╧═════════╧═══════╧══════════╝

╔══════════════════════════════════╤══════════╤═══════╤═════════════╗
║ Block statistics                 │  Count   │   %   │   Units     ║
╠══════════════════════════════════╪══════════╪═══════╪═════════════╣
║ Reads from core(s)               │      260 │   0.0 │ 4KiB Blocks ║
║ Writes to core(s)                │  5577800 │ 100.0 │ 4KiB Blocks ║
║ Total to/from core(s)            │  5578060 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼──────────┼───────┼─────────────╢
║ Reads from cache                 │  5579096 │  12.8 │ 4KiB Blocks ║
║ Writes to cache                  │ 37968644 │  87.2 │ 4KiB Blocks ║
║ Total to/from cache              │ 43547740 │ 100.0 │ 4KiB Blocks ║
╟──────────────────────────────────┼──────────┼───────┼─────────────╢
║ Reads from exported object(s)    │     1555 │   0.0 │ 4KiB Blocks ║
║ Writes to exported object(s)     │ 37968384 │ 100.0 │ 4KiB Blocks ║
║ Total to/from exported object(s) │ 37969939 │ 100.0 │ 4KiB Blocks ║
╚══════════════════════════════════╧══════════╧═══════╧═════════════╝

╔════════════════════╤═══════╤═════╤══════════╗
║ Error statistics   │ Count │  %  │ Units    ║
╠════════════════════╪═══════╪═════╪══════════╣
║ Cache read errors  │     0 │ 0.0 │ Requests ║
║ Cache write errors │     0 │ 0.0 │ Requests ║
║ Cache total errors │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Core read errors   │     0 │ 0.0 │ Requests ║
║ Core write errors  │     0 │ 0.0 │ Requests ║
║ Core total errors  │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Total errors       │     0 │ 0.0 │ Requests ║
╚════════════════════╧═══════╧═════╧══════════╝

**Comment by gwnet** [comment]
currently I move to other high priority issue. can we keep it monitor as low priority. or any developer can try to reproduce too with my configure? just ramdisk can cache device.

**Comment by katlapinka** [comment]
@gwnet any update on this issue? Or maybe we can close this?

**Comment by katlapinka** [comment]
I am closing this issue after long time without any update. Please reopen in case the problem will still occur.

**Comment by mslovy** [comment]
Is that because the 4KB cache-line size? I find that your io pattern is large IO and the opencas will split those large IO to small 4KB cache-line size. It seems a large cache-line size will improve the performance.
