### ISSUE TITLE
CAS service not starting properly on RHEL 8.2

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#426]
System enters maintenance mode after trying to start open-cas.service during boot
![image](https://user-images.githubusercontent.com/45125679/83027827-e6d7d400-a030-11ea-8ad0-9013f2b53cfd.png)

journalctl -xe
![image](https://user-images.githubusercontent.com/45125679/83027637-9eb8b180-a030-11ea-8974-1d69b9e77b04.png)
![image](https://user-images.githubusercontent.com/45125679/83027726-c0199d80-a030-11ea-8f52-95a11a1f9dfa.png)

**Comment by Deixx** [comment]
in maintenance mode service cannot be started manually

journalctl -xe
![image](https://user-images.githubusercontent.com/45125679/83028236-6e254780-a031-11ea-9fcb-c28bf7657fb7.png)

**Comment by imjfckm** [comment]
Seems to me that it's SELinux policy interfering with our settle service. I'm not an expert on SELinux, so I'll try to educate myself before coming up with some solution. I presume it's gonna be either a guidance in our Admin Guide or maybe we could automate that during installation.

**Comment by stdweird** [comment]
@Deixx anychance you can share the relevant /var/log/audit/audit.log entries (if you still have them, probably in the last rotated ones by now)

**Comment by stdweird** [comment]
@Deixx i just tried this on an up-to-date rhel82 box, i do not have this issue. i used a rpm based install

**Comment by Deixx** [comment]
@stdweird thanks for checking the issue. I have additional question - what was the OpenCAS setup, when you checked it? I mean - did you have cache(s) started with core(s) added and was this configuration reflected in /etc/opencas/opencas.conf when you booted the OS? 
As for your prior question - unfortunately I don't have the logs you requested. I'll try find the time to reproduce the problem and gather them.

**Comment by stdweird** [comment]
@Deixx yes, this is a reboot with CAS starting up and being active (1 cache dev, 3 core devs behind it).
did you use a rpm based install or a manual one?

**Comment by Deixx** [comment]
When I encountered this issue CAS was (most probably) installed from sources, but the installation method shouldn't really matter. Anyways - I'll try to reproduce this with CAS installed both ways.

**Comment by Deixx** [comment]
Issue reproduced only with CAS installed from sources. Linked README update contains info about remedying this.
