### ISSUE TITLE
Not loading cache after system restart on CentOS 7.8

### ISSUE THREAD

**Issue by darktorana** [Open-CAS/open-cas-linux#431]
### Environment:
OS: CentOS 7.8
Kernel: 3.10.0-1127.8.2.el7.x86_64
OpenCAS Version: 20.03.00.00000604
Also tried:
OpenCAS Version: 20.06.00.00000603

### Issue:
Restarting the server with OpenCAS Config configured, leads to emergency mode as it fails to come up during the start-job.
It tried for 30 minutes until it eventually fails.
![image](https://user-images.githubusercontent.com/44046564/83716411-2cb91b80-a673-11ea-84e5-242c9ea17f54.png)
![image](https://user-images.githubusercontent.com/44046564/83716428-393d7400-a673-11ea-90ab-d80ef7fa781e.png)

### Expected: 
For it to correctly boot the OS with the OpenCAS Cache in place.

### Configuration File: (Comments removed)
>version=19.3.0
[caches]
1               /dev/disk/by-id/wwn-0x5002538b9961a700  WB
[cores]
1               1               /dev/disk/by-id/wwn-0x64cd98f07ea64b002668849a0aac780f-part5

###Description:
We can run start the cache by running the following fine:
> casctl start

Which in turn calls:
> /sbin/casadm --start-cache --cache-device /dev/disk/by-id/wwn-0x5002538b9961a700 --cache-id 1 --cache-mode wb --load

And it all starts and runs correctly, I can mount it as per /etc/fstab and use it as per normal.

The issue is that if I restart the server, it will always go into emergency mode so long as the configuration file doesn't have the cache and core lines commented out.
If I comment it out and restart, it restarts normally, and I can then run the 'casctl start' normally

The error generated in /var/log/opencas.log from the failed booting is:
Thu Jun  4 14:32:09 2020 casadm: Failed to retrieve cache information!

I can see that error is generated from /opt/open-cas-linux/casadm/cas_lib.c and it's looking to see if the cache is made from what I can understand.
I believe it is this file that is calling it '/usr/lib/udev/rules.d/60-persistent-storage-cas-load.rules', but I can't see what is actually 'starting' the cache, only the settle command.

Highly likely I am missing something.

### Steps:

1. Run below commands:
>cd /opt/
*git clone https://github.com/Open-CAS/open-cas-linux
cd open-cas-linux
git submodule update --init
yum install python3 gcc kernel-headers kernel-devel -y; yum update kernel-headers kernel-devel -y
./configure
make
make install
casadm -V
2. Edit /etc/opencas/opencas.conf adding in the above cache/core
3. casctl init (or start if it's already initialized)
4. reboot server

*Alternatively use:
>https://github.com/Open-CAS/open-cas-linux/releases/download/v20.3/open-cas-linux-v20.03.0.0286.tar.gz
tar -xf open-cas-linux-v20.03.0.0286.tar.gz
mv open-cas-linux-v20.03.0.0286 open-cas-linux

**Comment by darktorana** [comment]
Additional information: This is a baremetal installation, I note because I set it up the same way in a VM and it didn't have the problem.

**Comment by imjfckm** [comment]
Hi @darktorana, thanks for your report.

`open-cas.service` drops to emergency shell whenever it can't detect that the cache configuration you have specified in your `/etc/opencas/opencas.conf` started in given timeout. `/usr/lib/udev/rules.d/60-persistent-storage-cas-load.rules` should grab the devices specified in config when they appear and add them to CAS configuration (either load a cache if it's a cache device or add the core to cache/core pool if it's a core device).

Given that you're able to manually start the cache after rebooting it's unlikely that the device disappeared between reboots, so there must be some other reason why CAS didn't manage to start the configuration.

I'll need some more details to give you definite answers to why did that happen and what could be done.

1. When CAS drops to emergency shell what is the output of `lsblk`, `casadm -L` and does `casctl start` work in emergency shell?
2. Are there any additional logs in `journalctl/dmesg` concerning CAS? Some traces of cache starting/failing to start, any mentions of `open-cas-loader`?
3. How big is the caching device? I see it's in WB mode, maybe it takes unexpectedly long time to recover after dirty shutdown.

**Comment by darktorana** [comment]
I tried to recreate the issue for you, but for the life of me, it is booting every time now.

I should note that in the original testing, I had it not try to mount the folder during boot to ensure it had the full 30 minutes to try to start and continued to fail.
I've restarted today about a dozen times and it comes up everytime without issue. So honestly I can't say what the issue was.

It is a 2TB disk so potentially the size of it was an issue? Would you say 2TB is a reasonable size (sitting in front of ~10TB of data with 20TB of storage), or that it might be best to use smaller disks to ensure the start time?

**Comment by imjfckm** [comment]
Well, without full logs of failing run there's not much I can come up with. Recovery is one possible path in which CAS could take longer then usual to start, but not that long. Unless you're using atomic mode - in that case it would be possible it took longer than the 30m limit, because then we have to read WHOLE device, not just metadata section.

If you encounter it again, please collect full journal/dmesg logs - that way we can check if cas-loader complained about anything, or maybe recovery indeed took longer than expected.

I think you should size your cache device based on your workset size and workload characteristics, I wouldn't recommend sizing your cache to reduce startup time.

**Comment by darktorana** [comment]
As I am unable to make this happen or get you any extra information, I will close this issue and thank you for your assistance.
