### ISSUE TITLE
why my read workload create so many pass through reads to open-cas

### ISSUE THREAD

**Issue by gwnet** [Open-CAS/open-cas-linux#437]
Hello experts

I run minio on the open-cas, I read fixed sets object in stress test. I feel the cache hit should increase. but it is strange, I also see a lot of pass through read requests. why this happen? how can I know where these pass through requests comes? and why?

intel@wcp116:~$ sudo casadm -P -i 1 -j 1
[sudo] password for intel: 
Core Id              1
Core Device          /dev/sde
Exported Object      /dev/cas1-1
Core Size            976754646 [4KiB Blocks] / 3726.02 [GiB]
Dirty for            0 [s] / Cache clean
Status               Active
Seq cutoff threshold 1024 [KiB]
Seq cutoff policy    full

╔══════════════════╤══════════╤═══════╤═════════════╗
║ Usage statistics │  Count   │   %   │   Units     ║
╠══════════════════╪══════════╪═══════╪═════════════╣
║ Occupancy        │ 45812608 │ 100.0 │ 4KiB Blocks ║
║ Free             │     1696 │   0.0 │ 4KiB Blocks ║
║ Clean            │ 45812608 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │        0 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧══════════╧═══════╧═════════════╝

╔══════════════════════╤════════╤═══════╤══════════╗
║ Request statistics   │ Count  │   %   │ Units    ║
╠══════════════════════╪════════╪═══════╪══════════╣
║ Read hits            │ 149821 │  34.0 │ Requests ║
║ Read partial misses  │   1400 │   0.3 │ Requests ║
║ Read full misses     │  45723 │  10.4 │ Requests ║
║ Read total           │ 196944 │  44.7 │ Requests ║
╟──────────────────────┼────────┼───────┼──────────╢
║ Write hits           │     14 │   0.0 │ Requests ║
║ Write partial misses │      0 │   0.0 │ Requests ║
║ Write full misses    │      6 │   0.0 │ Requests ║
║ Write total          │     20 │   0.0 │ Requests ║
╟──────────────────────┼────────┼───────┼──────────╢
║ Pass-Through reads   │ 243933 │  55.3 │ Requests ║
║ Pass-Through writes  │      0 │   0.0 │ Requests ║
║ Serviced requests    │ 196964 │  44.7 │ Requests ║
╟──────────────────────┼────────┼───────┼──────────╢
║ Total requests       │ 440897 │ 100.0 │ Requests ║
╚══════════════════════╧════════╧═══════╧══════════╝

╔═══════════════════════════════╤══════════╤═══════╤═════════════╗
║ Block statistics              │  Count   │   %   │   Units     ║
╠═══════════════════════════════╪══════════╪═══════╪═════════════╣
║ Reads from core               │  8391829 │ 100.0 │ 4KiB Blocks ║
║ Writes to core                │      118 │   0.0 │ 4KiB Blocks ║
║ Total to/from core            │  8391947 │ 100.0 │ 4KiB Blocks ║
╟───────────────────────────────┼──────────┼───────┼─────────────╢
║ Reads from cache              │  3773743 │  74.1 │ 4KiB Blocks ║
║ Writes to cache               │  1320252 │  25.9 │ 4KiB Blocks ║
║ Total to/from cache           │  5093995 │ 100.0 │ 4KiB Blocks ║
╟───────────────────────────────┼──────────┼───────┼─────────────╢
║ Reads from exported object    │ 12165396 │ 100.0 │ 4KiB Blocks ║
║ Writes to exported object     │       32 │   0.0 │ 4KiB Blocks ║
║ Total to/from exported object │ 12165428 │ 100.0 │ 4KiB Blocks ║
╚═══════════════════════════════╧══════════╧═══════╧═════════════╝

╔════════════════════╤═══════╤═════╤══════════╗
║ Error statistics   │ Count │  %  │ Units    ║
╠════════════════════╪═══════╪═════╪══════════╣
║ Cache read errors  │     0 │ 0.0 │ Requests ║
║ Cache write errors │     0 │ 0.0 │ Requests ║
║ Cache total errors │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Core read errors   │     0 │ 0.0 │ Requests ║
║ Core write errors  │     0 │ 0.0 │ Requests ║
║ Core total errors  │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Total errors       │     0 │ 0.0 │ Requests ║
╚════════════════════╧═══════╧═════╧══════════╝
intel@wcp116:~$

**Comment by gwnet** [comment]
hello after I turn off the seq-cutoff, the pass through reads are gone. :)
here I have another issue. 
my requests are all read requests, when the cache device is written by cas, the read request hit rate drop very much. why?
nvme0n1 and nvme1n1 is optane cache device. when I see the write cache going on, read hit rate drop a lot.

00   0.00
nvme0n1        143.00      0.70     0.00   0.00    0.03     4.99 3168.00    133.35     0.00   0.00    0.07    43.10    0.00      0.00     0.00   0.00    0.00     0.00    0.00  98.60
nvme1n1        116.50      0.60     0.00   0.00    0.03     5.24 3221.00    133.69     0.00   0.00    0.06    42.50    0.00      0.00     0.00   0.00    0.00     0.00    0.00  97.40
sda              0.00      0.00     0.00   0.00    0.00     0.00    2.50      0.02     2.00  44.44    0.20     8.80    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.20
sdb              0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
sdc              0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
sdd              0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
sde            592.50     68.07     0.00   0.00   25.63   117.64    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00   14.63  90.80
sdf            545.50     65.28     0.00   0.00   19.75   122.54    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00   10.23  81.20
sdg            568.00     65.43     1.00   0.18   19.33   117.96    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00   10.44  82.60
sdh            594.50     68.26     0.50   0.08   24.55   117.57    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00   14.07  86.60


intel@wcp116:~$ sudo  casadm -P -i 3 -j 1 
Core Id              1
Core Device          /dev/sdg
Exported Object      /dev/cas3-1
Core Size            976754646 [4KiB Blocks] / 3726.02 [GiB]
Dirty for            97 [s] / 1 [m] 37 [s]
Status               Active
Seq cutoff threshold 1024 [KiB]
Seq cutoff policy    never

╔══════════════════╤══════════╤═══════╤═════════════╗
║ Usage statistics │  Count   │   %   │   Units     ║
╠══════════════════╪══════════╪═══════╪═════════════╣
║ Occupancy        │ 45812864 │ 100.0 │ 4KiB Blocks ║
║ Free             │     1440 │   0.0 │ 4KiB Blocks ║
║ Clean            │ 45805840 │ 100.0 │ 4KiB Blocks ║
║ Dirty            │     7024 │   0.0 │ 4KiB Blocks ║
╚══════════════════╧══════════╧═══════╧═════════════╝

╔══════════════════════╤════════╤═══════╤══════════╗
║ Request statistics   │ Count  │   %   │ Units    ║
╠══════════════════════╪════════╪═══════╪══════════╣
║ Read hits            │ 328391 │  93.0 │ Requests ║
║ Read partial misses  │    225 │   0.1 │ Requests ║
║ Read full misses     │  24404 │   6.9 │ Requests ║
║ Read total           │ 353020 │ 100.0 │ Requests ║
╟──────────────────────┼────────┼───────┼──────────╢
║ Write hits           │      6 │   0.0 │ Requests ║
║ Write partial misses │      0 │   0.0 │ Requests ║
║ Write full misses    │      2 │   0.0 │ Requests ║
║ Write total          │      8 │   0.0 │ Requests ║
╟──────────────────────┼────────┼───────┼──────────╢
║ Pass-Through reads   │      0 │   0.0 │ Requests ║
║ Pass-Through writes  │      0 │   0.0 │ Requests ║
║ Serviced requests    │ 353028 │ 100.0 │ Requests ║
╟──────────────────────┼────────┼───────┼──────────╢
║ Total requests       │ 353028 │ 100.0 │ Requests ║
╚══════════════════════╧════════╧═══════╧══════════╝

╔═══════════════════════════════╤═════════╤═══════╤═════════════╗
║ Block statistics              │  Count  │   %   │   Units     ║
╠═══════════════════════════════╪═════════╪═══════╪═════════════╣
║ Reads from core               │  729941 │ 100.0 │ 4KiB Blocks ║
║ Writes to core                │       0 │   0.0 │ 4KiB Blocks ║
║ Total to/from core            │  729941 │ 100.0 │ 4KiB Blocks ║
╟───────────────────────────────┼─────────┼───────┼─────────────╢
║ Reads from cache              │ 8788118 │  92.3 │ 4KiB Blocks ║
║ Writes to cache               │  729695 │   7.7 │ 4KiB Blocks ║
║ Total to/from cache           │ 9517813 │ 100.0 │ 4KiB Blocks ║
╟───────────────────────────────┼─────────┼───────┼─────────────╢
║ Reads from exported object    │ 9518059 │ 100.0 │ 4KiB Blocks ║
║ Writes to exported object     │      11 │   0.0 │ 4KiB Blocks ║
║ Total to/from exported object │ 9518070 │ 100.0 │ 4KiB Blocks ║
╚═══════════════════════════════╧═════════╧═══════╧═════════════╝

╔════════════════════╤═══════╤═════╤══════════╗
║ Error statistics   │ Count │  %  │ Units    ║
╠════════════════════╪═══════╪═════╪══════════╣
║ Cache read errors  │     0 │ 0.0 │ Requests ║
║ Cache write errors │     0 │ 0.0 │ Requests ║
║ Cache total errors │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Core read errors   │     0 │ 0.0 │ Requests ║
║ Core write errors  │     0 │ 0.0 │ Requests ║
║ Core total errors  │     0 │ 0.0 │ Requests ║
╟────────────────────┼───────┼─────┼──────────╢
║ Total errors       │     0 │ 0.0 │ Requests ║
╚════════════════════╧═══════╧═════╧══════════╝

**Comment by mmichal10** [comment]
Hi, @gwnet 

The data you are reading may be not be cached yet. In such scenario data will be read from core device, request will be marked in statistics as a miss. After returning data to user, CAS will perform backfill in background, so next time you want to access the same data it will be read from cache and such request will be marked as hit.

**Comment by gwnet** [comment]
@mmichal10 thank you so much. you are correct. it is because my mongoose client tool run 40 threads, one thread remove the cache that the other thread is trying to read, this cause so many not hit.

**Comment by gwnet** [comment]
all are clear now.
