### ISSUE TITLE
Supporting adaptive device size?

### ISSUE THREAD

**Issue by hairbear** [Open-CAS/open-cas-linux#458]
For an intern project this summer, I am meant to modify Open CAS Linux to support an adaptive device size, however I have run into a roadblock and do not know how to fix the resulting metadata issues. Would it be possible for someone to work with me one on one?

**Comment by robertbaldyga** [comment]
Do you plan to implement adaptive device size for cache device, for core device or maybe for both?
In case of cache device it would be quite complicated. Most of Open CAS data structures, which sizes are dependent on size of cache device, are not designed to be dynamically resized. For core device this may be simpler, but still may need some redesign in metadata.

Can you describe what specific issues you have? I think it would be most effective to look at them one by one and try to find some solution.

**Comment by hairbear** [comment]
I think the specific issues with my experiments so far would be solved with a better idea of the overall design necessary.

I plan to implement adaptive device size for the cache device only. Is metadata redesign still necessary if only sequential layout is used, instead of striping layout? In general I don't understand the implementation of metadata well enough and would appreciate an extended discussion.

**Comment by imjfckm** [comment]
Hi @hairbear,

Thanks for your interest and initiative!

What @robertbaldyga said is true - in general it will be hard, but depending on what your exact requirements are it ranges from "tedious, but doable" to complete OCF rewrite.

I think your best shot at doing this kind of thing it to use OCF's [attach](https://github.com/Open-CAS/ocf/blob/d144f18959b9a7678b256efcc26ca445bc3804d6/inc/ocf_mngt.h#L471)/[detach](https://github.com/Open-CAS/ocf/blob/d144f18959b9a7678b256efcc26ca445bc3804d6/inc/ocf_mngt.h#L492) API:

1. Detach cache device
2. Resize
3. Attach cache device

There should be no major obstacles to this approach - you would just need to handle this API in OCL and expose it to casadm.

Of course there are some drawbacks to this simple solution - if you're using WB cache mode it can take a long time to flush all dirty data to core device and all the traffic will be served directly from core device, but the exported object will still be present so no change for any app/mounts that are using it (aside from obvious performance drop).

If you were to pursue something more advanced that wouldn't require caching to stop - that's when you would need to look at metadata layout details and that's the OCF rewrite territory.

Let me know if that's what you were going for and don't hesitate to ask if you have some more questions!

**Comment by imjfckm** [comment]
Closing for now. Feel free to reopen if still relevant!
