### ISSUE TITLE
sudden power lost test fail to load device if configure opencas.config

### ISSUE THREAD

**Issue by gwnet** [Open-CAS/open-cas-linux#517]
1. if configure opencas.config, do the sudden power lost test, OS failed to bring up because of opencas
 
![image](https://user-images.githubusercontent.com/7543276/91917370-490c3900-ecf2-11ea-845e-88ec3b267d5a.png)

2. if delete the core device information from opencas.config or do not use opencas.config at all. just use casadm load, after sudden power lost, OS can boot up correctly, cache configuration can recovery, but partial data looks like lost.
![image](https://user-images.githubusercontent.com/7543276/91917769-7d342980-ecf3-11ea-9ea1-43852bbc4aed.png)

more detail test steps  and test results:
1. configure the opencas.config file, want to leverage this to prepare cas device well before other user service started
2. find some operations may impact that OS reboot failed with opencas. if do sudden power lost test, OS will fail to bring up because of opencas for sure.
3. the only work around now is to modify opencas.configure file remove the core device, then OS can bring up normally.

detail about the temp solution and the data consistent issue suffered:
1. when create new cache instance, only write the cache device info to opencas.config as work around.

if the normal reboot, everything works fine.
if sudden power lost test, cannot promise data consistent, detail test result are:
acp and nop is our flush dirty policy.
1. wb mode, use acp, then sudden power lost. if dirty already flushed to core device, after reboot, data consistent is good. when issue read request, it read from core device not core device. --- I feel this is worked as designed.
2. wb mode, use acp, then sudden power lost, if dirty is not fully flushed into core, after reboot, data is not consistent.
3. wb mode, use NOP, then sudden power lost, after reboot, if cache is not full, read data is serviced by cache, data is consistent
4. wb mode, use NOP, then sudden power lost, after reboot, if cache is full, data is not very consistent. ---- need more specific info, if cache is full, it will use wt mode, data should be consistent.

**Comment by gwnet** [comment]
1. after clarification, data consistent issue is reported by vdbench tool, we do one test, sudden power lost, bdbench on one single disk without opencas, it report error too. so we can skip this data integrity issue for now. we may try test with dd directly.
![image](https://user-images.githubusercontent.com/7543276/91960417-77af0180-ed3c-11ea-8d42-4a5864703981.png)

2. for the OS bring failure issue, if we remove the soft link that is created by user to point to core device too, we did not reproduce the boot up issue again. it is strange that opencas try to open one soft link that is created by user not the wwn name that is specified in the opencas.conf.
![image](https://user-images.githubusercontent.com/7543276/91960696-cceb1300-ed3c-11ea-9f37-8d3d85a9ef8b.png)

**Comment by gwnet** [comment]
for 2nd issue, one workaround now we found is that we do not specify the core device information in opencas.conf. then do the sudden power lost test, OS can bring up correct without open /dev/disk/by-id/esss-disk-uuid-xxx   softlink that is created by other service on the cas device. 
may I know if this work around solution has no risk? 
if we do not specify the core device in the opencas.conf, where opencas to load the correct core device?

**Comment by arutk** [comment]
Hi @gwnet. Answering your questions:
1. What you describe looks like a valid sequence to me. You can perform the initial configuration by either using casctl or manually (casadm + editing .conf file after starting the cache).
2.  If you don't specify cores in opencas.conf, then two bad things may happen during the startup:
   a. Another service claims the core device before CAS
   b. CAS starts with detached (missing) core, although the device is available in the system after OS fully starts.
Either way you end up with core device not claimed by CAS. Worst case scenario is that the associated cache is dirty and the data on core device is out of date. Application might mistake the core device for CAS exported object and end up using old data.

**Comment by arutk** [comment]
@gwnet I'm told that you spoke with one of our engineers and the issue boils down to casadm resolving provided by-id path to **different** by-id path. The issue would be fixed by changing casadm behavior not to resolve the input path in case this is already a /dev/by-id/... path. Is this correct?

**Comment by gwnet** [comment]
@arutk, Yes the 2nd issue work around should work, customer have not tried yet. for the 1st issue, they are trying to reproduce the data consistence issue during sudden power lost. they may share us result later
