### ISSUE TITLE
a question about cache_line_size

### ISSUE THREAD

**Issue by ycs0220** [Open-CAS/open-cas-linux#534]
I have a question about cache_line_size：

If the cache-line-size is set to be relatively large, such as 32K, WB+ACP. At this time, if I use fio random 8K to pressure test, the iostat that is dirty to the core device seems to be written in 512B blocks; if fio uses higher than 32K, there is no problem
![image](https://user-images.githubusercontent.com/34889631/93963532-04733b00-fd90-11ea-810e-fd8927217846.png)

Looking forward to your reply，Thanks

**Comment by mmichal10** [comment]
Hi @ycs0220 

Could you share with us some more informations about:
- OpenCAS version (Could you provide commit id)?
- OS and kernel version?
- fio version?

**Comment by mmichal10** [comment]
I'm closing issue due a lack of response.
