### ISSUE TITLE
loading cas_cache timeout during booting os

### ISSUE THREAD

**Issue by mslovy** [Open-CAS/open-cas-linux#537]
For large SSD such as > 2TB, when we reboot the system. It will be timeout for running udev to loading cache in https://github.com/Open-CAS/open-cas-linux/blob/master/utils/open-cas-loader when system boot. And then the system run into a rescue mode, any suggestion to workaround for that?

**Comment by imjfckm** [comment]
Hi @mslovy, thanks for your report.

We are in process of designing more robust solution for that problem. In the meantime there are two workarounds you can try:

### 1. Mark cores attached to this slow loading cache as `lazy_startup=true`:
```ini
(...)
[cores]
1 1 /dev/sda lazy_startup=true
(...)
```
**IMPORTANT:** This will cause the boot process to not wait for given core to be added to CAS. If you have some other services which may claim this drive **based on metadata stored on it** this may cause races for this specific device. E.g.: if you have an `fstab` entry that mounts it based on filesystem label, CAS will race with mount systemd unit and your mount may not work.

### 2. Extend the timeout for open-cas.service:
The file is located either at `/usr/lib/systemd/system/open-cas.service` or `/lib/systemd/system/open-cas.service`

You should measure the time it takes to load the cache (keep in mind that it may be longer if it's after a dirty shutdown) and change both `TimeoutStartSec=**<this value>**` and `ExecStart=/sbin/casctl settle --timeout **<this value>** --interval 5`. For logging purposes it would be better if the second one is 30 secs shorter - it's best if settle times out before systemd unit does - this way we can notify what exactly broke.

**Comment by katlapinka** [comment]
I assume that the solution gave by @imjfckm works fine, because there is no continuation of the bug topic, so I am closing this issue.
Please reopen if this bug will occur once again.
