### ISSUE TITLE
Metadata version mismatch after upgrade from v20.3 to v20.3.2

### ISSUE THREAD

**Issue by serjponomarev** [Open-CAS/open-cas-linux#552]
After upgrading from version v20.3 to v20.3.2 i got a message

**Error inserting cache 1
Metadata version mismatch.**

Distro: CentOS Linux release 8.2.2004 (Core) 
Kernel: 4.18.0-193.19.1.el8_2.x86_64
Setup method: rpm packages

**Comment by imjfckm** [comment]
Hi @serjponomarev, thanks for your report.

Am I correct to think that you tried to `--load` a cache created with v20.3 in v20.3.2? If yes, then unfortunately this case is not supported (yet). OCF refuses to load cache created with other version of software. In the future we will be implementing metadata migration to assure seamless upgrade experience.

For now I think you need to stop the cache completely and flush all the cores: `casctl stop --flush` and only then upgrade CAS and reinstate the configuration using `casctl init --force`.

**Comment by serjponomarev** [comment]
I just built new packages and updated the CAS. After that I rebooted the host.

**Comment by serjponomarev** [comment]
@imjfckm add this information to the main tutorial to let others know that you cannot migrate from version to version without reinitializing the metadata.

**Comment by Deixx** [comment]
@mmichal10 pls add info
