### ISSUE TITLE
Multistreaming sequential cutoff not working for version 20.03.3.0307

### ISSUE THREAD

**Issue by serjponomarev** [Open-CAS/open-cas-linux#588]
OS: CentOS 8.2 with last updates
CAS: 20.03.3.0307

cas cutoff params:
`casadm -X -n seq-cutoff -i 1 -j 1 -p always -t 1024`

When I write data to the device using the fio command:
`fio --name=nvme --numjobs=1 --iodepth=2 --bs=1024k --rw=write --ioengine=libaio --direct=1 --group_reporting=1 --filename=/dev/cas1-1 --runtime=30 --time_based=1`
cutoff is working and all data going to core

but when i am using fio command:
`fio --name=nvme --numjobs=2 --iodepth=2 --bs=1024k --rw=write --ioengine=libaio --direct=1 --group_reporting=1 --filename=/dev/cas1-1 --runtime=30 --time_based=1`
data is written to cache

Is this normal behavior or a bug?
If this is normal behavior, then how should multistreaming work for sequential data?

**Comment by katlapinka** [comment]
Hello @serjponomarev 
The behavior you observe is an expected one, because you are using CAS 20.03.3 version and the multistream sequential cutoff feature will be introduced in OpenCAS 20.12 version which will be released at the begining of January 2021.

**Comment by robertbaldyga** [comment]
Multi-stream sequential cutoff is not included in 20.3.3. It's going to be part of the next major release, which is 20.12.
