### ISSUE TITLE
Wrong md5 checksum after interrupting flushing on xfs on Ubuntu 20.4.1

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#629]
## Description
After interrupting flushing operation on xfs filesystem on Ubuntu 20.4.1, file md5sum is different, than before. Doesn't matter if the operation is explicit or implicit, like interrupting core removal, which requires flushing.

## Expected Behavior
File checksum the same after interrupting flushing.

## Actual Behavior
File checksum is changed after interrupting flushing.

## Steps to Reproduce

1. Create a file and count its md5 checksum
2. Create xfs on core device
3. Start cache in WB mode, add core device and mount the exported object
4. Copy test file to mounted location
5. Check statistics (file data should be cached and "dirty")
6. Start flushing
7. Interrupt flushing
8. Count and compare md5 checksum

## Your Environment

* OpenCAS version (commit hash or tag): 20.12.0.420
* Operating System: Ubuntu 20.4.1
* Kernel version: 5.8.0 or 5.4.0
* Cache device type (model): Optane/NAND
* Core device type (model): HDD
* Cache configuration: 
* * Cache mode: WB

**Comment by arutk** [comment]
Problem has bin narrowed down to checksum mismatch on XFS without CAS layer. The below script triggers the issue on one of the affected systems. Quick attempt did not yield reproduction on other affected systems, some more investigation needs to be done in this regard.

`#!/bin/bash
set -e

DEV=/dev/sdc

MOUNT_POINT=/mnt/core
FILE=test.file
FPATH=${MOUNT_POINT}/$FILE
SIZE_MB=1024
WORKDIR=/root

echo "generating file..."
dd if=/dev/urandom bs=1M count=${SIZE_MB}  of=$WORKDIR/$FILE

echo "calculating csum ..."
CS=$(md5sum -b $WORKDIR/$FILE |  awk '{print $1;}')

unalias cp 2> /dev/null || true;

echo y | mkfs -t xfs  -f  $DEV

mkdir --parents /mnt/core/

mount  $DEV /mnt/core/
cp --force --recursive --dereference $WORKDIR/$FILE $FPATH
umount $DEV

for i in $(seq 10); do
        echo "iteration $i/10"
        mount  $DEV /mnt/core/
        CS2=$(md5sum -b $FPATH |  awk '{print $1;}');
        umount $DEV
        if [ "$CS2" != "$CS" ]; then
                echo "checksum mismatch"
                exit 1;
        fi
done

echo "OK"`

**Comment by arutk** [comment]
Problem outside CAS
