### ISSUE TITLE
device /dev/cas_ctrl not found after reboot

### ISSUE THREAD

**Issue by abolfazlmarj** [Open-CAS/open-cas-linux#645]
## Description

After installing open-cas-linux-v20.03.3 and rebooting, the device /dev/cas_ctrl was not found and as a result the OS (ubuntu-server 18.04 on Virtual Machine Manager 1.5.1) can not boot successfully.
I have also seen this error before, when I installed open-cas-linux, used it, and rebooted several times (about 10 times). Sometimes this problem occurs when the operating system boots.

## Expected Behavior

modules load and ubuntu-server boot successfully

## Actual Behavior

OS can not boot (device /dev/cas_ctrl not found)

## Steps to Reproduce

1. install open-cas-linux-v20.03.3 on ubuntu-server 18.04
2. reboot for several times

## Logs

...

The start-up result is RESULT.
Jan 20 14:17:44 ab_server systemd-udevd[458]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 20 14:17:44 ab_server kernel: random: crng init done
Jan 20 14:17:44 ab_server kernel: random: 7 urandom warning(s) missed due to ratelimiting
Jan 20 14:17:44 ab_server kernel: snd_hda_codec_generic hdaudioC0D0: autoconfig for Generic: line_outs=1 (0x3/0x0/0x0/0x0/0x0) type:line
Jan 20 14:17:44 ab_server kernel: snd_hda_codec_generic hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
Jan 20 14:17:44 ab_server kernel: snd_hda_codec_generic hdaudioC0D0:    hp_outs=0 (0x0/0x0/0x0/0x0/0x0)
Jan 20 14:17:44 ab_server kernel: snd_hda_codec_generic hdaudioC0D0:    mono: mono_out=0x0
Jan 20 14:17:44 ab_server kernel: snd_hda_codec_generic hdaudioC0D0:    inputs:
Jan 20 14:17:44 ab_server kernel: snd_hda_codec_generic hdaudioC0D0:      Line=0x5
Jan 20 14:17:44 ab_server systemd[1]: Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
 Subject: Unit systemd-rfkill.socket has finished start-up
 Defined-By: systemd
 Support: http://www.ubuntu.com/support
 
 Unit systemd-rfkill.socket has finished starting up.
 
 The start-up result is RESULT.
Jan 20 14:17:44 ab_server systemd-udevd[454]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 20 14:17:44 ab_server systemd[1]: Reached target Sound Card.
 Subject: Unit sound.target has finished start-up
 Defined-By: systemd
 Support: http://www.ubuntu.com/support
 
 Unit sound.target has finished starting up.
 
 The start-up result is RESULT.
Jan 20 14:18:14 ab_server casctl[433]: casadm error: Device /dev/cas_ctrl not found
Jan 20 14:18:14 ab_server systemd[1]: open-cas.service: Main process exited, code=exited, status=1/FAILURE
Jan 20 14:18:14 ab_server systemd[1]: open-cas.service: Failed with result 'exit-code'.
Jan 20 14:18:14 ab_server systemd[1]: Failed to start opencas initialization service.
 Subject: Unit open-cas.service has failed
 Defined-By: systemd
 Support: http://www.ubuntu.com/support
 
 Unit open-cas.service has failed.
 
 The result is RESULT.
Jan 20 14:18:14 ab_server systemd[1]: Dependency failed for Local File Systems.
 Subject: Unit local-fs.target has failed
 Defined-By: systemd
 Support: http://www.ubuntu.com/support
 
 Unit local-fs.target has failed.
 
 The result is RESULT.
Jan 20 14:18:14 ab_server systemd[1]: local-fs.target: Job local-fs.target/start failed with result 'dependency'.
Jan 20 14:18:14 ab_server systemd[1]: local-fs.target: Triggering OnFailure= dependencies.
Jan 20 14:18:14 ab_server systemd[1]: Dependency failed for Local File Systems (Pre).
 Subject: Unit local-fs-pre.target has failed
 Defined-By: systemd
 Support: http://www.ubuntu.com/support
 
 Unit local-fs-pre.target has failed.
 
 The result is RESULT.
Jan 20 14:18:14 ab_server systemd[1]: local-fs-pre.target: Job local-fs-pre.target/start failed with result 'dependency'.
Jan 20 14:18:14 ab_server systemd[1]: open-cas.service: Triggering OnFailure= dependencies.
Jan 20 14:18:14 ab_server systemd[1]: Stopped target System Time Synchronized.
 Subject: Unit time-sync.target has finished shutting down
 Defined-By: systemd
 Support: http://www.ubuntu.com/support
 
Unit time-sync.target has finished shutting down.
Jan 20 14:18:14 ab_server systemd[1]: Stopped target Local Encrypted Volumes.
Subject: Unit cryptsetup.target has finished shutting down
Defined-By: systemd
Support: http://www.ubuntu.com/support

...

## Your Environment

* OpenCAS version (commit hash or tag): v20.3.3
* Operating System: ubuntu-server 18.04
* Kernel version: Linux 4.15.0-132-generic
* Virtual Machine Manager version: 1.5.1

**Comment by rafalste** [comment]
Hey @abolfazlmarj , thank you for filing the issue!
I need a few more information to better understand what may happen there:

1. Is your OS booting normally despite the error, or is it finishing in a different state (like emergency/rescue target) or hangs etc.?
2. When you reboot again after the issue, is it booting normally or the problem remains unless you do something?
3. What is the output of `find /lib/modules/ -name "cas_*.ko"`?
4. What is the output of relevant part of `dmesg` when this happens?
5. When it happens, can you load modules manually (`modprobe cas_disk; modprobe cas_cache`)?
6. What is the output of `modinfo cas_disk cas_cache`?

**Comment by abolfazlmarj** [comment]
> Hey @abolfazlmarj , thank you for filing the issue!
> I need a few more information to better understand what may happen there:
> 
> 1. Is your OS booting normally despite the error, or is it finishing in a different state (like emergency/rescue target) or hangs etc.?
> 2. When you reboot again after the issue, is it booting normally or the problem remains unless you do something?
> 3. What is the output of `find /lib/modules/ -name "cas_*.ko"`?
> 4. What is the output of relevant part of `dmesg` when this happens?
> 5. When it happens, can you load modules manually (`modprobe cas_disk; modprobe cas_cache`)?
> 6. What is the output of `modinfo cas_disk cas_cache`?

Hi @rafalste , thanks for your attention
1. OS can't booting normally and it is finishing in emergency mode.
2. Rebooting will repeat the problem unless I disable the modules (systemctl disable open-cas) in an emergency then reboot the system and `make` and `make install` open-cas-linux after the OS boot normally. When I did these things open-cas-linux was installed and running correctly, but the problem can be repeated after a few days (Includes a number of on and off the system). I have no idea why this is happening because everything is working properly before this problem occurs but it may happen the next time I turn on the system.
3. In emergency mode: Nothing
4. There isn't any message relevant to open-cas
5. In emergency mode: `modprobe cas_disk`  ->  Module cas_disk not found in directory /lib/modules/4.15.0-128-generic
6. In emergency mode: `modinfo cas_disk`  ->  Module cas_disk not found

**Comment by rafalste** [comment]
Hi @abolfazlmarj ,
is there any chance that you've upgraded your kernel just before the failing reboot? If you do, our kernel modules won't be loaded by the new kernel (as you wrote - you need to compile the modules sources against the current kernel and install them again).
Also in an emergency mode you probably won't have your filesystems mounted, so please mount all of them or reboot into normal mode and before you install open-cas again, do `find /lib/modules/ -name "cas_*.ko"` There you should see your CAS modules placed in your relevant kernel version directory. Please make sure that the directory matches the kernel version you are running.

**Comment by rafalste** [comment]
> Is there any way to fix the problem other than preventing the kernel upgrades or do installation again after upgrade?

@abolfazlmarj there is a way actually. We have a script which will create deb packages. There is a DKMS support, so modules will be automatically rebuilt after kernel upgrade. To generate those debs simply run:
`make deb`
then install two .deb packages (with utils and modules) located in `packages/` directory:
`apt install ./packages/open-cas-linux*.deb`

You may also need to install additional dependencies:
`apt install debhelper devscripts dkms`

**Comment by abolfazlmarj** [comment]
Hi @rafalste 
I installed the dependencies, but for me, in addition to what you said, there was another need.
`apt install libelf-dev`
Then I did the other commands and the packages were installed successfully.
Thanks for your help and please close this issue.
