### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by jonggyup** [Open-CAS/open-cas-linux#652]
## Question

I received the following configruation error.
Is there anyone who knows how to solve this?

\Preparing configuration
ERROR! Following steps failed while preparing config:
1_bio_dev.conf
1_bdev_lookup.conf
1_bio_iter.conf
1_bio_flags.conf
1_blk_end_req.conf
1_dentry.conf
1_flush_flag.conf
1_global_page_state.conf
1_hlist.conf
1_inode.conf
1_bio_clone.conf
1_bio_err.conf
1_munmap.conf
1_queue_limits.conf
1_bio_discard.conf
1_queue_lock.conf
1_vmalloc.conf
1_write_flag.conf
2_bio_cmpl.conf
2_queue_write.conf
2_bio_barrier.conf
1_generic_acct.conf
1_submit_bio.conf

## Your Environment

* OpenCAS version (commit hash or tag): af664f9917017ae8184393fe73ff39f6d7477067
* Operating System: Ubuntu
* Kernel version: 5.4.0-60-generic

**Comment by mmichal10** [comment]
Hi @jonggyup,

can you share the logs? For each step which failed you can find them at `open-cas-linux/configure.d/.{config_file}.log` where {config_file} is a name of a step.

**Comment by jonggyup** [comment]
The configuration problem has occured because of the gcc version.
The error was derived from "-fstack-protector-strong"
And, this was merged into GCC version 4.9; 4.8.x does not support it.
By upgrading my gcc version, I could successfully configure.
Thank you so much.
