### ISSUE TITLE
System crash if seq-cutoff threshold equal request_size in ioclassification

### ISSUE THREAD

**Issue by khristenkovladimir** [Open-CAS/open-cas-linux#663]
## Description
System crash when fio test is finished and seq-cutoff threshold equal request_size in ioclassification

## Steps to Reproduce

1. Create wo cache
2.  casadm --io-class --load-config --cache-id 1 -f /etc/opencas/ioclass.csv 
```
cat /etc/opencas/ioclass.csv
IO class id,IO class name,Eviction priority,Allocation
0,unclassified,255,0
1,request_size:le:8192,255,1
```
3. casadm -X -n seq-cutoff -i 1 -j 1 -p always -t 8
4. run fio test
`fio --name=nvme --numjobs=6 --iodepth=4 --bs=8k --rw=randwrite --ioengine=libaio --direct=1 --group_reporting=1 --filename=/dev/cas1-1 --runtime=10 --time_based=1 --filesize=1G`

## Logs

https://user-images.githubusercontent.com/11570512/106160441-7f10f480-618e-11eb-9642-69dcc918c376.mp4
dump file: https://drive.google.com/file/d/1eVwUfnfjbV47VOEDVBMt1FI5sLp685c4/view?usp=sharing

## Your Environment

* OpenCAS version (commit hash or tag): 20.12.0.0438.master
* Operating System: CentOS Linux release 8.3.2011
* Kernel version: 4.18.0-240.10.1
* Cache configuration:
* * Cache mode: (default: wo)
* * Cache line size: (default: 4)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: always)

**Comment by mmichal10** [comment]
Hi @khristenkovladimir 

we are investigating your issue
