### ISSUE TITLE
bcache vs. flash cache vs. open-cas

### ISSUE THREAD

**Issue by jonggyup** [Open-CAS/open-cas-linux#667]
What's the main difference among bcache, flash cache, and open-cas?

**Comment by rafalste** [comment]
Hey @jonggyup,
we are currently working on a detailed comparison of OpenCAS to other popular caching solutions, which will be available in our documentation hopefully pretty soon.

But in the meantime, I can share with you some knowledge on this topic that we gathered some time ago. Those might not be up to date as we put those together about two years ago for our internal use, but maybe you'll find something useful there:

. | OpenCAS | bcache | dm-cache | flashcache
--- | --- | --- | --- | ---
I/O classification | Yes | No | No | No
Cache line size | 4 (default), 8, 16, 32, 64 [KiB] | matching core block size (4KB default) | 32KB - 1GB (%32KB) | 4KB
Cache modes | Write-Through (default),<br />Write-Back,<br />Write-Around,<br />Write-Invalidate,<br />Write-Only,<br />Pass-Through | Write-Through (default),<br />Write-Back,<br />Write-Around,<br />Pass-Through | Write-Through (Red Hat default),<br />Write-Back (originally default),<br />Pass-Through | Write-Through (default),<br />Write-Back,<br />Write-Around,<br />Write-Only
Cache replacement policies | Separated policies for:<br />- promotion: always (default), nhit,<br />- cleaning: ALRU (default), ACP, NOP,<br />- eviction: LRU. | LRU (default), FIFO, random | SMQ (default), MQ, cleaner | FIFO (default), LRU
Sequential data cutoff | full (default), always, never (+ threshold setting) | yes (default), no (+ threshold setting) | yes (+ threshold setting) | no (default), yes (+ threshold setting)
Max number of backend storage devices per cache instance | 4096 | ?? | 1 | 1

And please have in mind, that this is not an official comparison - just our old internal research.

**Comment by jonggyup** [comment]
Thank you very much. It is very helpful.

**Comment by jiaohaolin** [comment]
> 

hi @rafalste 
where can i see this article？could you share the atricle please?

**Comment by rafalste** [comment]
Hi @jiaohaolin,
those values above were gathered mostly from the documentation of those projects, not a single article.
There is a similar question here: https://github.com/Open-CAS/open-cas-linux/issues/1221

But as I mentioned - as of today, those might be outdated, cause we never refreshed this in the end.
