### ISSUE TITLE
opencas python file is uses python3 features breaking specfile for CentOS 7

### ISSUE THREAD

**Issue by justinvreeland** [Open-CAS/open-cas-linux#670]
## Description

`util/opencas.py` uses python3 specific features but the specfile template used for `make rpm` doesn't set the python version to 3.

## Expected Behavior
An RPM should've been created.

## Actual Behavior

The following error was printed:

```
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Compiling /tmp/opencas-pckgen.5L0myTP7K5/rpmbuild/BUILDROOT/open-cas-linux-20.12.0.0438.release-1.el7.x86_64/lib/opencas/opencas.py ...
  File "/lib/opencas/opencas.py", line 182
    raise ValueError(f"Given path {path} isn't correct by-id path.")
                                                                  ^
SyntaxError: invalid syntax

error: Bad exit status from /var/tmp/rpm-tmp.pCaBTE (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.pCaBTE (%install)
ERROR: pckgen: couldn't create RPM packages
make: *** [rpm] Error 1

```
## Steps to Reproduce

on centos-7
1. clone
2. update submodules
3. ./configure
4. make rpm

## Context

build a package for open-cas-linux

## Possible Fix

Add `%global __python %{__python3}` to the specfile

## Your Environment

* OpenCAS version (commit hash or tag): only checked v20.12 and master but any with the python f-string will have this problem 
* Operating System: CentOS-7

**Comment by rafalste** [comment]
Hey @justinvreeland , thanks for filing this issue!
I'll look at it closely and try to reproduce this but, in the meantime, can you confirm that your possible fix resolve the problem in your case?

**Comment by justinvreeland** [comment]
Adding it allows the package to be built on CentOS 7, not sure what potential implications it would have for other RPM based distros/versions.
