### ISSUE TITLE
Using ramdisk as a cache doesn't work

### ISSUE THREAD

**Issue by jonggyup** [Open-CAS/open-cas-linux#679]
## Question

I am trying to set up a cache using ramdisk (i.e. /dev/ram0)

But '$ casadm -S -d /dev/ram0 -i 1' returns "please use correct by-id path to the device /dev/ram0.'

Using hwinfo --disk, I realized the ramdisk doesn't have by-id path.

Do you have an idea?

I used '$ modprobe -brd rd_nr=1 rd_size=....' to create the ram block device

**Comment by katlapinka** [comment]
Hello @jonggyup,
Due to our latest changes you have to use a full by-id path for all devices. In case there is no such path for a device, you have to create a link for it, e.g.:

> ln -s /dev/ram0 /dev/disk/by-id/ramdisk0

I hope it will help you resolve this issue.

**Comment by katlapinka** [comment]
We'll update the documentation regarding this issue.

**Comment by jonggyup** [comment]
The link trick works well. Thank you.
