### ISSUE TITLE
is open-cas-linux support spdk with spdk

### ISSUE THREAD

**Issue by perrynzhou** [Open-CAS/open-cas-linux#718]
we has 2 nvmes disk,we want't using that to build open-cas as cache and disk,is hash way to support nvme with spdk framework?if yes,how to deployment？

**Comment by rafalste** [comment]
Hi @perrynzhou,
if you are looking for OCF support in SPDK, it is already partially implemented. There are two places in SPDK's documentation, where you can find some useful information about OCF:
https://spdk.io/doc/bdev.html#bdev_config_cas
https://spdk.io/doc/jsonrpc.html#rpc_bdev_ocf_create (and further methods)

Currently there are four methods implemented:
```
bdev_ocf_create
bdev_ocf_delete
bdev_ocf_get_stats
bdev_ocf_get_bdevs
```
but there are plenty more on the go, including cache mode switching method which is currently in the review process.

**Comment by rafalste** [comment]
Hi @perrynzhou,
I will close this issue as I think there is nothing more to add to it right now, but if you have any additional concerns, please feel free to reopen.
