### ISSUE TITLE
make uninstall fails if /etc/opencas/opencas.conf is removed

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#734]
## Description
Uninstallation is interrupted if opencas.conf is removed beforehand. In effect not all files are removed.

## Expected Behavior
Finished uninstallation

## Actual Behavior
Error No such file or directory

## Steps to Reproduce
1. Remove /etc/opencas/opencas.conf
2. Uninstall Open-CAS

## Context
I'm trying to achieve clean uninstallation

## Workaround
make install && make uninstall

## Logs
```[root@localhost open-cas-linux]# make uninstall
cd modules && make uninstall
make[1]: Entering directory '/root/open-cas-linux/modules'
Uninstalling Open-CAS modules
make[1]: Leaving directory '/root/open-cas-linux/modules'
cd casadm && make uninstall
make[1]: Entering directory '/root/open-cas-linux/casadm'
Uninstalling casadm
rm: cannot remove '/etc/opencas/opencas.conf': No such file or directory
make[1]: *** [Makefile:153: uninstall] Error 1
make[1]: Leaving directory '/root/open-cas-linux/casadm'
make: *** [Makefile:22: casadm] Error 2
```

## Your Environment
* OpenCAS version (commit hash or tag): any
* Operating System: any
* Kernel version: any

**Comment by katlapinka** [comment]
The workaround for this defect is to install and uninstall CAS using RPM packages - there is no such issue. To generate RPM packages use "make rpm" command at the open-cas-linux source directory.
