### ISSUE TITLE
Ramdisk as cache error

### ISSUE THREAD

**Issue by jianlenovo** [Open-CAS/open-cas-linux#738]
I followed the steps below for using ramdisk as the cache on Ubuntu 18.04, but it failed on the last step with the message about using correct by-id path. However, there is no id under /dev/disk/by-id/ for ramdisk.
1. modprobe brd rd_size=102400
2. casadm -S -d /dev/ram1 -i 2 , got error message "Please use correct by-id path to the device /dev/ram1."

**Comment by robertbaldyga** [comment]
See solution here https://github.com/Open-CAS/open-cas-linux/issues/679. It seems that documentation has not been updated yet.
