### ISSUE TITLE
Error stats did not increase as expected

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#748]
## Description
Test: test_soft_hot_plug_core
During workload test perform soft hot unplug on one core device. After that operations we've got:
Failed: There are some inconsistencies in error stats for Write-Only cache mode:
fio errors on unplugged core: 0, should be greater then 0
CAS errors on unlugged core: 0.0, should be greater then 0

## Expected Behavior
fio errors and CAS errors increased.

## Actual Behavior
fio errors and CAS errors haven't increased.

## Steps to Reproduce

1. Prepare cache and core devices
2. Start cache in Write-Only cache mode and add 2 cores
3. Run 'fio'
4. Soft hot unplug one core device[
5. Wait for 'fio' to finish...
6. Check for appropriate cache, core and fio errors

## Your Environment

* OpenCAS version : 21.03.0.0472.master
* Operating System: RHEL 8.3
* Kernel version: 4.18.0-240.el8.x86_64
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):

**Comment by karolinavelkaja** [comment]
logs attached:
[test_soft_hot_plug_core_cas213.zip](https://github.com/Open-CAS/open-cas-linux/files/6183807/test_soft_hot_plug_core_cas213.zip)

**Comment by katlapinka** [comment]
There was an issue with the test.

**Comment by karolinavelkaja** [comment]
Test fix for longer io in test: https://github.com/Open-CAS/open-cas-linux/pull/781
