### ISSUE TITLE
Core max size?

### ISSUE THREAD

**Issue by alxtrl** [Open-CAS/open-cas-linux#766]
## Question
I would like to known if there's some kind of limits about the size of a core device

## Motivation
I added a core device of 60TB and the output of 'casadm -P -i 1 -j 1' reports:
Core Size            15626993664 [4KiB Blocks] / 10460.25 [GiB]

## Your Environment

* OpenCAS version (commit hash or tag): 20.12.2.0444
* Operating System: Oracle Linux 8.3
* Kernel version: 4.18.0-240.15.1
* Cache device type (NAND/Optane/other): Intel Optane SSD DC P4800X Series 
* Core device type (HDD/SSD/other): RAID-6 Volume
* Cache configuration: WT 4K
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by robertbaldyga** [comment]
Hi @alxtrl. It looks like there is a bug in blocks->GiB calculation code, as 15626993664 blocks is no less no more 59612.25 GiB.
We do not set any additional limit on core device size. Open CAS should work with any core device size Linux kernel is able to handle.

Thanks for reporting this!

**Comment by alxtrl** [comment]
Hi Robert, thanks for your prompt reply, I have verified that the actual size of the volume is 64TB

**Comment by robertbaldyga** [comment]
15626993664 blocks = 58.22 TiB = 64TB, so it looks like the size is ok. The problem is just with printing the right value in GiB.
