### ISSUE TITLE
Sporadical problem with adding core device to the cache instance

### ISSUE THREAD

**Issue by katlapinka** [Open-CAS/open-cas-linux#808]
## Description
There is a problem to add a core to the cache which results in error message like below:

> Error while adding core device to cache instance 1
> Cannot allocate memory

Problem occurs on RHEL 7.x

## Expected Behavior
Core should be added successfully

## Actual Behavior
This is impossible to add core

## Your Environment

* OpenCAS version (commit hash or tag):  21.03.0.0496.release
* Operating System: RHEL 7.9
* Kernel version: 3.10.0-1160.el7.x86_64
* Cache device type (NAND/Optane/other): Optane

**Comment by Ostrokrzew** [comment]
Looks like the problem only occurs when the `scsi_debug` module with custom parameters was loaded previously but not with scsi device but physical device. Investigation is in progress.
