### ISSUE TITLE
Timeout occurred while trying to plug disk

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#854]
## Description

Test: test_recovery_unplug_cache_raw
Failure:
Plug missing cache device.
    Exception: Timeout occurred while trying to plug disk.

## Steps to Reproduce

1. Prepare devices
2. Create test files.
3. Start cache and add core.
4. Copy file to CAS.
5. Unplug cache device.
6. Stop cache.
7. Plug missing cache device.
    Exception: Timeout occurred while trying to plug disk.

## Your Environment

* OpenCAS version (commit hash or tag): eaa2f54
* Operating System: Centos 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by Deixx** [comment]
Non-CAS related. Looks like this issue was connected to a specific platform.
