### ISSUE TITLE
Incorrect file md5 sum after interrupted core removal

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#855]
## Description

After interrupting core removal operation, the test file md5 sum was incorrect. The file was on xfs filesystem.
Similar test with interrupting cache stop operation passed.

## Steps to Reproduce

1. Start a cache in WB mode
2. Set the cleaning policy to nop
3. Create a xfs filesystem on a core device
4. Add the core to the cache
5. Mount the exported object
6. Create a big test file (NOT in the mounted location) and count its md5 sum
7. Copy the test file to the mounted location
8. Call 'sync' and unmount the filesystem
8. Run 'remove core' command
9. Wait for progress to reach 70% (flushing data) and then interrupt the removal
10. Re-mount the filesystem and call 'sync'
11. Count the test file md5 sum on mounted filesystem

## Your Environment

* OpenCAS version (commit hash or tag): 8c2ab0fac60656cff466151b47378d6c647c4992
* Operating System: Centos 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other): Optane
* Core device type (HDD/SSD/other): SATA SSD
* Cache configuration:
* * Cache mode: (default: wt) wb
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru) nop
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by arutk** [comment]
Seems to be caused by https://github.com/Open-CAS/open-cas-linux/issues/866
