### ISSUE TITLE
FIO IO error - cache line size 4k, XFS

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#856]
## Description

Test checks different fio IO engines. Issues occur only with configuration from title, regardless of IO engine used. Noticed in WB, WA and WT mode.

## Actual Behavior

FIO ended with error:
`fio: pid=0, err=5/file:filesetup.c:249, func=fsync, error=Input/output error`

## Steps to Reproduce

1. Start a cache with 4k cache line size
2. Add a core
3. Create XFS on the exported object
4. Mount the filesystem
5. Run fio (engines can be different, CPUs correspond to cache device numa node):
`fio --eta=always --output-format=json --output=fio_output --group_reporting --direct=1 --ioengine=posixaio --runtime=900 --time_based --readwrite=randrw --rwmixwrite=30 --verify=pattern --verify_pattern=0x74F81AC766A4BC7E4327056B74098EA9 --do_verify=1 --cpus_allowed=0-17,36-53 --cpus_allowed_policy=split --size=1073741824 --filename=/mnt/test/fio_test --name=fio`

## Your Environment

* OpenCAS version (commit hash or tag): eaa2f54ec160539b4fab4815df254da4c1807908
* Operating System: Centos 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other): Optane
* Core device type (HDD/SSD/other): HDD
* Cache configuration:
* * Cache mode: differrent
* * Cache line size: 4k
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by arutk** [comment]
Caused by https://github.com/Open-CAS/open-cas-linux/issues/866
