### ISSUE TITLE
Pinned IO class can be evicted

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#860]
## Description

The pinned IO class does not occupy whole cache capacity. Test was using IO classes differentiated by file size.

## Expected Behavior

Pinned IO class occupying whole cache

## Actual Behavior

Pinned IO class occupies ~76% cache space

## Steps to Reproduce

1. Start a cache in WB mode and add a core with ext4 filesystem
2. Load IO class config with pinned IO class configured. Config used:
```
IO class id,IO class name,Eviction priority,Allocation
15,file_size:le:1048576&done,,1
16,file_size:le:4194304&done,1,1
17,file_size:le:16777216&done,2,1
18,file_size:le:67108864&done,3,1
19,file_size:le:268435456&done,4,1
```
3. Mount the core filesystem
4. Write files for pinned IO class on mounted filesystem to fill whole cache
5. Write files for all the other IO classes
6. Check the pinned IO class occupancy

## Logs

Stats for pinned IO class after test:
```
IO class ID       15
IO class name     file_size:le:1048576&done
Eviction priority Pinned
Max size          100%

+==================+=======+=======+=============+
| Usage statistics | Count |   %   |   Units     |
+==================+=======+=======+=============+
| Occupancy        | 45931 |  76.4 | 4KiB Blocks |
| Clean            | 45931 | 100.0 | 4KiB Blocks |
| Dirty            |     0 |   0.0 | 4KiB Blocks |
+==================+=======+=======+=============+

+======================+========+=======+==========+
| Request statistics   | Count  |   %   | Units    |
+======================+========+=======+==========+
| Read hits            |  45888 |  34.9 | Requests |
| Read partial misses  |      0 |   0.0 | Requests |
| Read full misses     |     43 |   0.0 | Requests |
| Read total           |  45931 |  35.0 | Requests |
+----------------------+--------+-------+----------+
| Write hits           |  44800 |  34.1 | Requests |
| Write partial misses |      0 |   0.0 | Requests |
| Write full misses    |   1263 |   1.0 | Requests |
| Write total          |  46063 |  35.1 | Requests |
+----------------------+--------+-------+----------+
| Pass-Through reads   |  19605 |  14.9 | Requests |
| Pass-Through writes  |  19729 |  15.0 | Requests |
| Serviced requests    |  91994 |  70.0 | Requests |
+----------------------+--------+-------+----------+
| Total requests       | 131328 | 100.0 | Requests |
+======================+========+=======+==========+

+==================================+========+=======+=============+
| Block statistics                 | Count  |   %   |   Units     |
+==================================+========+=======+=============+
| Reads from core(s)               |  19648 |  18.5 | 4KiB Blocks |
| Writes to core(s)                |  86272 |  81.5 | 4KiB Blocks |
| Total to/from core(s)            | 105920 | 100.0 | 4KiB Blocks |
+----------------------------------+--------+-------+-------------+
| Reads from cache                 |  91776 |  50.3 | 4KiB Blocks |
| Writes to cache                  |  90731 |  49.7 | 4KiB Blocks |
| Total to/from cache              | 182507 | 100.0 | 4KiB Blocks |
+----------------------------------+--------+-------+-------------+
| Reads from exported object(s)    |  65536 |  33.3 | 4KiB Blocks |
| Writes to exported object(s)     | 131072 |  66.7 | 4KiB Blocks |
| Total to/from exported object(s) | 196608 | 100.0 | 4KiB Blocks |
+==================================+========+=======+=============+
```

## Your Environment

* OpenCAS version (commit hash or tag): eaa2f54ec160539b4fab4815df254da4c1807908
* Operating System: CentOS 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other): Optane
* Core device type (HDD/SSD/other): NAND SSD
* Cache configuration:
* * Cache mode: (default: wt) WB
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by mmkayPL** [comment]
The pinned ioclasses don't seem to be evicted in this scenario. Instead, in this testing scenario, some initial writes incorporating metadata are cached as part of the unclassified class and following that sequential cutoff seems to kick in and writes use the passthrough path. Executing the test again after turning off sequential cutoff fills up the pinned I/O class occupancy to 100%. The lowered initial occupancy is still visible for a single run of the test with sequential cutoff turned off, so this doesn't seem to be the whole reason for the behavior.

**Comment by Deixx** [comment]
Test passed with the following changes:
1. Disabled seq-cutoff
2. Allocation set to 0 for the Unclassified IO class
3. Core added after loading IO class configuration

2. and 3. prevent the unwanted caching of (meta)data when the core is added.
