### ISSUE TITLE
Kernel BUG during boot after dirty shutdown (cas_cache/src/ocf/ocf_lru.c:925!)

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#869]
## Description

Test prepares an exported object, starts IO and hard resets the platform. BUG occurs when the OS is booting.

## Steps to Reproduce

1. Prepare an exported object
2. Prepare a configuration file corresponding to the running CAS setup
3. Run an IO workload on the exported object 
4. Cut the power during the workload
5. Restore power, boot to OS

## Logs

[SerialLog_WFP-22_Ipmi.log](https://github.com/Open-CAS/open-cas-linux/files/6769166/SerialLog_WFP-22_Ipmi.log)

## Your Environment

* OpenCAS version (commit hash or tag): b488565e98041fe6978e1dab36cdfbd254209a65
* Operating System: Centos 7.9
* Kernel version: 5.10

**Comment by karolinavelkaja** [comment]
Issue occurred again with CAS 21.06.0.0530.master during test_stress_dirty_shutdown.
