### ISSUE TITLE
Occupancy for ioclass id exceeded specified occupancy

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#876]
## Description

Test sometimes fails (few test cases but rather without any pattern): 
test_ioclass_resize
test_ioclass_occupancy_directory_write
problem: "Occupancy for ioclass id exceeded"

> test_ioclass_resize[CacheLineSize.LINE_4KiB-25]		PASSED 
> test_ioclass_resize[CacheLineSize.LINE_4KiB-50]     PASSED 
> test_ioclass_resize[CacheLineSize.LINE_4KiB-70]     FAILED
> test_ioclass_resize[CacheLineSize.LINE_4KiB-100]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_8KiB-25]     PASSED 
> test_ioclass_resize[CacheLineSize.LINE_8KiB-50]     FAILED
> test_ioclass_resize[CacheLineSize.LINE_8KiB-70]     FAILED
> test_ioclass_resize[CacheLineSize.LINE_8KiB-100]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_16KiB-25]    FAILED
> test_ioclass_resize[CacheLineSize.LINE_16KiB-50]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_16KiB-70]    FAILED
> test_ioclass_resize[CacheLineSize.LINE_16KiB-100]   PASSED 
> test_ioclass_resize[CacheLineSize.LINE_32KiB-25]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_32KiB-50]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_32KiB-70]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_32KiB-100]   PASSED 
> test_ioclass_resize[CacheLineSize.LINE_64KiB-25]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_64KiB-50]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_64KiB-70]    PASSED 
> test_ioclass_resize[CacheLineSize.LINE_64KiB-100]   PASSED 

## Steps to Reproduce

Failures observed on both steps where occupancy is beeing checked but not simultaneously - step 11 **OR** 14.
Failures concatenated in one description:
1. Prepare CAS device
2. Disable udev
3. Prepare filesystem and mount /dev/cas1-1 at /tmp/cas1-1
4. Prepare test dirs
5. Remove old ioclass config
6. Add default ioclasses
7. Add directory for ioclass
8. Reset cache stats
9. Check initial occupancy
10. Perform IO with size equal to cache size
11. Check if the ioclass did not exceed specified occupancy
   Occupancy for ioclass id exceeded: 2. Limit: 260228.0 Blocks4096, actuall: 266776.0 Blocks4096
12. Resize ioclass from 10.0% to 50% cache occupancy
13. Perform IO with size equal to cache size
14. Check if the ioclass did not exceed specified occupancy
    Occupancy for ioclass id exceeded: 2. Limit: 1301136.0 Blocks4096, actuall: 1306624.0 Blocks4096

## Your Environment

* OpenCAS version (commit hash or tag):  21.06.0.0527.master
* Operating System: Centos 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by karolinavelkaja** [comment]
Reproduction on 21.06.0.0530.master

**Comment by Deixx** [comment]
Reproduction on 21.06.0.0534.master in test_ioclass_resize (test_ioclass_occupancy_directory_write passed)
