### ISSUE TITLE
IO classification by directory reclassification fails

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#889]
## Description

Tests:
test_ioclass_directory_dir_operations
test_ioclass_directory_file_operations

## Expected Behavior

Files should be reclassified to proper IO class after changing their paths and reading them. 

## Actual Behavior

After:
- renaming a classified dir to non-classified and reading all files within
- moving a file from a non-classified directory to a dir nested in a classified dir

occupancy doesn't meet expected values.

## Your Environment

* OpenCAS version (commit hash or tag): 21.06.0.0534.master b57a8bf
* Operating System: Centos 7.9
* Kernel version: 5.10

**Comment by karolinavelkaja** [comment]
Target to fix the issue: CAS v22.3

**Comment by arutk** [comment]
it's worth checking whether adding 1s delay after configuring IO classes helps

**Comment by karolinavelkaja** [comment]
test_ioclass_directory_file_operations already improved with the delay (within another PR) and works fine.
test_ioclass_directory_dir_operations needs some refactor/work

**Comment by karolinavelkaja** [comment]
Both tests work good. Issue not reproduced.
