### ISSUE TITLE
Slab kmalloc-2048 leak

### ISSUE THREAD

**Issue by lausaa** [Open-CAS/open-cas-linux#892]
## Description

CAS is used in our HDFS as datanode's cache disk. Recently, we encountered some OOM problems caused by the large allocation of kmalloc-2048.

## Expected Behavior

kmalloc-2048 could not need to allocate too large.

## Actual Behavior

With the IO running, the kmalloc-2048 allocation is growing more and more until the system OOM.
And if the IO stop, the kmalloc-2048 allocation will stop increasing.

## Steps to Reproduce

This problem happens occasionally, and I could not find how to reproduce.
But now I reserved a machine with problem used to debug.
So I can provide any information if it helps.
1. 
2.
3.
4.

## Logs

No error logs in /var/log/messages and dmesg and opencas.log.

\# cat /proc/meminfo
MemTotal:       263588420 kB
MemFree:        12139504 kB
MemAvailable:   60175732 kB
Buffers:         4297512 kB
Cached:         44090212 kB
SwapCached:            0 kB
Active:         113073788 kB
Inactive:       30906724 kB
Active(anon):   97731784 kB
Inactive(anon):  1950844 kB
Active(file):   15342004 kB
Inactive(file): 28955880 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                72 kB
Writeback:             0 kB
AnonPages:      95593120 kB
Mapped:           111896 kB
Shmem:           4089832 kB
Slab:           39722676 kB
SReclaimable:    5048432 kB
SUnreclaim:     34674244 kB
KernelStack:       30272 kB
PageTables:       204048 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    131794208 kB
Committed_AS:   103233404 kB
VmallocTotal:   34359738367 kB
VmallocUsed:    65422860 kB
VmallocChunk:   34294129876 kB
HardwareCorrupted:     0 kB
AnonHugePages:      2048 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:    36805832 kB
DirectMap2M:    149475328 kB
DirectMap1G:    83886080 kB

\# cat /proc/slabinfo
kmalloc-2048      17095284 17095380   2048   16    8 : tunables    0    0    0 : slabdata 5306368 5306368      0

## Your Environment

* OpenCAS version (commit hash or tag):
20.03.01.00000804
* Operating System:
CentOS 7.4
* Kernel version:
3.10.0-693.5.2.el7.x86_64
* Cache device type (NAND/Optane/other):
NAND
* Core device type (HDD/SSD/other):
HDD
* Cache configuration:
* * Cache mode: (default: wt)
wt
* * Cache line size: (default: 4)
4
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
acp
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

\# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 223.6G  0 disk
├─sda1        8:1    0     1G  0 part /boot
├─sda2        8:2    0    16G  0 part
└─sda3        8:3    0 206.6G  0 part /
sdb           8:16   0  12.8T  0 disk
└─sdb1        8:17   0  12.8T  0 part
  └─cas1-1  252:0    0  12.8T  0 disk /data0
sdc           8:32   0  12.8T  0 disk
└─sdc1        8:33   0  12.8T  0 part
  └─cas1-2  252:1    0  12.8T  0 disk /data1
sdd           8:48   0  12.8T  0 disk
└─sdd1        8:49   0  12.8T  0 part
  └─cas1-3  252:2    0  12.8T  0 disk /data2
sde           8:64   0  12.8T  0 disk
└─sde1        8:65   0  12.8T  0 part
  └─cas1-4  252:3    0  12.8T  0 disk /data3
sdf           8:80   0  12.8T  0 disk
└─sdf1        8:81   0  12.8T  0 part
  └─cas1-5  252:4    0  12.8T  0 disk /data4
sdg           8:96   0  12.8T  0 disk
└─sdg1        8:97   0  12.8T  0 part
  └─cas1-6  252:5    0  12.8T  0 disk /data5
sdh           8:112  0  12.8T  0 disk
└─sdh1        8:113  0  12.8T  0 part
  └─cas1-7  252:6    0  12.8T  0 disk /data6
sdi           8:128  0  12.8T  0 disk
└─sdi1        8:129  0  12.8T  0 part
  └─cas1-8  252:7    0  12.8T  0 disk /data7
sdj           8:144  0  12.8T  0 disk
└─sdj1        8:145  0  12.8T  0 part
  └─cas1-9  252:8    0  12.8T  0 disk /data8
sdk           8:160  0  12.8T  0 disk
└─sdk1        8:161  0  12.8T  0 part
  └─cas1-10 252:9    0  12.8T  0 disk /data9
sdl           8:176  0  12.8T  0 disk
└─sdl1        8:177  0  12.8T  0 part
  └─cas1-11 252:10   0  12.8T  0 disk /data10
sdm           8:192  0  12.8T  0 disk
└─sdm1        8:193  0  12.8T  0 part
  └─cas1-12 252:11   0  12.8T  0 disk /data11
sdn           8:208  0  12.8T  0 disk
└─sdn1        8:209  0  12.8T  0 part
  └─cas1-13 252:12   0  12.8T  0 disk /data12
sdo           8:224  0  12.8T  0 disk
└─sdo1        8:225  0  12.8T  0 part
  └─cas1-14 252:13   0  12.8T  0 disk /data13
sdp           8:240  0  12.8T  0 disk
└─sdp1        8:241  0  12.8T  0 part
  └─cas1-15 252:14   0  12.8T  0 disk /data14
sdq          65:0    0  12.8T  0 disk
└─sdq1       65:1    0  12.8T  0 part
  └─cas1-16 252:15   0  12.8T  0 disk /data15
sdr          65:16   0  12.8T  0 disk
└─sdr1       65:17   0  12.8T  0 part
  └─cas1-17 252:16   0  12.8T  0 disk /data16
sds          65:32   0  12.8T  0 disk
└─sds1       65:33   0  12.8T  0 part
  └─cas1-18 252:17   0  12.8T  0 disk /data17
sdt          65:48   0  12.8T  0 disk
└─sdt1       65:49   0  12.8T  0 part
  └─cas2-1  252:18   0  12.8T  0 disk /data18
sdu          65:64   0  12.8T  0 disk
└─sdu1       65:65   0  12.8T  0 part
  └─cas2-2  252:19   0  12.8T  0 disk /data19
sdv          65:80   0  12.8T  0 disk
└─sdv1       65:81   0  12.8T  0 part
  └─cas2-3  252:20   0  12.8T  0 disk /data20
sdw          65:96   0  12.8T  0 disk
└─sdw1       65:97   0  12.8T  0 part
  └─cas2-4  252:21   0  12.8T  0 disk /data21
sdx          65:112  0  12.8T  0 disk
└─sdx1       65:113  0  12.8T  0 part
  └─cas2-5  252:22   0  12.8T  0 disk /data22
sdy          65:128  0  12.8T  0 disk
└─sdy1       65:129  0  12.8T  0 part
  └─cas2-6  252:23   0  12.8T  0 disk /data23
sdz          65:144  0  12.8T  0 disk
└─sdz1       65:145  0  12.8T  0 part
  └─cas2-7  252:24   0  12.8T  0 disk /data24
sdaa         65:160  0  12.8T  0 disk
└─sdaa1      65:161  0  12.8T  0 part
  └─cas2-8  252:25   0  12.8T  0 disk /data25
sdab         65:176  0  12.8T  0 disk
└─sdab1      65:177  0  12.8T  0 part
  └─cas2-9  252:26   0  12.8T  0 disk /data26
sdac         65:192  0  12.8T  0 disk
└─sdac1      65:193  0  12.8T  0 part
  └─cas2-10 252:27   0  12.8T  0 disk /data27
sdad         65:208  0  12.8T  0 disk
└─sdad1      65:209  0  12.8T  0 part
  └─cas2-11 252:28   0  12.8T  0 disk /data28
sdae         65:224  0  12.8T  0 disk
└─sdae1      65:225  0  12.8T  0 part
  └─cas2-12 252:29   0  12.8T  0 disk /data29
sdaf         65:240  0  12.8T  0 disk
└─sdaf1      65:241  0  12.8T  0 part
  └─cas2-13 252:30   0  12.8T  0 disk /data30
sdag         66:0    0  12.8T  0 disk
└─sdag1      66:1    0  12.8T  0 part
  └─cas2-14 252:31   0  12.8T  0 disk /data31
sdah         66:16   0  12.8T  0 disk
└─sdah1      66:17   0  12.8T  0 part
  └─cas2-15 252:32   0  12.8T  0 disk /data32
sdai         66:32   0  12.8T  0 disk
└─sdai1      66:33   0  12.8T  0 part
  └─cas2-16 252:33   0  12.8T  0 disk /data33
sdaj         66:48   0  12.8T  0 disk
└─sdaj1      66:49   0  12.8T  0 part
  └─cas2-17 252:34   0  12.8T  0 disk /data34
sdak         66:64   0  12.8T  0 disk
└─sdak1      66:65   0  12.8T  0 part
  └─cas2-18 252:35   0  12.8T  0 disk /data35
nvme0n1     259:0    0   1.8T  0 disk
nvme1n1     259:1    0   1.8T  0 disk

\# casadm -P -i 1
Cache Id                  1
Cache Size                482473718 [4KiB Blocks] / 1840.49 [GiB]
Cache Device              /dev/nvme0n1
Core Devices              18
Inactive Core Devices     0
Write Policy              wt
Eviction Policy           lru
Cleaning Policy           acp
Promotion Policy          always
Cache line size           4 [KiB]
Metadata Memory Footprint 24.3 [GiB]
Dirty for                 0 [s] / Cache clean
Metadata Mode             normal
Status                    Running

\# casadm -P -i 2
Cache Id                  2
Cache Size                482473718 [4KiB Blocks] / 1840.49 [GiB]
Cache Device              /dev/nvme1n1
Core Devices              18
Inactive Core Devices     0
Write Policy              wt
Eviction Policy           lru
Cleaning Policy           acp
Promotion Policy          always
Cache line size           4 [KiB]
Metadata Memory Footprint 24.3 [GiB]
Dirty for                 0 [s] / Cache clean
Metadata Mode             normal
Status                    Running

\# casadm -L
type    id   disk           status    write policy   device
cache   1    /dev/nvme0n1   Running   wt             -
├core   1    /dev/sdb1      Active    -              /dev/cas1-1
├core   2    /dev/sdc1      Active    -              /dev/cas1-2
├core   3    /dev/sdd1      Active    -              /dev/cas1-3
├core   4    /dev/sde1      Active    -              /dev/cas1-4
├core   5    /dev/sdf1      Active    -              /dev/cas1-5
├core   6    /dev/sdg1      Active    -              /dev/cas1-6
├core   7    /dev/sdh1      Active    -              /dev/cas1-7
├core   8    /dev/sdi1      Active    -              /dev/cas1-8
├core   9    /dev/sdj1      Active    -              /dev/cas1-9
├core   10   /dev/sdk1      Active    -              /dev/cas1-10
├core   11   /dev/sdl1      Active    -              /dev/cas1-11
├core   12   /dev/sdm1      Active    -              /dev/cas1-12
├core   13   /dev/sdn1      Active    -              /dev/cas1-13
├core   14   /dev/sdo1      Active    -              /dev/cas1-14
├core   15   /dev/sdp1      Active    -              /dev/cas1-15
├core   16   /dev/sdq1      Active    -              /dev/cas1-16
├core   17   /dev/sdr1      Active    -              /dev/cas1-17
└core   18   /dev/sds1      Active    -              /dev/cas1-18
cache   2    /dev/nvme1n1   Running   wt             -
├core   1    /dev/sdt1      Active    -              /dev/cas2-1
├core   2    /dev/sdu1      Active    -              /dev/cas2-2
├core   3    /dev/sdv1      Active    -              /dev/cas2-3
├core   4    /dev/sdw1      Active    -              /dev/cas2-4
├core   5    /dev/sdx1      Active    -              /dev/cas2-5
├core   6    /dev/sdy1      Active    -              /dev/cas2-6
├core   7    /dev/sdz1      Active    -              /dev/cas2-7
├core   8    /dev/sdaa1     Active    -              /dev/cas2-8
├core   9    /dev/sdab1     Active    -              /dev/cas2-9
├core   10   /dev/sdac1     Active    -              /dev/cas2-10
├core   11   /dev/sdad1     Active    -              /dev/cas2-11
├core   12   /dev/sdae1     Active    -              /dev/cas2-12
├core   13   /dev/sdaf1     Active    -              /dev/cas2-13
├core   14   /dev/sdag1     Active    -              /dev/cas2-14
├core   15   /dev/sdah1     Active    -              /dev/cas2-15
├core   16   /dev/sdai1     Active    -              /dev/cas2-16
├core   17   /dev/sdaj1     Active    -              /dev/cas2-17
└core   18   /dev/sdak1     Active    -              /dev/cas2-18

**Comment by mmichal10** [comment]
Hi @lausaa,

thank you for reporting this issue. We tested CAS 20.3.1 and 21.3.2 versions and in both cases we were unable to find any memory leaks during the IO. But we are very concerned about this bug and since you mentioned `But now I reserved a machine with problem used to debug`  I want to ask whether it would be possible to for you to do some testing on your machine? To detect memory leaks we are using a tool call [KEDR](https://github.com/euspectre/kedr). If you don't mind our team will be happy to provide you all the necessary instructions.

**Comment by lausaa** [comment]
Thank you @mmichal10 for introducing this tool. I have installed KEDR on my machine. I run the commands as follows:
1. kedr start cas_cache;
2. modprobe cas_cache;
3. start cache instance and mount them;
4. write some files;
5. unmount the CAS devices and stop cache instance;
6. rmmod cas_cache;
At last the KEDR's log is dumped to the dmesg.
Is this a normal way to use it? If so, I should reload all machines with KEDR, however I am not allowed to do this...
The probability of the bug is low(< 1% per week, I have hundreds of machines), and when the bug is happening, if the cas_cache is reloaded, the scene will be lost.
Is there any other way to use it when the cas_cache is running?

**Comment by mmichal10** [comment]
`Is this a normal way to use it? If so, I should reload all machines with KEDR, however I am not allowed to do this...`
You are using it in a correct way, but KEDR as a debug tool it might have a great impact on CAS performance so it is unrecommended to use it in production environment. 

I suspect CAS has a memory leak somewhere in an IO path. We were not able to find it in our environment so it might by related to your workload and configuration.  Do you have resources to do the testing with KEDR in the debug env with a similar setup and workload to the production env? For a longer period of time - at lest one week. 

In meantime I would like to recommend you using newer version of Open CAS Linux. Next week we expect CAS v21.6 to be released. It includes a lot of fixed bugs and vast performance improvements.

**Comment by lausaa** [comment]
>Do you have resources to do the testing with KEDR in the debug env with a similar setup and workload to the production env?

OK. I will do the testing today.

**Comment by mmichal10** [comment]
@lausaa how did the testing go?

**Comment by lausaa** [comment]
> @lausaa how did the testing go?

@mmichal10 Sorry I did not concern ths issue recently.
The test seems OK now.
And with the decrease of IO pressure, none of the hundreds of machines happened the leak.
I will continue to test this version for a period of time. On the other hand, as you recommended, we plan to test and upgrade to v21.6 later.

**Comment by mmichal10** [comment]
Hello @lausaa 

> The test seems OK now.

I'm really glad to hear that. Would you mind closing the issue for the time being? In case if you encounter the bug again please let us know.
