### ISSUE TITLE
"Cannot resolve path to cache / Safe C lib error" after adding cache device

### ISSUE THREAD

**Issue by rafalste** [Open-CAS/open-cas-linux#912]
## Description
`casadm -L` displays following error message:
```
WARNING: Cannot resolve path to cache. By-id path will be shown for that cache.
Safe C lib error
strncpy_s: slen is zero (401)
casadm(+0x912b)[0x55f2758b312b]
casadm(+0x91d3)[0x55f2758b31d3]
casadm(+0xd446)[0x55f2758b7446]
casadm(+0x1680a)[0x55f2758c080a]
casadm(+0x15f13)[0x55f2758bff13]
casadm(+0xc2e5)[0x55f2758b62e5]
casadm(+0xe7c3)[0x55f2758b87c3]
/lib64/libpthread.so.0(+0x814a)[0x7f9b10a4914a]
/lib64/libc.so.6(clone+0x43)[0x7f9b1077af23]
```
This error is rather rare as it happened to me once in particular situation when the nvme controller was switched back and forth from kernel to SPDK igb_uio driver a couple of times. After reboot everything worked fine and I couldn't reproduce the issue even after many driver replacements, so I suppose this was not the reason of this problem.
As a clarification, when this happens:
- controllers were pinned to kernel driver (not igb_uio)
- cache was added with by-id path
- by-id path (as well as /dev/nvme... path) to cache device was present and accessible

I'm just leaving it here in case anyone stumble upon this in the future.

## Steps to Reproduce
It is not known in what circumstances this occurs, but when it does, it is enough to just add cache device and list caches:
1. `casadm -S -d /dev/disk/by-id/...`
2. `casadm -L`

## Your Environment
* OpenCAS version (commit hash or tag): 21.06.0.0537.master
* Operating System: CentOS 8
* Kernel version: 4.18.0-240.22.1.el8_3.x86_64
* Cache device type (NAND/Optane/other): Optane P4800X
* Cache configuration: default

**Comment by kmajzero** [comment]
This output may happen when a string parameter given for a *printf function is a zero length string.

**Comment by jfckm** [comment]
Closing because of very-low exposure and severity.
