### ISSUE TITLE
20.04.1-Ubuntu generated_defines.h not found

### ISSUE THREAD

**Issue by dalingng** [Open-CAS/open-cas-linux#937]
cat /proc/version
Linux version 5.11.0-27-generic (buildd@lcy01-amd64-019) (gcc (Ubuntu 9.3.0-17ubuntu1 - 20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021

root@lok-PowerEdge-R620:~/work/open-cas-linux# make
cd modules && make
make[1]: 进入目录“/root/work/open-cas-linux/modules”
make[2]: 进入目录“/root/work/open-cas-linux/ocf”
make[3]: 进入目录“/root/work/open-cas-linux/ocf”
make[3]: 对“distcleandir”无需做任何事。
make[3]: 离开目录“/root/work/open-cas-linux/ocf”
make[2]: 离开目录“/root/work/open-cas-linux/ocf”
make[2]: 进入目录“/root/work/open-cas-linux/ocf”
make[3]: 进入目录“/root/work/open-cas-linux/ocf”
make[3]: 对“distcleandir”无需做任何事。
make[3]: 离开目录“/root/work/open-cas-linux/ocf”
make[2]: 离开目录“/root/work/open-cas-linux/ocf”
cd "/lib/modules/"5.11.0-27-generic"/build" && make M=/root/work/open-cas-linux/modules modules
make[2]: 进入目录“/usr/src/linux-headers-5.11.0-27-generic”
  CC [M]  /root/work/open-cas-linux/modules/cas_cache/context.o
In file included from /root/work/open-cas-linux/modules/cas_cache/ocf_env.h:10,
                 from /root/work/open-cas-linux/modules/cas_cache/cas_cache.h:10,
                 from /root/work/open-cas-linux/modules/cas_cache/context.c:6:
/root/work/open-cas-linux/modules/cas_cache/linux_kernel_version.h:44:10: fatal error: generated_defines.h: 没有那个文件或目录
   44 | #include "generated_defines.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:287：/root/work/open-cas-linux/modules/cas_cache/context.o] 错误 1
make[3]: *** [scripts/Makefile.build:518：/root/work/open-cas-linux/modules/cas_cache] 错误 2
make[2]: *** [Makefile:1848：/root/work/open-cas-linux/modules] 错误 2
make[2]: 离开目录“/usr/src/linux-headers-5.11.0-27-generic”
make[1]: *** [Makefile:48：default] 错误 2
make[1]: 离开目录“/root/work/open-cas-linux/modules”
make: *** [Makefile:22：modules] 错误 2

**Comment by robertbaldyga** [comment]
It looks like you did not run `./configure` script before running `make`.
Please see https://github.com/Open-CAS/open-cas-linux#source-compile-and-install.
