### ISSUE TITLE
ubuntu20.04.1  cannot boot cache disk when reboot machine

### ISSUE THREAD

**Issue by dcb1** [Open-CAS/open-cas-linux#950]
## Description
ubuntu20.04.1; python3.8.5; opencas 20; cache disk (8t nvme) ; cache line size 8k; intel cpu; mem 1T

## Expected Behavior
reboot machine casadm -L can get cache disk output

## Actual Behavior
reboot machine casadm -L  get empty output

## Context
1. the opencas.conf is correct
2. manual exec 'casctl start' can work; add 'casctl start' to rc.local and reboot can not work
3. when use cache line size =8k and 8T nvme:  give nvme a partition <=4t, it can work; >5t it can not work 
4. when use cache line size =16k and 8T nvme: it can work, but sometimes cache add successfully, but waiting interrupted, Rollback and stop cache
5. when diskname has multiple diskids(for example sda has two diskids scsi-0xxx,scsi-1xxx),  even if opencas.conf set diskid scsi-0xxxx, opencas load diskid scsi-1xxx. why???  

## Your Environment

* OpenCAS version (commit hash or tag):
* Operating System:
* Kernel version:
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by gaowayne** [comment]
@dcb1 please fill opencas version and many other questions

**Comment by gaowayne** [comment]
@dcb1 please also paste dmesg log

**Comment by gaowayne** [comment]
@dcb1 how customer create two diskid for one diskname?

**Comment by jfckm** [comment]
It could be due to starting cache on such big device taking a long time. However, it should result in boot dropping to emergency shell. Did you modify open-cas.service?

**Comment by dcb1** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已经收到,我会尽快回复您。祝一切顺利!

**Comment by arutk** [comment]
Hi @dcb1. Any update on this?

**Comment by dcb1** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已经收到,我会尽快回复您。祝一切顺利!

**Comment by robertbaldyga** [comment]
Hi @dcb1. Do you have any updates? Otherwise we will close this issue.

**Comment by dcb1** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已经收到,我会尽快回复您。祝一切顺利!
