### ISSUE TITLE
Kernel crashed when add core device

### ISSUE THREAD

**Issue by loyou** [Open-CAS/open-cas-linux#951]
## Description

add core devices cause the physical machine crashed and reboot, open cas device is set with acp cleaning policy and alru cleaning policy with different cache devices in one physical machine

## Expected Behavior

add core devices, and the physical machine wouldn't crash

## Actual Behavior

the physical machine crashed and reboot

## Steps to Reproduce

Preconditions：
lsblk
NAME     MAJ:MIN  RM   SIZE RO TYPE MOUNTPOINT
sda        8:0     0 278.9G  0 disk 
├─sda1     8:1     0     1M  0 part 
├─sda2     8:2     0    50G  0 part /
├─sda3     8:3     0    32G  0 part [SWAP]
└─sda4     8:4     0   196G  0 part /pitrix
sdb        8:16    0 446.6G  0 disk 
sdc        8:32    0 446.6G  0 disk 
sdd        8:48    0   3.7T  0 disk 
└─cas1-1 251:768   0   3.7T  0 disk 
sde        8:64    0   3.7T  0 disk 
└─cas1-2 251:1024  0   3.7T  0 disk 
sdf        8:80    0   3.7T  0 disk 
└─cas1-3 251:1280  0   3.7T  0 disk 
sdg        8:96    0   3.7T  0 disk 
└─cas1-4 251:1536  0   3.7T  0 disk 
sdh        8:112   0   3.7T  0 disk 
└─cas1-5 251:1792  0   3.7T  0 disk 
sdi        8:128   0   3.7T  0 disk 
└─cas2-1 251:2048  0   3.7T  0 disk 
sdj        8:144   0   3.7T  0 disk 
└─cas2-2 251:2304  0   3.7T  0 disk 
sdk        8:160   0   3.7T  0 disk 
└─cas2-3 251:2560  0   3.7T  0 disk 
sdl        8:176   0   3.7T  0 disk 
└─cas2-4 251:2816  0   3.7T  0 disk 
sdm        8:192   0   3.7T  0 disk 
└─cas2-5 251:3072  0   3.7T  0 disk 

casadm -L
type        id   disk       status       write policy   device
core pool   -    -          -            -              -
├core       -    /dev/sdm   Detached     -              -
├core       -    /dev/sdl   Detached     -              -
├core       -    /dev/sdk   Detached     -              -
├core       -    /dev/sde   Detached     -              -
├core       -    /dev/sdd   Detached     -              -
├core       -    /dev/sdi   Detached     -              -
└core       -    /dev/sdj   Detached     -              -
cache       2    /dev/sdc   Running      wb             -
cache       1    /dev/sdb   Incomplete   wb             -
├core       1    /dev/sdd   Inactive     -              /dev/cas1-1
├core       2    /dev/sde   Inactive     -              /dev/cas1-2
├core       3    /dev/sdf   Active       -              /dev/cas1-3
├core       4    /dev/sdg   Active       -              /dev/cas1-4
└core       5    /dev/sdh   Active       -              /dev/cas1-5

here are some information of cache device 1&2:
* Cache configuration: 
  Cache mode: (default: wt) wb
  Cache line size: (default: 4) 8
  Promotion policy: (default: always) always
  Cleaning policy: (default: alru) acp --->!!!Pay attention, will change this configuration later
  Sequential cutoff policy: (default: full) full

1.remove all cores devices and cache device as below:
casadm --remove-core -f -i -j 
casadm --remove-detached -d /dev/xxx
casadm -T -i
And after removing ,command "casadm -L" shows below:
casadm -L
type        id   disk       status       write policy   device
cache       2    /dev/sdc   Running   wb             -

2.start cache device /dev/sdb:
casadm --start-cache --cache-line-size 8 --cache-device /dev/sdb --force --cache-mode wb 
command "casadm -L" shows below:
casadm -L
type        id   disk       status       write policy   device
cache       2    /dev/sdc   Running   wb             -
cache       1    /dev/sdb   Running   wb             -
now the Cleaning policy of cache device 1 is alru, however the Cleaning policy of cache device 2 is acp

3.add core device attach to cache device 1 ,and it succeed
root@testsanc05:~# casadm -A -i 1 -d /dev/sdd
Successfully added core 1 to cache instance 1
root@testsanc05:~# casadm -A -i 1 -d /dev/sde
Successfully added core 2 to cache instance 1
root@testsanc05:~# casadm -A -i 1 -d /dev/sdf
Successfully added core 3 to cache instance 1
root@testsanc05:~# casadm -A -i 1 -d /dev/sdg
Successfully added core 4 to cache instance 1
root@testsanc05:~# casadm -A -i 1 -d /dev/sdh
Successfully added core 5 to cache instance 1

4.add core device attach to cache device 2 , and when the first core device added successfully, the physical machine crashed and reboot
root@testsanc05:~# casadm -A -i 2 -d /dev/sdi
Successfully added core 5 to cache instance 2

Then the physical machine reboot

## Context

the physical machine reboot, and i must wait util it start to continue my operation (add core devices)

## Possible Fix

NA

## Logs

[ 1369.556421] cache1: Inserting core core5
[ 1369.563373] cache1.core5: Successfully added
[ 1369.566204] [Open-CAS] Adding device /dev/disk/by-id/wwn-0x66c92bf0006ab4a728a35828084fe6e9 as core core5 to cache cache1
[ 1376.542057] cache2: Inserting core core1
[ 1376.542114] ------------[ cut here ]------------
[ 1376.542115] kernel BUG at /root/neil/opencas/open-cas-linux-v20.03.1.0292/modules/cas_cache/src/ocf/cleaning/acp.c:710!
[ 1376.646372] invalid opcode: 0000 [#1] SMP PTI
[ 1376.697579] CPU: 17 PID: 2339 Comm: cas_io_cache2_- Kdump: loaded Tainted: G           OE     5.4.0-59-generic 
[ 1376.800092] Hardware name: NULL SA5212M4-Q/NULL, BIOS 4.1.12 07/31/2017
[ 1376.851583] RIP: 0010:cleaning_policy_acp_add_core+0x175/0x1a0 [cas_cache]
[ 1376.902839] Code: 31 d2 be 03 00 00 00 4c 89 c7 e8 06 7c ea cc 31 c0 48 83 c4 08 5b 41 5c 41 5d 41 5e 41 5f 5d c3 31 c0 0f b7 de e9 c8 fe ff ff <0f> 0b 4c 89 e7 4c 89 45 d0 e8 ad 64 eb cc 4c 8b 45 d0 31 c9 31 d2
[ 1377.055120] RSP: 0018:ffffa6e748c8fdb8 EFLAGS: 00010286
[ 1377.104823] RAX: ffff94b2d3ce8000 RBX: ffffa6e748f81008 RCX: 00000000000e8d98
[ 1377.154796] RDX: 0000000000000001 RSI: 0000000000000001 RDI: ffffa6e748f81000
[ 1377.204253] RBP: ffffa6e748c8fde8 R08: 0000000000000000 R09: 0000000000000228
[ 1377.253029] R10: 0000000000000dc0 R11: 0000000000000000 R12: ffffa6e748f81000
[ 1377.300962] R13: 000003a3663fffff R14: 0000000000000001 R15: 0000000000009506
[ 1377.348103] FS:  0000000000000000(0000) GS:ffff94b3bf9c0000(0000) knlGS:0000000000000000
[ 1377.441160] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1377.487687] CR2: 00007f7b1b057870 CR3: 0000000e2a1f8001 CR4: 00000000003606e0
[ 1377.534214] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 1377.579659] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 1377.623774] Call Trace:
[ 1377.666378]  ocf_mngt_cache_add_core_insert+0x16b/0x2e0 [cas_cache]
[ 1377.709629]  _ocf_pipeline_run_step+0x78/0xd0 [cas_cache]
[ 1377.752538]  ocf_io_handle+0x34/0x40 [cas_cache]
[ 1377.795098]  ocf_queue_run_single+0x3a/0x40 [cas_cache]
[ 1377.837687]  ocf_queue_run+0x2a/0x40 [cas_cache]
[ 1377.879651]  _cas_io_queue_thread+0x6f/0x110 [cas_cache]
[ 1377.921705]  ? wait_woken+0x80/0x80
[ 1377.962724]  kthread+0x104/0x140
[ 1378.002270]  ? cas_rpool_try_put+0x80/0x80 [cas_cache]
[ 1378.042326]  ? kthread_park+0x90/0x90
[ 1378.081427]  ret_from_fork+0x35/0x40

## Your Environment

* OpenCAS version (commit hash or tag): v20.03.1.0292
* Operating System: Ubuntu 20.04.1
* Kernel version: 5.4.0-59-generic
* Cache device type (NAND/Optane/other): other (480GB SSD)
* Core device type (HDD/SSD/other): HDD
* Cache configuration: 
  Cache mode: (default: wt) wb
  Cache line size: (default: 4) 8
  Promotion policy: (default: always) always
  Cleaning policy: (default: alru) alru
  Sequential cutoff policy: (default: full) full
* Other (e.g. lsblk, casadm -P, casadm -L) 

lsblk
NAME     MAJ:MIN  RM   SIZE RO TYPE MOUNTPOINT
sda        8:0     0 278.9G  0 disk 
├─sda1     8:1     0     1M  0 part 
├─sda2     8:2     0    50G  0 part /
├─sda3     8:3     0    32G  0 part [SWAP]
└─sda4     8:4     0   196G  0 part /pitrix
sdb        8:16    0 446.6G  0 disk 
sdc        8:32    0 446.6G  0 disk 
sdd        8:48    0   3.7T  0 disk 
└─cas1-1 251:768   0   3.7T  0 disk 
sde        8:64    0   3.7T  0 disk 
└─cas1-2 251:1024  0   3.7T  0 disk 
sdf        8:80    0   3.7T  0 disk 
└─cas1-3 251:1280  0   3.7T  0 disk 
sdg        8:96    0   3.7T  0 disk 
└─cas1-4 251:1536  0   3.7T  0 disk 
sdh        8:112   0   3.7T  0 disk 
└─cas1-5 251:1792  0   3.7T  0 disk 
sdi        8:128   0   3.7T  0 disk 
└─cas2-1 251:2048  0   3.7T  0 disk 
sdj        8:144   0   3.7T  0 disk 
└─cas2-2 251:2304  0   3.7T  0 disk 
sdk        8:160   0   3.7T  0 disk 
└─cas2-3 251:2560  0   3.7T  0 disk 
sdl        8:176   0   3.7T  0 disk 
└─cas2-4 251:2816  0   3.7T  0 disk 
sdm        8:192   0   3.7T  0 disk 
└─cas2-5 251:3072  0   3.7T  0 disk 

casadm -L
type        id   disk       status       write policy   device
core pool   -    -          -            -              -
├core       -    /dev/sdm   Detached     -              -
├core       -    /dev/sdl   Detached     -              -
├core       -    /dev/sdk   Detached     -              -
├core       -    /dev/sde   Detached     -              -
├core       -    /dev/sdd   Detached     -              -
├core       -    /dev/sdi   Detached     -              -
└core       -    /dev/sdj   Detached     -              -
cache       2    /dev/sdc   Running      wb             -
cache       1    /dev/sdb   Incomplete   wb             -
├core       1    /dev/sdd   Inactive     -              /dev/cas1-1
├core       2    /dev/sde   Inactive     -              /dev/cas1-2
├core       3    /dev/sdf   Active       -              /dev/cas1-3
├core       4    /dev/sdg   Active       -              /dev/cas1-4
└core       5    /dev/sdh   Active       -              /dev/cas1-5

**Comment by mmichal10** [comment]
Hello @loyou,

thank you for reporting the issue. [We had implemented fix](https://github.com/Open-CAS/open-cas-linux/pull/904) and it was merged into 21.6 and 21.3.4 branches. I recommend you switching to the [latest stable CAS version](https://github.com/Open-CAS/open-cas-linux/releases/tag/v21.6).

**Comment by loyou** [comment]
thanks for your reply, we will try with latest 21.6 and feed back the test result.

**Comment by mmichal10** [comment]
@loyou how did the testing go?

**Comment by loyou** [comment]
@mmichal10 we have tested with 21.6 for several times and not reproduced until now, I will close this issue, thanks for your support.
