### ISSUE TITLE
check classified occupancy failed

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#959]
## Description

failure on test_ioclass_directory_file_operations[Filesystem.ext3]  
"Occupancy check failed!
Expected: 8388608.0 Byte, actual: 0.0 Blocks4096"
## Steps to Reproduce

1.	Prepare cache and core.
2.	Create and load IO class config file.
3.	Prepare ext3 filesystem and mounting /dev/cas1-1 at /tmp/cas1-1.
4.	Create directory /tmp/cas1-1/test_dir/nested_dir.
5.	Create test file.
6.	Check classified occupancy.
    Occupancy check failed!
    Expected: 8388608.0 Byte, actual: 0.0 Blocks4096
7.	Move test file out of classified directory.
8.	Check classified occupancy.
9.	Read test file.
10.	Check classified occupancy.
    ValueError: Subtracted value is too big. Result size cannot be negative.

## Logs

[2021_09_14_03_44_55_test_ioclass_directory_file_operations.zip](https://github.com/Open-CAS/open-cas-linux/files/7162684/2021_09_14_03_44_55_test_ioclass_directory_file_operations.zip)
## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0568.master
* Operating System:
* Kernel version:
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by mmichal10** [comment]
Failed on ext3. ext4 and xfs passed

**Comment by karolinavelkaja** [comment]
Failed on CAS 21.12.0.0593.master - xfs
[2021_11_29_15_13_25_test_ioclass_directory_file_operations.zip](https://github.com/Open-CAS/open-cas-linux/files/7618824/2021_11_29_15_13_25_test_ioclass_directory_file_operations.zip)

**Comment by karolinavelkaja** [comment]
Test case for 'xfs' still failing sometimes - CAS 22.03.0.0607.master

**Comment by mmichal10** [comment]
I've updated the patch. It shouldn't be a problem anymore.

**Comment by karolinavelkaja** [comment]
Confirming, https://github.com/Open-CAS/open-cas-linux/pull/1062 resolves the issue.
