### ISSUE TITLE
discards detected on incorrect device (cache)

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#960]
## Description

failure on test_trim_device_discard_support
Fail:
Ensure that discards were detected by blktrace on proper devices.
    -Discards expected: core - False, cache - False, cas - True
    -blktrace monitoring for device /dev/disk/by-id/scsi-35000c500ba41bdbc-part1 stopped
    -Parsing blktrace headers from /tmp/tmp.H12wxovcc8... Be patient
    -Parsed 0 blktrace headers from /tmp/tmp.H12wxovcc8
    -No TRIM instructions found in requests to /dev/disk/by-id/scsi-35000c500ba41bdbc-part1
    -blktrace monitoring for device /dev/disk/by-id/nvme-INTEL_SSDPE21K375GA_PHKE730600GQ375AGN-part1 stopped
    -Parsing blktrace headers from /tmp/tmp.OZi1p70aGL... Be patient
    -Parsed 155475 blktrace headers from /tmp/tmp.OZi1p70aGL
    **155475 TRIM instructions generated for /dev/disk/by-id/nvme-INTEL_SSDPE21K375GA_PHKE730600GQ375AGN-part1**

## Steps to Reproduce

1.	Create partitions on SSD and HDD devices. Create filesystem.
2.	Start cache and add core.
3.	Mount filesystem with discard option.
4.	Create random file.
5.	Start blktrace monitoring on all devices.
6.	Remove file.
7.	Ensure that discards were detected by blktrace on proper devices.
-Discards expected: core - False, cache - False, cas - True
-blktrace monitoring for device /dev/disk/by-id/scsi-35000c500ba41bdbc-part1 stopped
-Parsing blktrace headers from /tmp/tmp.H12wxovcc8... Be patient
-Parsed 0 blktrace headers from /tmp/tmp.H12wxovcc8
-No TRIM instructions found in requests to /dev/disk/by-id/scsi-35000c500ba41bdbc-part1
-blktrace monitoring for device /dev/disk/by-id/nvme-INTEL_SSDPE21K375GA_PHKE730600GQ375AGN-part1 stopped
-Parsing blktrace headers from /tmp/tmp.OZi1p70aGL... Be patient
-Parsed 155475 blktrace headers from /tmp/tmp.OZi1p70aGL
-155475 **TRIM instructions generated** for /dev/disk/by-id/nvme-INTEL_SSDPE21K375GA_PHKE730600GQ375AGN-part1
-blktrace monitoring for device /dev/cas1-1 stopped
-Parsing blktrace headers from /tmp/tmp.U9b0Io9IbX... Be patient
-Parsed 10 blktrace headers from /tmp/tmp.U9b0Io9IbX
-10 TRIM instructions generated for /dev/cas1-1

## Logs

[2021_09_13_15_50_00_test_trim_device_discard_support.zip](https://github.com/Open-CAS/open-cas-linux/files/7163187/2021_09_13_15_50_00_test_trim_device_discard_support.zip)

## Your Environment

* OpenCAS version (commit hash or tag):21.12.0.0568.master

* Operating System:
* Kernel version:
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by arutk** [comment]
It appears that CAS device announces discard support regardless of core / cache trim capabilities. Need to verify the test assumptions.

**Comment by karolinavelkaja** [comment]
Failed on 21.12.0.0593.master
example failure log:
[2021_11_29_19_42_05_test_trim_device_discard_support.zip](https://github.com/Open-CAS/open-cas-linux/files/7624768/2021_11_29_19_42_05_test_trim_device_discard_support.zip)

**Comment by pdebski21** [comment]
Checked on newest 22.03.0.0630.master on RHEL 84 and RHEL 83 and bug does not reproduce.

**Comment by karolinavelkaja** [comment]
Failed on 22.03.0.0631.master

**Comment by mmichal10** [comment]
One of the steps of discarding data from cas is invalidating it's metadata. If a cache line which is supposed to be discarded is dirty, invalidating it will require flushing metadata. Unfortunately, cas allocates flushing requests with the exactly the same flags as the original IO (in this case `discard` flag is set) so the page on the disk is discarded instead of being flushed. In case of power failure before the metadata is flushed to the disk, the data may be corrupted even if recovery will succeed.
