### ISSUE TITLE
Support for more recent kernel versions (5.12+)

### ISSUE THREAD

**Issue by kmajzero** [Open-CAS/open-cas-linux#987]
## Description

Update OpenCAS to support newer kernel versions.

Distribution-specific kernels are usually patched by vendors, sometimes quite heavily and thus substantially differ from vanilla versions. OpenCAS team aims for vanilla kernel revision support as a baseline.

## Reason

Future proofing OpenCAS and widening the userbase.

**Comment by scratchy** [comment]
Not possible to use it on latest ubuntu's without this fix here..
Any progress?

**Comment by robertbaldyga** [comment]
@scratchy We typically try to keep up with Ubuntu LTS. Support for kernel up to 5.15, which is expected for Ubuntu 22.04, will be added in Q2 2022 (in Open CAS v22.6).

**Comment by jamincollins** [comment]
Any update on this?

Ubuntu's 22.04 is slated for release on April 21, which is only a few days away.

**Comment by jamincollins** [comment]
It looks like the [v22.3 release](https://github.com/Open-CAS/open-cas-linux/releases/tag/v22.3) addressed this.

Additionally, testing shows that current [HEAD](https://github.com/Open-CAS/open-cas-linux/tree/bead2af4f4238201b95644e959485775d036b466) builds successfully under Arch Linux's `linux-lts` kernel.  Which as of this comment is: **5.15.49-1-lts**

**Comment by kmajzero** [comment]
You're right. Latest master branch indeed builds successfully on 5.15 kernel, however, it is still under testing. 
Upcoming 22.6 version is based on this and is scheduled to be released by the end of next week.

**Comment by mmichal10** [comment]
As the last week OpenCAS v22.6 was successfully released I'm closing this issue. For more details please [take a look at v22.6 release notes ](https://github.com/Open-CAS/open-cas-linux/releases/tag/v22.6)
