### ISSUE TITLE
[21.12] Inconsistencies in error stats: fio errors should be greater then 0

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#999]
## Description

test: test_soft_hot_plug_cache

from serial.log:
[ 5352.864425] cache1: Metadata Error
[ 5352.865251] cache1.core1: Failed to write data to cache sector: 2645696, bytes: 4096

## Steps to Reproduce

	1. Prepare cache and core devices
	2. Start cache in Write-Back cache mode and add core
	3. Run 'fio'
	4. Soft hot unplug cache device
	5. Wait for 'fio' to finish...
	6. Check for appropriate cache, core and fio errors
 Failed: There are some inconsistencies in error stats for Write-Back cache mode:  fio errors: 0, should be greater then 0
[2021_11_22_18_14_55_test_soft_hot_plug_cache.zip](https://github.com/Open-CAS/open-cas-linux/files/7588160/2021_11_22_18_14_55_test_soft_hot_plug_cache.zip)

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0589
* Operating System:
* Kernel version:
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by Deixx** [comment]
Might be already fixed on master

**Comment by karolinavelkaja** [comment]
Fixed, test passed on CAS 21.12.0.0593.master
